{
 "title": "Juno Node Performance (Generic)",
 "description": "Juno - Metrics",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "logsDatasource", "label": "logs", "query": "loki" }
  ]
 },
 "panels": [
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Juno Version",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "juno_info{job=\"juno\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Logs (last 1000 lines)",
   "type": "logs",
   "gridPos": { "h": 10, "w": 21, "x": 3, "y": 1 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"juno\"} |= ``",
     "maxLines": 1000
    }
   ]
  },
  {
   "title": "Error logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"juno\"} |= \"ERROR\""
    }
   ]
  },
  {
   "title": "15-minute Block Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(sync_blocks{job=\"juno\"}[15m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(sync_blocks{job=\"juno\"}[15m])",
     "legendFormat": "Blocks every 15 minutes"
    }
   ]
  },
  { "title": "Sync operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "L2 Sync Head",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sync_blockchain_height{job=\"juno\"}",
     "legendFormat": "Blockchain Height"
    }
   ]
  },
  {
   "title": "L1 Finalised",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "l1_finalised_height{job=\"juno\"}",
     "legendFormat": "Blockchain Height"
    }
   ]
  },
  {
   "title": "L2 Finalization Lag",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sync_blockchain_height{job=\"juno\"} - l1_l2_finalised_height{job=\"juno\"}",
     "legendFormat": "Blockchain Height"
    }
   ]
  },
  {
   "title": "L2 Head on L1",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "l1_l2_finalised_height{job=\"juno\"}",
     "legendFormat": "Blockchain Height"
    }
   ]
  },
  {
   "title": "L1 Latest",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "l1_latest_height{job=\"juno\"}",
     "legendFormat": "Blockchain Height"
    }
   ]
  },
  {
   "title": "Reorgs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sync_reorganisations{job=\"juno\"} ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blocks Behind",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "(sync_best_known_block_number{job=\"juno\"} - sync_blockchain_height{job=\"juno\"}) * (sync_blockchain_height{job=\"juno\"} != bool 0) ",
     "legendFormat": "Blocks Behind"
    }
   ]
  },
  {
   "title": "Verify Operation Latency Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "increase(sync_timers_bucket{job=\"juno\", op=\"verify\"}[$__interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Verify Operation Latency Distribution",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(sync_timers_bucket{job=\"juno\", op=\"verify\"}[$__range])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Store Operation Latency Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "increase(sync_timers_bucket{job=\"juno\", op=\"store\"}[$__interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Store operation Latency Distribution",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(sync_timers_bucket{job=\"juno\", op=\"store\"}[$__range])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "RPC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "RPC Requests(All Methods)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(rpc_server_requests{job=\"juno\"}[5m])",
     "legendFormat": "-"
    }
   ]
  },
  {
   "title": "Per Method",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 16, "x": 8, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(rpc_server_requests{job=\"juno\"}[5m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "AVG Server Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(rpc_server_requests_latency_sum{job=\"juno\"}[5m]) / rate(rpc_server_requests_latency_count{job=\"juno\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P95 Server Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(rpc_server_requests_latency_bucket{job=\"juno\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(rpc_server_failed_requests{job=\"juno\"}[5m])) by (method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VM Jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "vm_jobs{job=\"juno\"}",
     "legendFormat": "running"
    },
    {
     "expr": "vm_queue{job=\"juno\"}",
     "legendFormat": "queue"
    }
   ]
  },
  {
   "title": "RPC In-Flight Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rpc_gate_active_requests{job=\"juno\"}",
     "legendFormat": "active"
    },
    {
     "expr": "rpc_gate_queued_requests{job=\"juno\"}",
     "legendFormat": "queued"
    }
   ]
  },
  {
   "title": "RPC Rejected Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(rpc_gate_rejected_requests{job=\"juno\"}[$__rate_interval])",
     "legendFormat": "rejected"
    }
   ]
  },
  { "title": "Feeder", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 122 } },
  {
   "title": "P95 Feeder Response Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(feeder_client_request_latency_bucket{job=\"juno\"}[5m])) by (method, le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(gateway_client_request_latency_bucket{job=\"juno\"}[5m])) by (method, le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Feeder Non-200 request rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "targets": [
    {
     "expr": "sum(rate(feeder_client_request_latency_count{job=\"juno\", status!=\"200\"}[5m])) by (method, status)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(gateway_client_request_latency_count{job=\"juno\", status!=\"200\"}[5m])) by (method, status)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 143 } },
  {
   "title": "Go Version",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 144 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_info{job=\"juno\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "CPU Usage (Single Core %)",
   "type": "timeseries",
   "description": "go_memstats_lookups_total – counts how many pointer dereferences happened. This is a counter value so you can use rate() to lookups/s.",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 144 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"juno\"}[5m]) * 100",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "C Total Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 152 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jemalloc_active{job=\"juno\"}",
     "legendFormat": "memory"
    }
   ]
  },
  {
   "title": "Pebble Cache",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 152 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(pebble_block_cache_size{job=\"juno\"})",
     "legendFormat": "pebble_block_cache_size"
    }
   ]
  },
  {
   "title": "GO Total Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 160 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(go_memstats_sys_bytes{job=\"juno\"})",
     "legendFormat": "memory"
    }
   ]
  },
  {
   "title": "DB Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 160 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(rate(db_read_latency_count{job=\"juno\"}[5m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(rate(db_write_latency_count{job=\"juno\"}[5m]))",
     "legendFormat": "write"
    },
    {
     "expr": "sum(delta(db_read_latency_sum{job=\"juno\"}[5m])) / sum(delta(db_read_latency_count{job=\"juno\"}[5m]))",
     "legendFormat": "avg read latency"
    },
    {
     "expr": "sum(delta(db_write_latency_sum{job=\"juno\"}[5m])) / sum(delta(db_write_latency_count{job=\"juno\"}[5m]))",
     "legendFormat": "avg write latency"
    }
   ]
  },
  {
   "title": "GO Memory in Off-Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 168 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_mspan_inuse_bytes{job=\"juno\"} ",
     "legendFormat": "memstats_mspan_inuse_bytes"
    },
    {
     "expr": "go_memstats_mspan_sys_bytes{job=\"juno\"} ",
     "legendFormat": "memstats_mspan_sys_bytes"
    },
    {
     "expr": "go_memstats_mcache_inuse_bytes{job=\"juno\"} ",
     "legendFormat": "memstats_mcache_inuse_bytes"
    },
    {
     "expr": "go_memstats_mcache_sys_bytes{job=\"juno\"} ",
     "legendFormat": "memstats_mcache_sys_bytes"
    },
    {
     "expr": "go_memstats_buck_hash_sys_bytes{job=\"juno\"} ",
     "legendFormat": "memstats_buck_hash_sys_bytes"
    },
    {
     "expr": "go_memstats_gc_sys_bytes{job=\"juno\"} ",
     "legendFormat": "memstats_gc_sys_bytes"
    },
    {
     "expr": "go_memstats_other_sys_bytes{job=\"juno\"}",
     "legendFormat": "bytes of memory are used for other runtime allocations"
    },
    {
     "expr": "go_memstats_next_gc_bytes{job=\"juno\"} ",
     "legendFormat": "memstats_next_gc_bytes"
    }
   ]
  },
  {
   "title": "GO Memory in Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 168 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=\"juno\"} ",
     "legendFormat": "memstats_heap_alloc_bytes"
    },
    {
     "expr": "go_memstats_heap_sys_bytes{job=\"juno\"} ",
     "legendFormat": "memstats_heap_sys_bytes"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{job=\"juno\"} ",
     "legendFormat": "memstats_heap_idle_bytes"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"juno\"} ",
     "legendFormat": "memstats_heap_inuse_bytes"
    },
    {
     "expr": "go_memstats_heap_released_bytes{job=\"juno\"} ",
     "legendFormat": "memstats_heap_released_bytes"
    }
   ]
  },
  {
   "title": "GO Memory in Stack",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 176 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_stack_inuse_bytes{job=\"juno\"} ",
     "legendFormat": "memstats_stack_inuse_bytes"
    },
    {
     "expr": "go_memstats_stack_sys_bytes{job=\"juno\"} ",
     "legendFormat": "memstats_stack_sys_byte"
    }
   ]
  },
  {
   "title": "GO Rate of Objects Allocated",
   "type": "timeseries",
   "description": "shows how many heap objects are allocated. This is a counter value so you can use rate() to objects allocated/s.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 176 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total{job=\"juno\"}[5m])",
     "legendFormat": "memstats_mallocs_total"
    }
   ]
  },
  {
   "title": "GO Number of Live Objects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 184 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_memstats_mallocs_total{job=\"juno\"} - go_memstats_frees_total{job=\"juno\"} ",
     "legendFormat": "Number of Live Objects"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 184 },
   "targets": [
    {
     "expr": "go_goroutines{job=\"juno\"} ",
     "legendFormat": "goroutines"
    }
   ]
  },
  {
   "title": "GO Rates of Allocation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 192 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=\"juno\"}[5m])",
     "legendFormat": "memstats_alloc_bytes_total"
    }
   ]
  },
  {
   "title": "GC duration quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 192 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=\"juno\"} ",
     "legendFormat": "{{quantile}}"
    }
   ]
  }
 ]
}