coverage:
  range: 70..90
  status:
    project:
      default:
        target: 70%
    patch:
      default:
        target: 60%
        only_pulls: true
ignore:
  - mocks
  - l1/internal/contract/starknet.go
  - grpc/gen/*