coverage:
  range: 70..90
  status:
    project:
      default:
        target: 75%
    patch:
      default:
        target: 62%
        threshold: 2%
        only_pulls: true
ignore:
  - mocks
  - l1/internal/contract/starknet.go
