version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exhaustruct
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - intrange
    - lll
    - makezero
    - misspell
    - mnd
    - nakedret
    - nilerr
    - nilnesserr
    - noctx
    - nolintlint
    - prealloc
    - staticcheck
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - whitespace
  settings:
    depguard:
      rules:
        logger:
          deny:
            - pkg: github.com/sirupsen/logrus
              desc: use github.com/NethermindEth/juno/utils for logging
    dupl:
      threshold: 100
    funlen:
      lines: 120
      statements: 50
    goconst:
      min-len: 2
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - sloppyReassign
        - dupImport # https://github.com/go-critic/go-critic/issues/845
        - ifElseChain
        - octalLiteral
        - whyNoLint
        - unnamedResult
        # note(rdr): when lib is called x and then you do x = x.New(). Widely used in the repo. 
        #            Should we change it?
        - importShadow
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 15
    gosec:
      excludes:
        - G115 #TODO: remove after fixing https://github.com/securego/gosec/issues/1212
    govet:
      enable:
        - nilness
    lll:
      line-length: 140 # todo(rdr): change this to 100
    misspell:
      locale: UK
    mnd:
      checks:
        - argument
        - case
        - condition
        - return
      ignored-numbers:
        - "0"
        - "1"
        - "2"
        - "3"
        - "4"
        - "8"
        - "16"
        - "24"
        - "32"
    nolintlint:
      allow-unused: false
      require-explanation: false # todo(rdr): this should be switched to true for non test files
      require-specific: true
    prealloc:
      simple: true
      range-loops: false
      for-loops: false
    staticcheck:
      checks:
        - "all"
        # note(rdr): change if `type` to `switch type`. I would agree in general but it also applies
        #            it even if there is only one `if` and it is not possible to relax it
        - "-QF1003"
        # note(rdr): doesn't allow the use of optional embedded fields in structs. . I am not sure
        #            if it is beneficial
        - "-QF1008"
        # note: this disables deprecation warning because it is active for .golangci_diff.yaml
        - "-SA1019"
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - exhaustruct
          - funlen
          - gosec
          - goconst
          - lll
          - mnd
        path: _test\.go
      - linters:
          - exhaustruct
        path-except: adapters/.+\.go
      - linters:
          - staticcheck
        path: vm/state\.go
        text: ST1003
      - linters:
          - lll
        source: "^//go:generate "
formatters:
  enable:
    - gci
    - gofumpt
  exclusions:
    generated: lax
run:
  timeout: 10m
