// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v7.34.0
// source: consensus/propeller/proto/propeller.proto

package proto

import (
	common "github.com/starknet-io/starknet-p2p-specs/p2p/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A Merkle proof consisting of sibling hashes used to verify that a leaf belongs to a Merkle tree.
// Each sibling hash is 32 bytes (SHA-256). The siblings are ordered from leaf level to root level.
type MerkleProof struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The sibling hashes needed to reconstruct the path from the leaf to the root.
	// Each hash is 32 bytes.
	Siblings      []*common.Hash256 `protobuf:"bytes,1,rep,name=siblings,proto3" json:"siblings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerkleProof) Reset() {
	*x = MerkleProof{}
	mi := &file_consensus_propeller_proto_propeller_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerkleProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerkleProof) ProtoMessage() {}

func (x *MerkleProof) ProtoReflect() protoreflect.Message {
	mi := &file_consensus_propeller_proto_propeller_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerkleProof.ProtoReflect.Descriptor instead.
func (*MerkleProof) Descriptor() ([]byte, []int) {
	return file_consensus_propeller_proto_propeller_proto_rawDescGZIP(), []int{0}
}

func (x *MerkleProof) GetSiblings() []*common.Hash256 {
	if x != nil {
		return x.Siblings
	}
	return nil
}

// A single unit in the Propeller protocol containing a shard of erasure-coded data
// along with cryptographic proofs for verification.
type PropellerUnit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The actual data shard (erasure-coded fragment of the original message).
	Shard []byte `protobuf:"bytes,1,opt,name=shard,proto3" json:"shard,omitempty"`
	// The position of this shard in the erasure coding scheme.
	Index uint64 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	// The Merkle root of all shards, used to verify shard integrity.
	MerkleRoot *common.Hash256 `protobuf:"bytes,3,opt,name=merkle_root,json=merkleRoot,proto3" json:"merkle_root,omitempty"`
	// The Merkle proof that this shard belongs to the tree with the given root.
	MerkleProof *MerkleProof `protobuf:"bytes,4,opt,name=merkle_proof,json=merkleProof,proto3" json:"merkle_proof,omitempty"`
	// The peer ID of the original publisher who created and signed this unit.
	Publisher *common.PeerID `protobuf:"bytes,5,opt,name=publisher,proto3" json:"publisher,omitempty"`
	// Cryptographic signature from the publisher over the merkle_root.
	Signature []byte `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
	// TODO(AndrewL): consider re-naming channel
	// TODO(AndrewL): make it uint64 instead of uint32.
	// Logical channel identifier for multiplexing different message streams.
	Channel       uint32 `protobuf:"varint,7,opt,name=channel,proto3" json:"channel,omitempty"` // TODO(AndrewL): CRITICAL: protect against replay attacks (maybe using a timestamp)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PropellerUnit) Reset() {
	*x = PropellerUnit{}
	mi := &file_consensus_propeller_proto_propeller_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropellerUnit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropellerUnit) ProtoMessage() {}

func (x *PropellerUnit) ProtoReflect() protoreflect.Message {
	mi := &file_consensus_propeller_proto_propeller_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropellerUnit.ProtoReflect.Descriptor instead.
func (*PropellerUnit) Descriptor() ([]byte, []int) {
	return file_consensus_propeller_proto_propeller_proto_rawDescGZIP(), []int{1}
}

func (x *PropellerUnit) GetShard() []byte {
	if x != nil {
		return x.Shard
	}
	return nil
}

func (x *PropellerUnit) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *PropellerUnit) GetMerkleRoot() *common.Hash256 {
	if x != nil {
		return x.MerkleRoot
	}
	return nil
}

func (x *PropellerUnit) GetMerkleProof() *MerkleProof {
	if x != nil {
		return x.MerkleProof
	}
	return nil
}

func (x *PropellerUnit) GetPublisher() *common.PeerID {
	if x != nil {
		return x.Publisher
	}
	return nil
}

func (x *PropellerUnit) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *PropellerUnit) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

// A batch of PropellerUnits for efficient transmission.
type PropellerUnitBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Batch         []*PropellerUnit       `protobuf:"bytes,1,rep,name=batch,proto3" json:"batch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PropellerUnitBatch) Reset() {
	*x = PropellerUnitBatch{}
	mi := &file_consensus_propeller_proto_propeller_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropellerUnitBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropellerUnitBatch) ProtoMessage() {}

func (x *PropellerUnitBatch) ProtoReflect() protoreflect.Message {
	mi := &file_consensus_propeller_proto_propeller_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropellerUnitBatch.ProtoReflect.Descriptor instead.
func (*PropellerUnitBatch) Descriptor() ([]byte, []int) {
	return file_consensus_propeller_proto_propeller_proto_rawDescGZIP(), []int{2}
}

func (x *PropellerUnitBatch) GetBatch() []*PropellerUnit {
	if x != nil {
		return x.Batch
	}
	return nil
}

var File_consensus_propeller_proto_propeller_proto protoreflect.FileDescriptor

const file_consensus_propeller_proto_propeller_proto_rawDesc = "" +
	"\n" +
	")consensus/propeller/proto/propeller.proto\x1a\x16p2p/proto/common.proto\"3\n" +
	"\vMerkleProof\x12$\n" +
	"\bsiblings\x18\x01 \x03(\v2\b.Hash256R\bsiblings\"\xf6\x01\n" +
	"\rPropellerUnit\x12\x14\n" +
	"\x05shard\x18\x01 \x01(\fR\x05shard\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x04R\x05index\x12)\n" +
	"\vmerkle_root\x18\x03 \x01(\v2\b.Hash256R\n" +
	"merkleRoot\x12/\n" +
	"\fmerkle_proof\x18\x04 \x01(\v2\f.MerkleProofR\vmerkleProof\x12%\n" +
	"\tpublisher\x18\x05 \x01(\v2\a.PeerIDR\tpublisher\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\fR\tsignature\x12\x18\n" +
	"\achannel\x18\a \x01(\rR\achannel\":\n" +
	"\x12PropellerUnitBatch\x12$\n" +
	"\x05batch\x18\x01 \x03(\v2\x0e.PropellerUnitR\x05batchB9Z7github.com/NethermindEth/juno/consensus/propeller/protob\x06proto3"

var (
	file_consensus_propeller_proto_propeller_proto_rawDescOnce sync.Once
	file_consensus_propeller_proto_propeller_proto_rawDescData []byte
)

func file_consensus_propeller_proto_propeller_proto_rawDescGZIP() []byte {
	file_consensus_propeller_proto_propeller_proto_rawDescOnce.Do(func() {
		file_consensus_propeller_proto_propeller_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_consensus_propeller_proto_propeller_proto_rawDesc), len(file_consensus_propeller_proto_propeller_proto_rawDesc)))
	})
	return file_consensus_propeller_proto_propeller_proto_rawDescData
}

var file_consensus_propeller_proto_propeller_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_consensus_propeller_proto_propeller_proto_goTypes = []any{
	(*MerkleProof)(nil),        // 0: MerkleProof
	(*PropellerUnit)(nil),      // 1: PropellerUnit
	(*PropellerUnitBatch)(nil), // 2: PropellerUnitBatch
	(*common.Hash256)(nil),     // 3: Hash256
	(*common.PeerID)(nil),      // 4: PeerID
}
var file_consensus_propeller_proto_propeller_proto_depIdxs = []int32{
	3, // 0: MerkleProof.siblings:type_name -> Hash256
	3, // 1: PropellerUnit.merkle_root:type_name -> Hash256
	0, // 2: PropellerUnit.merkle_proof:type_name -> MerkleProof
	4, // 3: PropellerUnit.publisher:type_name -> PeerID
	1, // 4: PropellerUnitBatch.batch:type_name -> PropellerUnit
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_consensus_propeller_proto_propeller_proto_init() }
func file_consensus_propeller_proto_propeller_proto_init() {
	if File_consensus_propeller_proto_propeller_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_consensus_propeller_proto_propeller_proto_rawDesc), len(file_consensus_propeller_proto_propeller_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_consensus_propeller_proto_propeller_proto_goTypes,
		DependencyIndexes: file_consensus_propeller_proto_propeller_proto_depIdxs,
		MessageInfos:      file_consensus_propeller_proto_propeller_proto_msgTypes,
	}.Build()
	File_consensus_propeller_proto_propeller_proto = out.File
	file_consensus_propeller_proto_propeller_proto_goTypes = nil
	file_consensus_propeller_proto_propeller_proto_depIdxs = nil
}
