// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: consensus/proto/wal.proto

package proto

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// EndHeight marks the end of the given height inside WAL.
type EndHeight struct {
	Height               int64    `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EndHeight) Reset()         { *m = EndHeight{} }
func (m *EndHeight) String() string { return proto.CompactTextString(m) }
func (*EndHeight) ProtoMessage()    {}
func (*EndHeight) Descriptor() ([]byte, []int) {
	return fileDescriptor_b931f50d3f528d30, []int{0}
}
func (m *EndHeight) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EndHeight.Unmarshal(m, b)
}
func (m *EndHeight) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EndHeight.Marshal(b, m, deterministic)
}
func (m *EndHeight) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndHeight.Merge(m, src)
}
func (m *EndHeight) XXX_Size() int {
	return xxx_messageInfo_EndHeight.Size(m)
}
func (m *EndHeight) XXX_DiscardUnknown() {
	xxx_messageInfo_EndHeight.DiscardUnknown(m)
}

var xxx_messageInfo_EndHeight proto.InternalMessageInfo

func (m *EndHeight) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

// Todo: implement other msg types. Currently only implement EndHeight
type WALMessage struct {
	// Types that are valid to be assigned to Sum:
	//
	//	*WALMessage_EndHeight
	Sum                  isWALMessage_Sum `protobuf_oneof:"sum"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *WALMessage) Reset()         { *m = WALMessage{} }
func (m *WALMessage) String() string { return proto.CompactTextString(m) }
func (*WALMessage) ProtoMessage()    {}
func (*WALMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_b931f50d3f528d30, []int{1}
}
func (m *WALMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WALMessage.Unmarshal(m, b)
}
func (m *WALMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WALMessage.Marshal(b, m, deterministic)
}
func (m *WALMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WALMessage.Merge(m, src)
}
func (m *WALMessage) XXX_Size() int {
	return xxx_messageInfo_WALMessage.Size(m)
}
func (m *WALMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_WALMessage.DiscardUnknown(m)
}

var xxx_messageInfo_WALMessage proto.InternalMessageInfo

type isWALMessage_Sum interface {
	isWALMessage_Sum()
}

type WALMessage_EndHeight struct {
	EndHeight *EndHeight `protobuf:"bytes,1,opt,name=end_height,json=endHeight,proto3,oneof" json:"end_height,omitempty"`
}

func (*WALMessage_EndHeight) isWALMessage_Sum() {}

func (m *WALMessage) GetSum() isWALMessage_Sum {
	if m != nil {
		return m.Sum
	}
	return nil
}

func (m *WALMessage) GetEndHeight() *EndHeight {
	if x, ok := m.GetSum().(*WALMessage_EndHeight); ok {
		return x.EndHeight
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*WALMessage) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*WALMessage_EndHeight)(nil),
	}
}

// TimedWALMessage wraps WALMessage and adds Time for debugging purposes.
type TimedWALMessage struct {
	Time                 time.Time   `protobuf:"bytes,1,opt,name=time,proto3,stdtime" json:"time"`
	Msg                  *WALMessage `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *TimedWALMessage) Reset()         { *m = TimedWALMessage{} }
func (m *TimedWALMessage) String() string { return proto.CompactTextString(m) }
func (*TimedWALMessage) ProtoMessage()    {}
func (*TimedWALMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_b931f50d3f528d30, []int{2}
}
func (m *TimedWALMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimedWALMessage.Unmarshal(m, b)
}
func (m *TimedWALMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimedWALMessage.Marshal(b, m, deterministic)
}
func (m *TimedWALMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimedWALMessage.Merge(m, src)
}
func (m *TimedWALMessage) XXX_Size() int {
	return xxx_messageInfo_TimedWALMessage.Size(m)
}
func (m *TimedWALMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_TimedWALMessage.DiscardUnknown(m)
}

var xxx_messageInfo_TimedWALMessage proto.InternalMessageInfo

func (m *TimedWALMessage) GetTime() time.Time {
	if m != nil {
		return m.Time
	}
	return time.Time{}
}

func (m *TimedWALMessage) GetMsg() *WALMessage {
	if m != nil {
		return m.Msg
	}
	return nil
}

func init() {
	proto.RegisterType((*EndHeight)(nil), "tendermint.consensus.EndHeight")
	proto.RegisterType((*WALMessage)(nil), "tendermint.consensus.WALMessage")
	proto.RegisterType((*TimedWALMessage)(nil), "tendermint.consensus.TimedWALMessage")
}

func init() { proto.RegisterFile("consensus/proto/wal.proto", fileDescriptor_b931f50d3f528d30) }

var fileDescriptor_b931f50d3f528d30 = []byte{
	// 277 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4c, 0xce, 0xcf, 0x2b,
	0x4e, 0xcd, 0x2b, 0x2e, 0x2d, 0xd6, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x2f, 0x4f, 0xcc, 0xd1,
	0x03, 0xb3, 0x84, 0x44, 0x4a, 0x52, 0xf3, 0x52, 0x52, 0x8b, 0x72, 0x33, 0xf3, 0x4a, 0xf4, 0xe0,
	0xaa, 0xa4, 0xe4, 0xd3, 0xf3, 0xf3, 0xd3, 0x73, 0x52, 0x21, 0xaa, 0x93, 0x4a, 0xd3, 0xf4, 0x4b,
	0x32, 0x73, 0x53, 0x8b, 0x4b, 0x12, 0x73, 0x0b, 0x20, 0xda, 0xa4, 0x44, 0xd2, 0xf3, 0xd3, 0xf3,
	0x21, 0x66, 0x81, 0x58, 0x10, 0x51, 0x25, 0x65, 0x2e, 0x4e, 0xd7, 0xbc, 0x14, 0x8f, 0xd4, 0xcc,
	0xf4, 0x8c, 0x12, 0x21, 0x31, 0x2e, 0xb6, 0x0c, 0x30, 0x4b, 0x82, 0x51, 0x81, 0x51, 0x83, 0x39,
	0x08, 0xca, 0x53, 0x0a, 0xe5, 0xe2, 0x0a, 0x77, 0xf4, 0xf1, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f,
	0x15, 0x72, 0xe0, 0xe2, 0x4a, 0xcd, 0x4b, 0x89, 0x47, 0x52, 0xc9, 0x6d, 0x24, 0xaf, 0x87, 0xcd,
	0x51, 0x7a, 0x70, 0xa3, 0x3d, 0x18, 0x82, 0x38, 0x53, 0x61, 0x1c, 0x27, 0x56, 0x2e, 0xe6, 0xe2,
	0xd2, 0x5c, 0xa5, 0x7a, 0x2e, 0xfe, 0x90, 0xcc, 0xdc, 0xd4, 0x14, 0x24, 0xb3, 0x2d, 0xb8, 0x58,
	0x40, 0xee, 0x86, 0x9a, 0x2a, 0xa5, 0x07, 0xf1, 0x94, 0x1e, 0xcc, 0x53, 0x7a, 0x21, 0x30, 0x4f,
	0x39, 0x71, 0x9c, 0xb8, 0x27, 0xcf, 0x30, 0xe1, 0xbe, 0x3c, 0x63, 0x10, 0x58, 0x87, 0x90, 0x11,
	0x17, 0x73, 0x6e, 0x71, 0xba, 0x04, 0x13, 0x58, 0xa3, 0x02, 0x76, 0xe7, 0x20, 0x2c, 0x0a, 0x02,
	0x29, 0x76, 0xd2, 0x8f, 0xd2, 0x4d, 0xcf, 0x2c, 0xc9, 0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5,
	0xf7, 0x4b, 0x2d, 0xc9, 0x00, 0x6b, 0x49, 0x71, 0x2d, 0xc9, 0xd0, 0xcf, 0x2a, 0xcd, 0xcb, 0xd7,
	0x47, 0x8b, 0x84, 0x24, 0x36, 0x30, 0x65, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x97, 0xce, 0x2d,
	0x1b, 0x9e, 0x01, 0x00, 0x00,
}
