[package]
name = "erc20"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = ">=2.10.1"
openzeppelin_upgrades = ">=1.0.0"
openzeppelin_access = ">=1.0.0"
openzeppelin_token = ">=1.0.0"

[[target.starknet-contract]]
