// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/NethermindEth/juno/l1 (interfaces: IPWatcher)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_watcher.go -package=mocks github.com/NethermindEth/juno/l1 IPWatcher
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	contract "github.com/NethermindEth/juno/l1/contract"
	bind "github.com/ethereum/go-ethereum/accounts/abi/bind"
	event "github.com/ethereum/go-ethereum/event"
	gomock "go.uber.org/mock/gomock"
)

// MockIPWatcher is a mock of IPWatcher interface.
type MockIPWatcher struct {
	ctrl     *gomock.Controller
	recorder *MockIPWatcherMockRecorder
	isgomock struct{}
}

// MockIPWatcherMockRecorder is the mock recorder for MockIPWatcher.
type MockIPWatcherMockRecorder struct {
	mock *MockIPWatcher
}

// NewMockIPWatcher creates a new mock instance.
func NewMockIPWatcher(ctrl *gomock.Controller) *MockIPWatcher {
	mock := &MockIPWatcher{ctrl: ctrl}
	mock.recorder = &MockIPWatcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPWatcher) EXPECT() *MockIPWatcherMockRecorder {
	return m.recorder
}

// WatchIPAdded mocks base method.
func (m *MockIPWatcher) WatchIPAdded(arg0 *bind.WatchOpts, arg1 chan<- *contract.IPAddressRegistryIPAdded) (event.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WatchIPAdded", arg0, arg1)
	ret0, _ := ret[0].(event.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WatchIPAdded indicates an expected call of WatchIPAdded.
func (mr *MockIPWatcherMockRecorder) WatchIPAdded(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WatchIPAdded", reflect.TypeOf((*MockIPWatcher)(nil).WatchIPAdded), arg0, arg1)
}

// WatchIPRemoved mocks base method.
func (m *MockIPWatcher) WatchIPRemoved(arg0 *bind.WatchOpts, arg1 chan<- *contract.IPAddressRegistryIPRemoved) (event.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WatchIPRemoved", arg0, arg1)
	ret0, _ := ret[0].(event.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WatchIPRemoved indicates an expected call of WatchIPRemoved.
func (mr *MockIPWatcherMockRecorder) WatchIPRemoved(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WatchIPRemoved", reflect.TypeOf((*MockIPWatcher)(nil).WatchIPRemoved), arg0, arg1)
}
