// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/NethermindEth/juno/core/state (interfaces: StateReader)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/mock_state_reader.go -package=mocks github.com/NethermindEth/juno/core/state StateReader
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	core "github.com/NethermindEth/juno/core"
	felt "github.com/NethermindEth/juno/core/felt"
	trie2 "github.com/NethermindEth/juno/core/trie2"
	gomock "go.uber.org/mock/gomock"
)

// MockStateReader is a mock of StateReader interface.
type MockStateReader struct {
	ctrl     *gomock.Controller
	recorder *MockStateReaderMockRecorder
}

// MockStateReaderMockRecorder is the mock recorder for MockStateReader.
type MockStateReaderMockRecorder struct {
	mock *MockStateReader
}

// NewMockStateReader creates a new mock instance.
func NewMockStateReader(ctrl *gomock.Controller) *MockStateReader {
	mock := &MockStateReader{ctrl: ctrl}
	mock.recorder = &MockStateReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStateReader) EXPECT() *MockStateReaderMockRecorder {
	return m.recorder
}

// Class mocks base method.
func (m *MockStateReader) Class(arg0 felt.Felt) (*core.DeclaredClass, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Class", arg0)
	ret0, _ := ret[0].(*core.DeclaredClass)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Class indicates an expected call of Class.
func (mr *MockStateReaderMockRecorder) Class(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Class", reflect.TypeOf((*MockStateReader)(nil).Class), arg0)
}

// ClassTrie mocks base method.
func (m *MockStateReader) ClassTrie() (*trie2.Trie, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClassTrie")
	ret0, _ := ret[0].(*trie2.Trie)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClassTrie indicates an expected call of ClassTrie.
func (mr *MockStateReaderMockRecorder) ClassTrie() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClassTrie", reflect.TypeOf((*MockStateReader)(nil).ClassTrie))
}

// ContractClassHash mocks base method.
func (m *MockStateReader) ContractClassHash(arg0 felt.Felt) (felt.Felt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContractClassHash", arg0)
	ret0, _ := ret[0].(felt.Felt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ContractClassHash indicates an expected call of ContractClassHash.
func (mr *MockStateReaderMockRecorder) ContractClassHash(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContractClassHash", reflect.TypeOf((*MockStateReader)(nil).ContractClassHash), arg0)
}

// ContractNonce mocks base method.
func (m *MockStateReader) ContractNonce(arg0 felt.Felt) (felt.Felt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContractNonce", arg0)
	ret0, _ := ret[0].(felt.Felt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ContractNonce indicates an expected call of ContractNonce.
func (mr *MockStateReaderMockRecorder) ContractNonce(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContractNonce", reflect.TypeOf((*MockStateReader)(nil).ContractNonce), arg0)
}

// ContractStorage mocks base method.
func (m *MockStateReader) ContractStorage(arg0, arg1 felt.Felt) (felt.Felt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContractStorage", arg0, arg1)
	ret0, _ := ret[0].(felt.Felt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ContractStorage indicates an expected call of ContractStorage.
func (mr *MockStateReaderMockRecorder) ContractStorage(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContractStorage", reflect.TypeOf((*MockStateReader)(nil).ContractStorage), arg0, arg1)
}

// ContractStorageTrie mocks base method.
func (m *MockStateReader) ContractStorageTrie(arg0 felt.Felt) (*trie2.Trie, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContractStorageTrie", arg0)
	ret0, _ := ret[0].(*trie2.Trie)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ContractStorageTrie indicates an expected call of ContractStorageTrie.
func (mr *MockStateReaderMockRecorder) ContractStorageTrie(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContractStorageTrie", reflect.TypeOf((*MockStateReader)(nil).ContractStorageTrie), arg0)
}

// ContractTrie mocks base method.
func (m *MockStateReader) ContractTrie() (*trie2.Trie, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContractTrie")
	ret0, _ := ret[0].(*trie2.Trie)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ContractTrie indicates an expected call of ContractTrie.
func (mr *MockStateReaderMockRecorder) ContractTrie() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContractTrie", reflect.TypeOf((*MockStateReader)(nil).ContractTrie))
}
