// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/NethermindEth/juno/core (interfaces: StateHistoryReader)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_state.go -package=mocks github.com/NethermindEth/juno/core StateHistoryReader
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	core "github.com/NethermindEth/juno/core"
	felt "github.com/NethermindEth/juno/core/felt"
	commontrie "github.com/NethermindEth/juno/core/state/commontrie"
	gomock "go.uber.org/mock/gomock"
)

// MockStateHistoryReader is a mock of StateHistoryReader interface.
type MockStateHistoryReader struct {
	ctrl     *gomock.Controller
	recorder *MockStateHistoryReaderMockRecorder
	isgomock struct{}
}

// MockStateHistoryReaderMockRecorder is the mock recorder for MockStateHistoryReader.
type MockStateHistoryReaderMockRecorder struct {
	mock *MockStateHistoryReader
}

// NewMockStateHistoryReader creates a new mock instance.
func NewMockStateHistoryReader(ctrl *gomock.Controller) *MockStateHistoryReader {
	mock := &MockStateHistoryReader{ctrl: ctrl}
	mock.recorder = &MockStateHistoryReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStateHistoryReader) EXPECT() *MockStateHistoryReaderMockRecorder {
	return m.recorder
}

// Class mocks base method.
func (m *MockStateHistoryReader) Class(classHash *felt.Felt) (*core.DeclaredClassDefinition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Class", classHash)
	ret0, _ := ret[0].(*core.DeclaredClassDefinition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Class indicates an expected call of Class.
func (mr *MockStateHistoryReaderMockRecorder) Class(classHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Class", reflect.TypeOf((*MockStateHistoryReader)(nil).Class), classHash)
}

// ClassTrie mocks base method.
func (m *MockStateHistoryReader) ClassTrie() (commontrie.Trie, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClassTrie")
	ret0, _ := ret[0].(commontrie.Trie)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClassTrie indicates an expected call of ClassTrie.
func (mr *MockStateHistoryReaderMockRecorder) ClassTrie() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClassTrie", reflect.TypeOf((*MockStateHistoryReader)(nil).ClassTrie))
}

// CompiledClassHash mocks base method.
func (m *MockStateHistoryReader) CompiledClassHash(classHash *felt.SierraClassHash) (felt.CasmClassHash, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompiledClassHash", classHash)
	ret0, _ := ret[0].(felt.CasmClassHash)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompiledClassHash indicates an expected call of CompiledClassHash.
func (mr *MockStateHistoryReaderMockRecorder) CompiledClassHash(classHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompiledClassHash", reflect.TypeOf((*MockStateHistoryReader)(nil).CompiledClassHash), classHash)
}

// CompiledClassHashAt mocks base method.
func (m *MockStateHistoryReader) CompiledClassHashAt(classHash *felt.SierraClassHash, blockNumber uint64) (felt.CasmClassHash, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompiledClassHashAt", classHash, blockNumber)
	ret0, _ := ret[0].(felt.CasmClassHash)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompiledClassHashAt indicates an expected call of CompiledClassHashAt.
func (mr *MockStateHistoryReaderMockRecorder) CompiledClassHashAt(classHash, blockNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompiledClassHashAt", reflect.TypeOf((*MockStateHistoryReader)(nil).CompiledClassHashAt), classHash, blockNumber)
}

// CompiledClassHashV2 mocks base method.
func (m *MockStateHistoryReader) CompiledClassHashV2(classHash *felt.SierraClassHash) (felt.CasmClassHash, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompiledClassHashV2", classHash)
	ret0, _ := ret[0].(felt.CasmClassHash)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompiledClassHashV2 indicates an expected call of CompiledClassHashV2.
func (mr *MockStateHistoryReaderMockRecorder) CompiledClassHashV2(classHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompiledClassHashV2", reflect.TypeOf((*MockStateHistoryReader)(nil).CompiledClassHashV2), classHash)
}

// ContractClassHash mocks base method.
func (m *MockStateHistoryReader) ContractClassHash(addr *felt.Felt) (felt.Felt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContractClassHash", addr)
	ret0, _ := ret[0].(felt.Felt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ContractClassHash indicates an expected call of ContractClassHash.
func (mr *MockStateHistoryReaderMockRecorder) ContractClassHash(addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContractClassHash", reflect.TypeOf((*MockStateHistoryReader)(nil).ContractClassHash), addr)
}

// ContractClassHashAt mocks base method.
func (m *MockStateHistoryReader) ContractClassHashAt(addr *felt.Felt, blockNumber uint64) (felt.Felt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContractClassHashAt", addr, blockNumber)
	ret0, _ := ret[0].(felt.Felt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ContractClassHashAt indicates an expected call of ContractClassHashAt.
func (mr *MockStateHistoryReaderMockRecorder) ContractClassHashAt(addr, blockNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContractClassHashAt", reflect.TypeOf((*MockStateHistoryReader)(nil).ContractClassHashAt), addr, blockNumber)
}

// ContractDeployedAt mocks base method.
func (m *MockStateHistoryReader) ContractDeployedAt(addr *felt.Felt, blockNumber uint64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContractDeployedAt", addr, blockNumber)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ContractDeployedAt indicates an expected call of ContractDeployedAt.
func (mr *MockStateHistoryReaderMockRecorder) ContractDeployedAt(addr, blockNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContractDeployedAt", reflect.TypeOf((*MockStateHistoryReader)(nil).ContractDeployedAt), addr, blockNumber)
}

// ContractNonce mocks base method.
func (m *MockStateHistoryReader) ContractNonce(addr *felt.Felt) (felt.Felt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContractNonce", addr)
	ret0, _ := ret[0].(felt.Felt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ContractNonce indicates an expected call of ContractNonce.
func (mr *MockStateHistoryReaderMockRecorder) ContractNonce(addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContractNonce", reflect.TypeOf((*MockStateHistoryReader)(nil).ContractNonce), addr)
}

// ContractNonceAt mocks base method.
func (m *MockStateHistoryReader) ContractNonceAt(addr *felt.Felt, blockNumber uint64) (felt.Felt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContractNonceAt", addr, blockNumber)
	ret0, _ := ret[0].(felt.Felt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ContractNonceAt indicates an expected call of ContractNonceAt.
func (mr *MockStateHistoryReaderMockRecorder) ContractNonceAt(addr, blockNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContractNonceAt", reflect.TypeOf((*MockStateHistoryReader)(nil).ContractNonceAt), addr, blockNumber)
}

// ContractStorage mocks base method.
func (m *MockStateHistoryReader) ContractStorage(addr, key *felt.Felt) (felt.Felt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContractStorage", addr, key)
	ret0, _ := ret[0].(felt.Felt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ContractStorage indicates an expected call of ContractStorage.
func (mr *MockStateHistoryReaderMockRecorder) ContractStorage(addr, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContractStorage", reflect.TypeOf((*MockStateHistoryReader)(nil).ContractStorage), addr, key)
}

// ContractStorageAt mocks base method.
func (m *MockStateHistoryReader) ContractStorageAt(addr, key *felt.Felt, blockNumber uint64) (felt.Felt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContractStorageAt", addr, key, blockNumber)
	ret0, _ := ret[0].(felt.Felt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ContractStorageAt indicates an expected call of ContractStorageAt.
func (mr *MockStateHistoryReaderMockRecorder) ContractStorageAt(addr, key, blockNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContractStorageAt", reflect.TypeOf((*MockStateHistoryReader)(nil).ContractStorageAt), addr, key, blockNumber)
}

// ContractStorageTrie mocks base method.
func (m *MockStateHistoryReader) ContractStorageTrie(addr *felt.Felt) (commontrie.Trie, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContractStorageTrie", addr)
	ret0, _ := ret[0].(commontrie.Trie)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ContractStorageTrie indicates an expected call of ContractStorageTrie.
func (mr *MockStateHistoryReaderMockRecorder) ContractStorageTrie(addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContractStorageTrie", reflect.TypeOf((*MockStateHistoryReader)(nil).ContractStorageTrie), addr)
}

// ContractTrie mocks base method.
func (m *MockStateHistoryReader) ContractTrie() (commontrie.Trie, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContractTrie")
	ret0, _ := ret[0].(commontrie.Trie)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ContractTrie indicates an expected call of ContractTrie.
func (mr *MockStateHistoryReaderMockRecorder) ContractTrie() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContractTrie", reflect.TypeOf((*MockStateHistoryReader)(nil).ContractTrie))
}
