// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/NethermindEth/juno/rpc (interfaces: Gateway)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	json "encoding/json"
	reflect "reflect"

	core "github.com/NethermindEth/juno/core"
	gomock "github.com/golang/mock/gomock"
)

// MockGateway is a mock of Gateway interface.
type MockGateway struct {
	ctrl     *gomock.Controller
	recorder *MockGatewayMockRecorder
}

// MockGatewayMockRecorder is the mock recorder for MockGateway.
type MockGatewayMockRecorder struct {
	mock *MockGateway
}

// NewMockGateway creates a new mock instance.
func NewMockGateway(ctrl *gomock.Controller) *MockGateway {
	mock := &MockGateway{ctrl: ctrl}
	mock.recorder = &MockGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGateway) EXPECT() *MockGatewayMockRecorder {
	return m.recorder
}

// AddInvokeTransaction mocks base method.
func (m *MockGateway) AddInvokeTransaction(arg0 context.Context, arg1 *json.RawMessage) (*core.InvokeTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddInvokeTransaction", arg0, arg1)
	ret0, _ := ret[0].(*core.InvokeTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddInvokeTransaction indicates an expected call of AddInvokeTransaction.
func (mr *MockGatewayMockRecorder) AddInvokeTransaction(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddInvokeTransaction", reflect.TypeOf((*MockGateway)(nil).AddInvokeTransaction), arg0, arg1)
}
