// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/NethermindEth/juno/core (interfaces: State)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_state.go -package=mocks github.com/NethermindEth/juno/core State
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	core "github.com/NethermindEth/juno/core"
	felt "github.com/NethermindEth/juno/core/felt"
	gomock "go.uber.org/mock/gomock"
)

// MockState is a mock of State interface.
type MockState struct {
	ctrl     *gomock.Controller
	recorder *MockStateMockRecorder
	isgomock struct{}
}

// MockStateMockRecorder is the mock recorder for MockState.
type MockStateMockRecorder struct {
	mock *MockState
}

// NewMockState creates a new mock instance.
func NewMockState(ctrl *gomock.Controller) *MockState {
	mock := &MockState{ctrl: ctrl}
	mock.recorder = &MockStateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockState) EXPECT() *MockStateMockRecorder {
	return m.recorder
}

// Class mocks base method.
func (m *MockState) Class(classHash *felt.Felt) (*core.DeclaredClassDefinition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Class", classHash)
	ret0, _ := ret[0].(*core.DeclaredClassDefinition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Class indicates an expected call of Class.
func (mr *MockStateMockRecorder) Class(classHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Class", reflect.TypeOf((*MockState)(nil).Class), classHash)
}

// ClassTrie mocks base method.
func (m *MockState) ClassTrie() (core.Trie, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClassTrie")
	ret0, _ := ret[0].(core.Trie)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClassTrie indicates an expected call of ClassTrie.
func (mr *MockStateMockRecorder) ClassTrie() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClassTrie", reflect.TypeOf((*MockState)(nil).ClassTrie))
}

// Commitment mocks base method.
func (m *MockState) Commitment() (felt.Felt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commitment")
	ret0, _ := ret[0].(felt.Felt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Commitment indicates an expected call of Commitment.
func (mr *MockStateMockRecorder) Commitment() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commitment", reflect.TypeOf((*MockState)(nil).Commitment))
}

// CompiledClassHash mocks base method.
func (m *MockState) CompiledClassHash(classHash *felt.SierraClassHash) (felt.CasmClassHash, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompiledClassHash", classHash)
	ret0, _ := ret[0].(felt.CasmClassHash)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompiledClassHash indicates an expected call of CompiledClassHash.
func (mr *MockStateMockRecorder) CompiledClassHash(classHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompiledClassHash", reflect.TypeOf((*MockState)(nil).CompiledClassHash), classHash)
}

// CompiledClassHashAt mocks base method.
func (m *MockState) CompiledClassHashAt(classHash *felt.SierraClassHash, blockNumber uint64) (felt.CasmClassHash, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompiledClassHashAt", classHash, blockNumber)
	ret0, _ := ret[0].(felt.CasmClassHash)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompiledClassHashAt indicates an expected call of CompiledClassHashAt.
func (mr *MockStateMockRecorder) CompiledClassHashAt(classHash, blockNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompiledClassHashAt", reflect.TypeOf((*MockState)(nil).CompiledClassHashAt), classHash, blockNumber)
}

// CompiledClassHashV2 mocks base method.
func (m *MockState) CompiledClassHashV2(classHash *felt.SierraClassHash) (felt.CasmClassHash, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompiledClassHashV2", classHash)
	ret0, _ := ret[0].(felt.CasmClassHash)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompiledClassHashV2 indicates an expected call of CompiledClassHashV2.
func (mr *MockStateMockRecorder) CompiledClassHashV2(classHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompiledClassHashV2", reflect.TypeOf((*MockState)(nil).CompiledClassHashV2), classHash)
}

// ContractClassHash mocks base method.
func (m *MockState) ContractClassHash(addr *felt.Felt) (felt.Felt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContractClassHash", addr)
	ret0, _ := ret[0].(felt.Felt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ContractClassHash indicates an expected call of ContractClassHash.
func (mr *MockStateMockRecorder) ContractClassHash(addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContractClassHash", reflect.TypeOf((*MockState)(nil).ContractClassHash), addr)
}

// ContractClassHashAt mocks base method.
func (m *MockState) ContractClassHashAt(addr *felt.Felt, blockNumber uint64) (felt.Felt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContractClassHashAt", addr, blockNumber)
	ret0, _ := ret[0].(felt.Felt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ContractClassHashAt indicates an expected call of ContractClassHashAt.
func (mr *MockStateMockRecorder) ContractClassHashAt(addr, blockNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContractClassHashAt", reflect.TypeOf((*MockState)(nil).ContractClassHashAt), addr, blockNumber)
}

// ContractDeployedAt mocks base method.
func (m *MockState) ContractDeployedAt(addr *felt.Felt, blockNumber uint64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContractDeployedAt", addr, blockNumber)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ContractDeployedAt indicates an expected call of ContractDeployedAt.
func (mr *MockStateMockRecorder) ContractDeployedAt(addr, blockNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContractDeployedAt", reflect.TypeOf((*MockState)(nil).ContractDeployedAt), addr, blockNumber)
}

// ContractNonce mocks base method.
func (m *MockState) ContractNonce(addr *felt.Felt) (felt.Felt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContractNonce", addr)
	ret0, _ := ret[0].(felt.Felt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ContractNonce indicates an expected call of ContractNonce.
func (mr *MockStateMockRecorder) ContractNonce(addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContractNonce", reflect.TypeOf((*MockState)(nil).ContractNonce), addr)
}

// ContractNonceAt mocks base method.
func (m *MockState) ContractNonceAt(addr *felt.Felt, blockNumber uint64) (felt.Felt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContractNonceAt", addr, blockNumber)
	ret0, _ := ret[0].(felt.Felt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ContractNonceAt indicates an expected call of ContractNonceAt.
func (mr *MockStateMockRecorder) ContractNonceAt(addr, blockNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContractNonceAt", reflect.TypeOf((*MockState)(nil).ContractNonceAt), addr, blockNumber)
}

// ContractStorage mocks base method.
func (m *MockState) ContractStorage(addr, key *felt.Felt) (felt.Felt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContractStorage", addr, key)
	ret0, _ := ret[0].(felt.Felt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ContractStorage indicates an expected call of ContractStorage.
func (mr *MockStateMockRecorder) ContractStorage(addr, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContractStorage", reflect.TypeOf((*MockState)(nil).ContractStorage), addr, key)
}

// ContractStorageAt mocks base method.
func (m *MockState) ContractStorageAt(addr, key *felt.Felt, blockNumber uint64) (felt.Felt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContractStorageAt", addr, key, blockNumber)
	ret0, _ := ret[0].(felt.Felt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ContractStorageAt indicates an expected call of ContractStorageAt.
func (mr *MockStateMockRecorder) ContractStorageAt(addr, key, blockNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContractStorageAt", reflect.TypeOf((*MockState)(nil).ContractStorageAt), addr, key, blockNumber)
}

// ContractStorageTrie mocks base method.
func (m *MockState) ContractStorageTrie(addr *felt.Felt) (core.Trie, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContractStorageTrie", addr)
	ret0, _ := ret[0].(core.Trie)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ContractStorageTrie indicates an expected call of ContractStorageTrie.
func (mr *MockStateMockRecorder) ContractStorageTrie(addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContractStorageTrie", reflect.TypeOf((*MockState)(nil).ContractStorageTrie), addr)
}

// ContractTrie mocks base method.
func (m *MockState) ContractTrie() (core.Trie, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContractTrie")
	ret0, _ := ret[0].(core.Trie)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ContractTrie indicates an expected call of ContractTrie.
func (mr *MockStateMockRecorder) ContractTrie() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContractTrie", reflect.TypeOf((*MockState)(nil).ContractTrie))
}

// Revert mocks base method.
func (m *MockState) Revert(blockNum uint64, update *core.StateUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revert", blockNum, update)
	ret0, _ := ret[0].(error)
	return ret0
}

// Revert indicates an expected call of Revert.
func (mr *MockStateMockRecorder) Revert(blockNum, update any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revert", reflect.TypeOf((*MockState)(nil).Revert), blockNum, update)
}

// Update mocks base method.
func (m *MockState) Update(blockNum uint64, update *core.StateUpdate, declaredClasses map[felt.Felt]core.ClassDefinition, skipVerifyNewRoot bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", blockNum, update, declaredClasses, skipVerifyNewRoot)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockStateMockRecorder) Update(blockNum, update, declaredClasses, skipVerifyNewRoot any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockState)(nil).Update), blockNum, update, declaredClasses, skipVerifyNewRoot)
}
