// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/NethermindEth/juno/clients/feeder (interfaces: Reader)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/mock_feeder.go -mock_names Reader=MockFeederReader -package=mocks github.com/NethermindEth/juno/clients/feeder Reader
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	felt "github.com/NethermindEth/juno/core/felt"
	starknet "github.com/NethermindEth/juno/starknet"
	gomock "go.uber.org/mock/gomock"
)

// MockFeederReader is a mock of Reader interface.
type MockFeederReader struct {
	ctrl     *gomock.Controller
	recorder *MockFeederReaderMockRecorder
	isgomock struct{}
}

// MockFeederReaderMockRecorder is the mock recorder for MockFeederReader.
type MockFeederReaderMockRecorder struct {
	mock *MockFeederReader
}

// NewMockFeederReader creates a new mock instance.
func NewMockFeederReader(ctrl *gomock.Controller) *MockFeederReader {
	mock := &MockFeederReader{ctrl: ctrl}
	mock.recorder = &MockFeederReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeederReader) EXPECT() *MockFeederReaderMockRecorder {
	return m.recorder
}

// Block mocks base method.
func (m *MockFeederReader) Block(ctx context.Context, blockID string) (*starknet.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Block", ctx, blockID)
	ret0, _ := ret[0].(*starknet.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Block indicates an expected call of Block.
func (mr *MockFeederReaderMockRecorder) Block(ctx, blockID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Block", reflect.TypeOf((*MockFeederReader)(nil).Block), ctx, blockID)
}

// BlockHeader mocks base method.
func (m *MockFeederReader) BlockHeader(ctx context.Context, blockID string) (starknet.BlockHeader, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlockHeader", ctx, blockID)
	ret0, _ := ret[0].(starknet.BlockHeader)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BlockHeader indicates an expected call of BlockHeader.
func (mr *MockFeederReaderMockRecorder) BlockHeader(ctx, blockID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlockHeader", reflect.TypeOf((*MockFeederReader)(nil).BlockHeader), ctx, blockID)
}

// BlockTrace mocks base method.
func (m *MockFeederReader) BlockTrace(ctx context.Context, blockHash string) (*starknet.BlockTrace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlockTrace", ctx, blockHash)
	ret0, _ := ret[0].(*starknet.BlockTrace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BlockTrace indicates an expected call of BlockTrace.
func (mr *MockFeederReaderMockRecorder) BlockTrace(ctx, blockHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlockTrace", reflect.TypeOf((*MockFeederReader)(nil).BlockTrace), ctx, blockHash)
}

// CasmClassDefinition mocks base method.
func (m *MockFeederReader) CasmClassDefinition(ctx context.Context, classHash *felt.Felt) (*starknet.CasmClass, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CasmClassDefinition", ctx, classHash)
	ret0, _ := ret[0].(*starknet.CasmClass)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CasmClassDefinition indicates an expected call of CasmClassDefinition.
func (mr *MockFeederReaderMockRecorder) CasmClassDefinition(ctx, classHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CasmClassDefinition", reflect.TypeOf((*MockFeederReader)(nil).CasmClassDefinition), ctx, classHash)
}

// ClassDefinition mocks base method.
func (m *MockFeederReader) ClassDefinition(ctx context.Context, classHash *felt.Felt) (*starknet.ClassDefinition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClassDefinition", ctx, classHash)
	ret0, _ := ret[0].(*starknet.ClassDefinition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClassDefinition indicates an expected call of ClassDefinition.
func (mr *MockFeederReaderMockRecorder) ClassDefinition(ctx, classHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClassDefinition", reflect.TypeOf((*MockFeederReader)(nil).ClassDefinition), ctx, classHash)
}

// FeeTokenAddresses mocks base method.
func (m *MockFeederReader) FeeTokenAddresses(ctx context.Context) (starknet.FeeTokenAddresses, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FeeTokenAddresses", ctx)
	ret0, _ := ret[0].(starknet.FeeTokenAddresses)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FeeTokenAddresses indicates an expected call of FeeTokenAddresses.
func (mr *MockFeederReaderMockRecorder) FeeTokenAddresses(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FeeTokenAddresses", reflect.TypeOf((*MockFeederReader)(nil).FeeTokenAddresses), ctx)
}

// PreConfirmedBlock mocks base method.
func (m *MockFeederReader) PreConfirmedBlock(ctx context.Context, blockNumber string) (*starknet.PreConfirmedBlock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PreConfirmedBlock", ctx, blockNumber)
	ret0, _ := ret[0].(*starknet.PreConfirmedBlock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PreConfirmedBlock indicates an expected call of PreConfirmedBlock.
func (mr *MockFeederReaderMockRecorder) PreConfirmedBlock(ctx, blockNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PreConfirmedBlock", reflect.TypeOf((*MockFeederReader)(nil).PreConfirmedBlock), ctx, blockNumber)
}

// PublicKey mocks base method.
func (m *MockFeederReader) PublicKey(ctx context.Context) (*felt.Felt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublicKey", ctx)
	ret0, _ := ret[0].(*felt.Felt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PublicKey indicates an expected call of PublicKey.
func (mr *MockFeederReaderMockRecorder) PublicKey(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublicKey", reflect.TypeOf((*MockFeederReader)(nil).PublicKey), ctx)
}

// Signature mocks base method.
func (m *MockFeederReader) Signature(ctx context.Context, blockID string) (*starknet.Signature, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Signature", ctx, blockID)
	ret0, _ := ret[0].(*starknet.Signature)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Signature indicates an expected call of Signature.
func (mr *MockFeederReaderMockRecorder) Signature(ctx, blockID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signature", reflect.TypeOf((*MockFeederReader)(nil).Signature), ctx, blockID)
}

// StateUpdate mocks base method.
func (m *MockFeederReader) StateUpdate(ctx context.Context, blockID string) (*starknet.StateUpdate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StateUpdate", ctx, blockID)
	ret0, _ := ret[0].(*starknet.StateUpdate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StateUpdate indicates an expected call of StateUpdate.
func (mr *MockFeederReaderMockRecorder) StateUpdate(ctx, blockID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StateUpdate", reflect.TypeOf((*MockFeederReader)(nil).StateUpdate), ctx, blockID)
}

// StateUpdateWithBlock mocks base method.
func (m *MockFeederReader) StateUpdateWithBlock(ctx context.Context, blockID string) (*starknet.StateUpdateWithBlock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StateUpdateWithBlock", ctx, blockID)
	ret0, _ := ret[0].(*starknet.StateUpdateWithBlock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StateUpdateWithBlock indicates an expected call of StateUpdateWithBlock.
func (mr *MockFeederReaderMockRecorder) StateUpdateWithBlock(ctx, blockID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StateUpdateWithBlock", reflect.TypeOf((*MockFeederReader)(nil).StateUpdateWithBlock), ctx, blockID)
}

// StateUpdateWithBlockAndSignature mocks base method.
func (m *MockFeederReader) StateUpdateWithBlockAndSignature(ctx context.Context, blockID string) (*starknet.StateUpdateWithBlockAndSignature, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StateUpdateWithBlockAndSignature", ctx, blockID)
	ret0, _ := ret[0].(*starknet.StateUpdateWithBlockAndSignature)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StateUpdateWithBlockAndSignature indicates an expected call of StateUpdateWithBlockAndSignature.
func (mr *MockFeederReaderMockRecorder) StateUpdateWithBlockAndSignature(ctx, blockID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StateUpdateWithBlockAndSignature", reflect.TypeOf((*MockFeederReader)(nil).StateUpdateWithBlockAndSignature), ctx, blockID)
}

// Transaction mocks base method.
func (m *MockFeederReader) Transaction(ctx context.Context, transactionHash *felt.Felt) (*starknet.DeprecatedTransactionStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transaction", ctx, transactionHash)
	ret0, _ := ret[0].(*starknet.DeprecatedTransactionStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Transaction indicates an expected call of Transaction.
func (mr *MockFeederReaderMockRecorder) Transaction(ctx, transactionHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transaction", reflect.TypeOf((*MockFeederReader)(nil).Transaction), ctx, transactionHash)
}

// TransactionStatus mocks base method.
func (m *MockFeederReader) TransactionStatus(ctx context.Context, transactionHash *felt.Felt) (*starknet.TransactionStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransactionStatus", ctx, transactionHash)
	ret0, _ := ret[0].(*starknet.TransactionStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TransactionStatus indicates an expected call of TransactionStatus.
func (mr *MockFeederReaderMockRecorder) TransactionStatus(ctx, transactionHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransactionStatus", reflect.TypeOf((*MockFeederReader)(nil).TransactionStatus), ctx, transactionHash)
}
