// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        (unknown)
// source: p2p/proto/receipt.proto

package spec

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PriceUnit int32

const (
	PriceUnit_Wei PriceUnit = 0
	PriceUnit_Fri PriceUnit = 1
)

// Enum value maps for PriceUnit.
var (
	PriceUnit_name = map[int32]string{
		0: "Wei",
		1: "Fri",
	}
	PriceUnit_value = map[string]int32{
		"Wei": 0,
		"Fri": 1,
	}
)

func (x PriceUnit) Enum() *PriceUnit {
	p := new(PriceUnit)
	*p = x
	return p
}

func (x PriceUnit) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PriceUnit) Descriptor() protoreflect.EnumDescriptor {
	return file_p2p_proto_receipt_proto_enumTypes[0].Descriptor()
}

func (PriceUnit) Type() protoreflect.EnumType {
	return &file_p2p_proto_receipt_proto_enumTypes[0]
}

func (x PriceUnit) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PriceUnit.Descriptor instead.
func (PriceUnit) EnumDescriptor() ([]byte, []int) {
	return file_p2p_proto_receipt_proto_rawDescGZIP(), []int{0}
}

type MessageToL1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromAddress *Felt252         `protobuf:"bytes,2,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"`
	Payload     []*Felt252       `protobuf:"bytes,3,rep,name=payload,proto3" json:"payload,omitempty"`
	ToAddress   *EthereumAddress `protobuf:"bytes,4,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`
}

func (x *MessageToL1) Reset() {
	*x = MessageToL1{}
	mi := &file_p2p_proto_receipt_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageToL1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageToL1) ProtoMessage() {}

func (x *MessageToL1) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_receipt_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageToL1.ProtoReflect.Descriptor instead.
func (*MessageToL1) Descriptor() ([]byte, []int) {
	return file_p2p_proto_receipt_proto_rawDescGZIP(), []int{0}
}

func (x *MessageToL1) GetFromAddress() *Felt252 {
	if x != nil {
		return x.FromAddress
	}
	return nil
}

func (x *MessageToL1) GetPayload() []*Felt252 {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *MessageToL1) GetToAddress() *EthereumAddress {
	if x != nil {
		return x.ToAddress
	}
	return nil
}

type EthereumAddress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Elements []byte `protobuf:"bytes,1,opt,name=elements,proto3" json:"elements,omitempty"`
}

func (x *EthereumAddress) Reset() {
	*x = EthereumAddress{}
	mi := &file_p2p_proto_receipt_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EthereumAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EthereumAddress) ProtoMessage() {}

func (x *EthereumAddress) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_receipt_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EthereumAddress.ProtoReflect.Descriptor instead.
func (*EthereumAddress) Descriptor() ([]byte, []int) {
	return file_p2p_proto_receipt_proto_rawDescGZIP(), []int{1}
}

func (x *EthereumAddress) GetElements() []byte {
	if x != nil {
		return x.Elements
	}
	return nil
}

type Receipt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Type:
	//
	//	*Receipt_Invoke_
	//	*Receipt_L1Handler_
	//	*Receipt_Declare_
	//	*Receipt_DeprecatedDeploy
	//	*Receipt_DeployAccount_
	Type isReceipt_Type `protobuf_oneof:"type"`
}

func (x *Receipt) Reset() {
	*x = Receipt{}
	mi := &file_p2p_proto_receipt_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Receipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Receipt) ProtoMessage() {}

func (x *Receipt) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_receipt_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Receipt.ProtoReflect.Descriptor instead.
func (*Receipt) Descriptor() ([]byte, []int) {
	return file_p2p_proto_receipt_proto_rawDescGZIP(), []int{2}
}

func (m *Receipt) GetType() isReceipt_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *Receipt) GetInvoke() *Receipt_Invoke {
	if x, ok := x.GetType().(*Receipt_Invoke_); ok {
		return x.Invoke
	}
	return nil
}

func (x *Receipt) GetL1Handler() *Receipt_L1Handler {
	if x, ok := x.GetType().(*Receipt_L1Handler_); ok {
		return x.L1Handler
	}
	return nil
}

func (x *Receipt) GetDeclare() *Receipt_Declare {
	if x, ok := x.GetType().(*Receipt_Declare_); ok {
		return x.Declare
	}
	return nil
}

func (x *Receipt) GetDeprecatedDeploy() *Receipt_Deploy {
	if x, ok := x.GetType().(*Receipt_DeprecatedDeploy); ok {
		return x.DeprecatedDeploy
	}
	return nil
}

func (x *Receipt) GetDeployAccount() *Receipt_DeployAccount {
	if x, ok := x.GetType().(*Receipt_DeployAccount_); ok {
		return x.DeployAccount
	}
	return nil
}

type isReceipt_Type interface {
	isReceipt_Type()
}

type Receipt_Invoke_ struct {
	Invoke *Receipt_Invoke `protobuf:"bytes,1,opt,name=invoke,proto3,oneof"`
}

type Receipt_L1Handler_ struct {
	L1Handler *Receipt_L1Handler `protobuf:"bytes,2,opt,name=l1_handler,json=l1Handler,proto3,oneof"`
}

type Receipt_Declare_ struct {
	Declare *Receipt_Declare `protobuf:"bytes,3,opt,name=declare,proto3,oneof"`
}

type Receipt_DeprecatedDeploy struct {
	DeprecatedDeploy *Receipt_Deploy `protobuf:"bytes,4,opt,name=deprecated_deploy,json=deprecatedDeploy,proto3,oneof"`
}

type Receipt_DeployAccount_ struct {
	DeployAccount *Receipt_DeployAccount `protobuf:"bytes,5,opt,name=deploy_account,json=deployAccount,proto3,oneof"`
}

func (*Receipt_Invoke_) isReceipt_Type() {}

func (*Receipt_L1Handler_) isReceipt_Type() {}

func (*Receipt_Declare_) isReceipt_Type() {}

func (*Receipt_DeprecatedDeploy) isReceipt_Type() {}

func (*Receipt_DeployAccount_) isReceipt_Type() {}

type Receipt_ExecutionResources struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Builtins    *Receipt_ExecutionResources_BuiltinCounter `protobuf:"bytes,1,opt,name=builtins,proto3" json:"builtins,omitempty"`
	Steps       uint32                                     `protobuf:"varint,2,opt,name=steps,proto3" json:"steps,omitempty"`
	MemoryHoles uint32                                     `protobuf:"varint,3,opt,name=memory_holes,json=memoryHoles,proto3" json:"memory_holes,omitempty"`
	L1Gas       *Felt252                                   `protobuf:"bytes,4,opt,name=l1_gas,json=l1Gas,proto3" json:"l1_gas,omitempty"`
	L1DataGas   *Felt252                                   `protobuf:"bytes,5,opt,name=l1_data_gas,json=l1DataGas,proto3" json:"l1_data_gas,omitempty"`
	TotalL1Gas  *Felt252                                   `protobuf:"bytes,6,opt,name=total_l1_gas,json=totalL1Gas,proto3" json:"total_l1_gas,omitempty"`
}

func (x *Receipt_ExecutionResources) Reset() {
	*x = Receipt_ExecutionResources{}
	mi := &file_p2p_proto_receipt_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Receipt_ExecutionResources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Receipt_ExecutionResources) ProtoMessage() {}

func (x *Receipt_ExecutionResources) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_receipt_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Receipt_ExecutionResources.ProtoReflect.Descriptor instead.
func (*Receipt_ExecutionResources) Descriptor() ([]byte, []int) {
	return file_p2p_proto_receipt_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Receipt_ExecutionResources) GetBuiltins() *Receipt_ExecutionResources_BuiltinCounter {
	if x != nil {
		return x.Builtins
	}
	return nil
}

func (x *Receipt_ExecutionResources) GetSteps() uint32 {
	if x != nil {
		return x.Steps
	}
	return 0
}

func (x *Receipt_ExecutionResources) GetMemoryHoles() uint32 {
	if x != nil {
		return x.MemoryHoles
	}
	return 0
}

func (x *Receipt_ExecutionResources) GetL1Gas() *Felt252 {
	if x != nil {
		return x.L1Gas
	}
	return nil
}

func (x *Receipt_ExecutionResources) GetL1DataGas() *Felt252 {
	if x != nil {
		return x.L1DataGas
	}
	return nil
}

func (x *Receipt_ExecutionResources) GetTotalL1Gas() *Felt252 {
	if x != nil {
		return x.TotalL1Gas
	}
	return nil
}

type Receipt_Common struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActualFee          *Felt252                    `protobuf:"bytes,2,opt,name=actual_fee,json=actualFee,proto3" json:"actual_fee,omitempty"`
	PriceUnit          PriceUnit                   `protobuf:"varint,3,opt,name=price_unit,json=priceUnit,proto3,enum=PriceUnit" json:"price_unit,omitempty"`
	MessagesSent       []*MessageToL1              `protobuf:"bytes,4,rep,name=messages_sent,json=messagesSent,proto3" json:"messages_sent,omitempty"`
	ExecutionResources *Receipt_ExecutionResources `protobuf:"bytes,5,opt,name=execution_resources,json=executionResources,proto3" json:"execution_resources,omitempty"`
	RevertReason       *string                     `protobuf:"bytes,6,opt,name=revert_reason,json=revertReason,proto3,oneof" json:"revert_reason,omitempty"`
}

func (x *Receipt_Common) Reset() {
	*x = Receipt_Common{}
	mi := &file_p2p_proto_receipt_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Receipt_Common) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Receipt_Common) ProtoMessage() {}

func (x *Receipt_Common) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_receipt_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Receipt_Common.ProtoReflect.Descriptor instead.
func (*Receipt_Common) Descriptor() ([]byte, []int) {
	return file_p2p_proto_receipt_proto_rawDescGZIP(), []int{2, 1}
}

func (x *Receipt_Common) GetActualFee() *Felt252 {
	if x != nil {
		return x.ActualFee
	}
	return nil
}

func (x *Receipt_Common) GetPriceUnit() PriceUnit {
	if x != nil {
		return x.PriceUnit
	}
	return PriceUnit_Wei
}

func (x *Receipt_Common) GetMessagesSent() []*MessageToL1 {
	if x != nil {
		return x.MessagesSent
	}
	return nil
}

func (x *Receipt_Common) GetExecutionResources() *Receipt_ExecutionResources {
	if x != nil {
		return x.ExecutionResources
	}
	return nil
}

func (x *Receipt_Common) GetRevertReason() string {
	if x != nil && x.RevertReason != nil {
		return *x.RevertReason
	}
	return ""
}

type Receipt_Invoke struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Common *Receipt_Common `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
}

func (x *Receipt_Invoke) Reset() {
	*x = Receipt_Invoke{}
	mi := &file_p2p_proto_receipt_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Receipt_Invoke) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Receipt_Invoke) ProtoMessage() {}

func (x *Receipt_Invoke) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_receipt_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Receipt_Invoke.ProtoReflect.Descriptor instead.
func (*Receipt_Invoke) Descriptor() ([]byte, []int) {
	return file_p2p_proto_receipt_proto_rawDescGZIP(), []int{2, 2}
}

func (x *Receipt_Invoke) GetCommon() *Receipt_Common {
	if x != nil {
		return x.Common
	}
	return nil
}

type Receipt_L1Handler struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Common  *Receipt_Common `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	MsgHash *Hash256        `protobuf:"bytes,2,opt,name=msg_hash,json=msgHash,proto3" json:"msg_hash,omitempty"`
}

func (x *Receipt_L1Handler) Reset() {
	*x = Receipt_L1Handler{}
	mi := &file_p2p_proto_receipt_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Receipt_L1Handler) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Receipt_L1Handler) ProtoMessage() {}

func (x *Receipt_L1Handler) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_receipt_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Receipt_L1Handler.ProtoReflect.Descriptor instead.
func (*Receipt_L1Handler) Descriptor() ([]byte, []int) {
	return file_p2p_proto_receipt_proto_rawDescGZIP(), []int{2, 3}
}

func (x *Receipt_L1Handler) GetCommon() *Receipt_Common {
	if x != nil {
		return x.Common
	}
	return nil
}

func (x *Receipt_L1Handler) GetMsgHash() *Hash256 {
	if x != nil {
		return x.MsgHash
	}
	return nil
}

type Receipt_Declare struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Common *Receipt_Common `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
}

func (x *Receipt_Declare) Reset() {
	*x = Receipt_Declare{}
	mi := &file_p2p_proto_receipt_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Receipt_Declare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Receipt_Declare) ProtoMessage() {}

func (x *Receipt_Declare) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_receipt_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Receipt_Declare.ProtoReflect.Descriptor instead.
func (*Receipt_Declare) Descriptor() ([]byte, []int) {
	return file_p2p_proto_receipt_proto_rawDescGZIP(), []int{2, 4}
}

func (x *Receipt_Declare) GetCommon() *Receipt_Common {
	if x != nil {
		return x.Common
	}
	return nil
}

type Receipt_Deploy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Common          *Receipt_Common `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	ContractAddress *Felt252        `protobuf:"bytes,2,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
}

func (x *Receipt_Deploy) Reset() {
	*x = Receipt_Deploy{}
	mi := &file_p2p_proto_receipt_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Receipt_Deploy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Receipt_Deploy) ProtoMessage() {}

func (x *Receipt_Deploy) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_receipt_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Receipt_Deploy.ProtoReflect.Descriptor instead.
func (*Receipt_Deploy) Descriptor() ([]byte, []int) {
	return file_p2p_proto_receipt_proto_rawDescGZIP(), []int{2, 5}
}

func (x *Receipt_Deploy) GetCommon() *Receipt_Common {
	if x != nil {
		return x.Common
	}
	return nil
}

func (x *Receipt_Deploy) GetContractAddress() *Felt252 {
	if x != nil {
		return x.ContractAddress
	}
	return nil
}

type Receipt_DeployAccount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Common          *Receipt_Common `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	ContractAddress *Felt252        `protobuf:"bytes,2,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
}

func (x *Receipt_DeployAccount) Reset() {
	*x = Receipt_DeployAccount{}
	mi := &file_p2p_proto_receipt_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Receipt_DeployAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Receipt_DeployAccount) ProtoMessage() {}

func (x *Receipt_DeployAccount) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_receipt_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Receipt_DeployAccount.ProtoReflect.Descriptor instead.
func (*Receipt_DeployAccount) Descriptor() ([]byte, []int) {
	return file_p2p_proto_receipt_proto_rawDescGZIP(), []int{2, 6}
}

func (x *Receipt_DeployAccount) GetCommon() *Receipt_Common {
	if x != nil {
		return x.Common
	}
	return nil
}

func (x *Receipt_DeployAccount) GetContractAddress() *Felt252 {
	if x != nil {
		return x.ContractAddress
	}
	return nil
}

type Receipt_ExecutionResources_BuiltinCounter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bitwise      uint32 `protobuf:"varint,1,opt,name=bitwise,proto3" json:"bitwise,omitempty"`
	Ecdsa        uint32 `protobuf:"varint,2,opt,name=ecdsa,proto3" json:"ecdsa,omitempty"`
	EcOp         uint32 `protobuf:"varint,3,opt,name=ec_op,json=ecOp,proto3" json:"ec_op,omitempty"`
	Pedersen     uint32 `protobuf:"varint,4,opt,name=pedersen,proto3" json:"pedersen,omitempty"`
	RangeCheck   uint32 `protobuf:"varint,5,opt,name=range_check,json=rangeCheck,proto3" json:"range_check,omitempty"`
	Poseidon     uint32 `protobuf:"varint,6,opt,name=poseidon,proto3" json:"poseidon,omitempty"`
	Keccak       uint32 `protobuf:"varint,7,opt,name=keccak,proto3" json:"keccak,omitempty"`
	Output       uint32 `protobuf:"varint,8,opt,name=output,proto3" json:"output,omitempty"`
	AddMod       uint32 `protobuf:"varint,9,opt,name=add_mod,json=addMod,proto3" json:"add_mod,omitempty"`
	MulMod       uint32 `protobuf:"varint,10,opt,name=mul_mod,json=mulMod,proto3" json:"mul_mod,omitempty"`
	RangeCheck96 uint32 `protobuf:"varint,11,opt,name=range_check96,json=rangeCheck96,proto3" json:"range_check96,omitempty"`
}

func (x *Receipt_ExecutionResources_BuiltinCounter) Reset() {
	*x = Receipt_ExecutionResources_BuiltinCounter{}
	mi := &file_p2p_proto_receipt_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Receipt_ExecutionResources_BuiltinCounter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Receipt_ExecutionResources_BuiltinCounter) ProtoMessage() {}

func (x *Receipt_ExecutionResources_BuiltinCounter) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_receipt_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Receipt_ExecutionResources_BuiltinCounter.ProtoReflect.Descriptor instead.
func (*Receipt_ExecutionResources_BuiltinCounter) Descriptor() ([]byte, []int) {
	return file_p2p_proto_receipt_proto_rawDescGZIP(), []int{2, 0, 0}
}

func (x *Receipt_ExecutionResources_BuiltinCounter) GetBitwise() uint32 {
	if x != nil {
		return x.Bitwise
	}
	return 0
}

func (x *Receipt_ExecutionResources_BuiltinCounter) GetEcdsa() uint32 {
	if x != nil {
		return x.Ecdsa
	}
	return 0
}

func (x *Receipt_ExecutionResources_BuiltinCounter) GetEcOp() uint32 {
	if x != nil {
		return x.EcOp
	}
	return 0
}

func (x *Receipt_ExecutionResources_BuiltinCounter) GetPedersen() uint32 {
	if x != nil {
		return x.Pedersen
	}
	return 0
}

func (x *Receipt_ExecutionResources_BuiltinCounter) GetRangeCheck() uint32 {
	if x != nil {
		return x.RangeCheck
	}
	return 0
}

func (x *Receipt_ExecutionResources_BuiltinCounter) GetPoseidon() uint32 {
	if x != nil {
		return x.Poseidon
	}
	return 0
}

func (x *Receipt_ExecutionResources_BuiltinCounter) GetKeccak() uint32 {
	if x != nil {
		return x.Keccak
	}
	return 0
}

func (x *Receipt_ExecutionResources_BuiltinCounter) GetOutput() uint32 {
	if x != nil {
		return x.Output
	}
	return 0
}

func (x *Receipt_ExecutionResources_BuiltinCounter) GetAddMod() uint32 {
	if x != nil {
		return x.AddMod
	}
	return 0
}

func (x *Receipt_ExecutionResources_BuiltinCounter) GetMulMod() uint32 {
	if x != nil {
		return x.MulMod
	}
	return 0
}

func (x *Receipt_ExecutionResources_BuiltinCounter) GetRangeCheck96() uint32 {
	if x != nil {
		return x.RangeCheck96
	}
	return 0
}

var File_p2p_proto_receipt_proto protoreflect.FileDescriptor

var file_p2p_proto_receipt_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x32, 0x70, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x65, 0x63, 0x65,
	0x69, 0x70, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x16, 0x70, 0x32, 0x70, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x8f, 0x01, 0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x6f, 0x4c,
	0x31, 0x12, 0x2b, 0x0a, 0x0c, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x46, 0x65, 0x6c, 0x74, 0x32, 0x35,
	0x32, 0x52, 0x0b, 0x66, 0x72, 0x6f, 0x6d, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x22,
	0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x08, 0x2e, 0x46, 0x65, 0x6c, 0x74, 0x32, 0x35, 0x32, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x12, 0x2f, 0x0a, 0x0a, 0x74, 0x6f, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x45, 0x74, 0x68, 0x65, 0x72, 0x65, 0x75,
	0x6d, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x09, 0x74, 0x6f, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x22, 0x2d, 0x0a, 0x0f, 0x45, 0x74, 0x68, 0x65, 0x72, 0x65, 0x75, 0x6d, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x73, 0x22, 0x9c, 0x0c, 0x0a, 0x07, 0x52, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x12, 0x29,
	0x0a, 0x06, 0x69, 0x6e, 0x76, 0x6f, 0x6b, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x52, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x2e, 0x49, 0x6e, 0x76, 0x6f, 0x6b, 0x65, 0x48,
	0x00, 0x52, 0x06, 0x69, 0x6e, 0x76, 0x6f, 0x6b, 0x65, 0x12, 0x33, 0x0a, 0x0a, 0x6c, 0x31, 0x5f,
	0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x52, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x2e, 0x4c, 0x31, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65,
	0x72, 0x48, 0x00, 0x52, 0x09, 0x6c, 0x31, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x12, 0x2c,
	0x0a, 0x07, 0x64, 0x65, 0x63, 0x6c, 0x61, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x52, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x2e, 0x44, 0x65, 0x63, 0x6c, 0x61, 0x72,
	0x65, 0x48, 0x00, 0x52, 0x07, 0x64, 0x65, 0x63, 0x6c, 0x61, 0x72, 0x65, 0x12, 0x3e, 0x0a, 0x11,
	0x64, 0x65, 0x70, 0x72, 0x65, 0x63, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x64, 0x65, 0x70, 0x6c, 0x6f,
	0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x52, 0x65, 0x63, 0x65, 0x69, 0x70,
	0x74, 0x2e, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x48, 0x00, 0x52, 0x10, 0x64, 0x65, 0x70, 0x72,
	0x65, 0x63, 0x61, 0x74, 0x65, 0x64, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x12, 0x3f, 0x0a, 0x0e,
	0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x52, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x2e, 0x44,
	0x65, 0x70, 0x6c, 0x6f, 0x79, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x0d,
	0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x1a, 0xc4, 0x04,
	0x0a, 0x12, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x73, 0x12, 0x46, 0x0a, 0x08, 0x62, 0x75, 0x69, 0x6c, 0x74, 0x69, 0x6e, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x52, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74,
	0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x73, 0x2e, 0x42, 0x75, 0x69, 0x6c, 0x74, 0x69, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x65, 0x72, 0x52, 0x08, 0x62, 0x75, 0x69, 0x6c, 0x74, 0x69, 0x6e, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x73, 0x74, 0x65, 0x70, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73, 0x74, 0x65,
	0x70, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x5f, 0x68, 0x6f, 0x6c,
	0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79,
	0x48, 0x6f, 0x6c, 0x65, 0x73, 0x12, 0x1f, 0x0a, 0x06, 0x6c, 0x31, 0x5f, 0x67, 0x61, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x46, 0x65, 0x6c, 0x74, 0x32, 0x35, 0x32, 0x52,
	0x05, 0x6c, 0x31, 0x47, 0x61, 0x73, 0x12, 0x28, 0x0a, 0x0b, 0x6c, 0x31, 0x5f, 0x64, 0x61, 0x74,
	0x61, 0x5f, 0x67, 0x61, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x46, 0x65,
	0x6c, 0x74, 0x32, 0x35, 0x32, 0x52, 0x09, 0x6c, 0x31, 0x44, 0x61, 0x74, 0x61, 0x47, 0x61, 0x73,
	0x12, 0x2a, 0x0a, 0x0c, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x6c, 0x31, 0x5f, 0x67, 0x61, 0x73,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x46, 0x65, 0x6c, 0x74, 0x32, 0x35, 0x32,
	0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x4c, 0x31, 0x47, 0x61, 0x73, 0x1a, 0xb5, 0x02, 0x0a,
	0x0e, 0x42, 0x75, 0x69, 0x6c, 0x74, 0x69, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x12,
	0x18, 0x0a, 0x07, 0x62, 0x69, 0x74, 0x77, 0x69, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x07, 0x62, 0x69, 0x74, 0x77, 0x69, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x63, 0x64,
	0x73, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x65, 0x63, 0x64, 0x73, 0x61, 0x12,
	0x13, 0x0a, 0x05, 0x65, 0x63, 0x5f, 0x6f, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04,
	0x65, 0x63, 0x4f, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x65, 0x64, 0x65, 0x72, 0x73, 0x65, 0x6e,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x70, 0x65, 0x64, 0x65, 0x72, 0x73, 0x65, 0x6e,
	0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x65, 0x69, 0x64, 0x6f, 0x6e, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x65, 0x69, 0x64, 0x6f, 0x6e, 0x12, 0x16, 0x0a,
	0x06, 0x6b, 0x65, 0x63, 0x63, 0x61, 0x6b, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x6b,
	0x65, 0x63, 0x63, 0x61, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x17, 0x0a,
	0x07, 0x61, 0x64, 0x64, 0x5f, 0x6d, 0x6f, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06,
	0x61, 0x64, 0x64, 0x4d, 0x6f, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x6d, 0x75, 0x6c, 0x5f, 0x6d, 0x6f,
	0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x6d, 0x75, 0x6c, 0x4d, 0x6f, 0x64, 0x12,
	0x23, 0x0a, 0x0d, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x39, 0x36,
	0x18, 0x0b, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x39, 0x36, 0x1a, 0x99, 0x02, 0x0a, 0x06, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x12,
	0x27, 0x0a, 0x0a, 0x61, 0x63, 0x74, 0x75, 0x61, 0x6c, 0x5f, 0x66, 0x65, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x46, 0x65, 0x6c, 0x74, 0x32, 0x35, 0x32, 0x52, 0x09, 0x61,
	0x63, 0x74, 0x75, 0x61, 0x6c, 0x46, 0x65, 0x65, 0x12, 0x29, 0x0a, 0x0a, 0x70, 0x72, 0x69, 0x63,
	0x65, 0x5f, 0x75, 0x6e, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0a, 0x2e, 0x50,
	0x72, 0x69, 0x63, 0x65, 0x55, 0x6e, 0x69, 0x74, 0x52, 0x09, 0x70, 0x72, 0x69, 0x63, 0x65, 0x55,
	0x6e, 0x69, 0x74, 0x12, 0x31, 0x0a, 0x0d, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x5f,
	0x73, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x54, 0x6f, 0x4c, 0x31, 0x52, 0x0c, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x53, 0x65, 0x6e, 0x74, 0x12, 0x4c, 0x0a, 0x13, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x52, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x2e, 0x45, 0x78,
	0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73,
	0x52, 0x12, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x73, 0x12, 0x28, 0x0a, 0x0d, 0x72, 0x65, 0x76, 0x65, 0x72, 0x74, 0x5f, 0x72,
	0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0c, 0x72,
	0x65, 0x76, 0x65, 0x72, 0x74, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x42, 0x10,
	0x0a, 0x0e, 0x5f, 0x72, 0x65, 0x76, 0x65, 0x72, 0x74, 0x5f, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e,
	0x1a, 0x31, 0x0a, 0x06, 0x49, 0x6e, 0x76, 0x6f, 0x6b, 0x65, 0x12, 0x27, 0x0a, 0x06, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x52, 0x65, 0x63,
	0x65, 0x69, 0x70, 0x74, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x06, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x1a, 0x59, 0x0a, 0x09, 0x4c, 0x31, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72,
	0x12, 0x27, 0x0a, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x52, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x52, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x12, 0x23, 0x0a, 0x08, 0x6d, 0x73, 0x67,
	0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x48, 0x61,
	0x73, 0x68, 0x32, 0x35, 0x36, 0x52, 0x07, 0x6d, 0x73, 0x67, 0x48, 0x61, 0x73, 0x68, 0x1a, 0x32,
	0x0a, 0x07, 0x44, 0x65, 0x63, 0x6c, 0x61, 0x72, 0x65, 0x12, 0x27, 0x0a, 0x06, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x52, 0x65, 0x63, 0x65,
	0x69, 0x70, 0x74, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x06, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x1a, 0x66, 0x0a, 0x06, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x12, 0x27, 0x0a, 0x06,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x52,
	0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x06, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x12, 0x33, 0x0a, 0x10, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x08, 0x2e, 0x46, 0x65, 0x6c, 0x74, 0x32, 0x35, 0x32, 0x52, 0x0f, 0x63, 0x6f, 0x6e, 0x74, 0x72,
	0x61, 0x63, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x1a, 0x6d, 0x0a, 0x0d, 0x44, 0x65,
	0x70, 0x6c, 0x6f, 0x79, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x27, 0x0a, 0x06, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x52, 0x65,
	0x63, 0x65, 0x69, 0x70, 0x74, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x06, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x12, 0x33, 0x0a, 0x10, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74,
	0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08,
	0x2e, 0x46, 0x65, 0x6c, 0x74, 0x32, 0x35, 0x32, 0x52, 0x0f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61,
	0x63, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x42, 0x06, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x2a, 0x1d, 0x0a, 0x09, 0x50, 0x72, 0x69, 0x63, 0x65, 0x55, 0x6e, 0x69, 0x74, 0x12, 0x07,
	0x0a, 0x03, 0x57, 0x65, 0x69, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x46, 0x72, 0x69, 0x10, 0x01,
	0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4e,
	0x65, 0x74, 0x68, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x64, 0x45, 0x74, 0x68, 0x2f, 0x6a, 0x75, 0x6e,
	0x6f, 0x2f, 0x70, 0x32, 0x70, 0x2f, 0x73, 0x74, 0x61, 0x72, 0x6b, 0x6e, 0x65, 0x74, 0x2f, 0x73,
	0x70, 0x65, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_p2p_proto_receipt_proto_rawDescOnce sync.Once
	file_p2p_proto_receipt_proto_rawDescData = file_p2p_proto_receipt_proto_rawDesc
)

func file_p2p_proto_receipt_proto_rawDescGZIP() []byte {
	file_p2p_proto_receipt_proto_rawDescOnce.Do(func() {
		file_p2p_proto_receipt_proto_rawDescData = protoimpl.X.CompressGZIP(file_p2p_proto_receipt_proto_rawDescData)
	})
	return file_p2p_proto_receipt_proto_rawDescData
}

var file_p2p_proto_receipt_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_p2p_proto_receipt_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_p2p_proto_receipt_proto_goTypes = []any{
	(PriceUnit)(0),                                    // 0: PriceUnit
	(*MessageToL1)(nil),                               // 1: MessageToL1
	(*EthereumAddress)(nil),                           // 2: EthereumAddress
	(*Receipt)(nil),                                   // 3: Receipt
	(*Receipt_ExecutionResources)(nil),                // 4: Receipt.ExecutionResources
	(*Receipt_Common)(nil),                            // 5: Receipt.Common
	(*Receipt_Invoke)(nil),                            // 6: Receipt.Invoke
	(*Receipt_L1Handler)(nil),                         // 7: Receipt.L1Handler
	(*Receipt_Declare)(nil),                           // 8: Receipt.Declare
	(*Receipt_Deploy)(nil),                            // 9: Receipt.Deploy
	(*Receipt_DeployAccount)(nil),                     // 10: Receipt.DeployAccount
	(*Receipt_ExecutionResources_BuiltinCounter)(nil), // 11: Receipt.ExecutionResources.BuiltinCounter
	(*Felt252)(nil),                                   // 12: Felt252
	(*Hash256)(nil),                                   // 13: Hash256
}
var file_p2p_proto_receipt_proto_depIdxs = []int32{
	12, // 0: MessageToL1.from_address:type_name -> Felt252
	12, // 1: MessageToL1.payload:type_name -> Felt252
	2,  // 2: MessageToL1.to_address:type_name -> EthereumAddress
	6,  // 3: Receipt.invoke:type_name -> Receipt.Invoke
	7,  // 4: Receipt.l1_handler:type_name -> Receipt.L1Handler
	8,  // 5: Receipt.declare:type_name -> Receipt.Declare
	9,  // 6: Receipt.deprecated_deploy:type_name -> Receipt.Deploy
	10, // 7: Receipt.deploy_account:type_name -> Receipt.DeployAccount
	11, // 8: Receipt.ExecutionResources.builtins:type_name -> Receipt.ExecutionResources.BuiltinCounter
	12, // 9: Receipt.ExecutionResources.l1_gas:type_name -> Felt252
	12, // 10: Receipt.ExecutionResources.l1_data_gas:type_name -> Felt252
	12, // 11: Receipt.ExecutionResources.total_l1_gas:type_name -> Felt252
	12, // 12: Receipt.Common.actual_fee:type_name -> Felt252
	0,  // 13: Receipt.Common.price_unit:type_name -> PriceUnit
	1,  // 14: Receipt.Common.messages_sent:type_name -> MessageToL1
	4,  // 15: Receipt.Common.execution_resources:type_name -> Receipt.ExecutionResources
	5,  // 16: Receipt.Invoke.common:type_name -> Receipt.Common
	5,  // 17: Receipt.L1Handler.common:type_name -> Receipt.Common
	13, // 18: Receipt.L1Handler.msg_hash:type_name -> Hash256
	5,  // 19: Receipt.Declare.common:type_name -> Receipt.Common
	5,  // 20: Receipt.Deploy.common:type_name -> Receipt.Common
	12, // 21: Receipt.Deploy.contract_address:type_name -> Felt252
	5,  // 22: Receipt.DeployAccount.common:type_name -> Receipt.Common
	12, // 23: Receipt.DeployAccount.contract_address:type_name -> Felt252
	24, // [24:24] is the sub-list for method output_type
	24, // [24:24] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_p2p_proto_receipt_proto_init() }
func file_p2p_proto_receipt_proto_init() {
	if File_p2p_proto_receipt_proto != nil {
		return
	}
	file_p2p_proto_common_proto_init()
	file_p2p_proto_receipt_proto_msgTypes[2].OneofWrappers = []any{
		(*Receipt_Invoke_)(nil),
		(*Receipt_L1Handler_)(nil),
		(*Receipt_Declare_)(nil),
		(*Receipt_DeprecatedDeploy)(nil),
		(*Receipt_DeployAccount_)(nil),
	}
	file_p2p_proto_receipt_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_p2p_proto_receipt_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_p2p_proto_receipt_proto_goTypes,
		DependencyIndexes: file_p2p_proto_receipt_proto_depIdxs,
		EnumInfos:         file_p2p_proto_receipt_proto_enumTypes,
		MessageInfos:      file_p2p_proto_receipt_proto_msgTypes,
	}.Build()
	File_p2p_proto_receipt_proto = out.File
	file_p2p_proto_receipt_proto_rawDesc = nil
	file_p2p_proto_receipt_proto_goTypes = nil
	file_p2p_proto_receipt_proto_depIdxs = nil
}
