// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.4
// source: p2p/proto/snapshot.proto

package spec

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PatriciaNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Node:
	//
	//	*PatriciaNode_Edge_
	//	*PatriciaNode_Binary_
	Node isPatriciaNode_Node `protobuf_oneof:"node"`
}

func (x *PatriciaNode) Reset() {
	*x = PatriciaNode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_p2p_proto_snapshot_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PatriciaNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatriciaNode) ProtoMessage() {}

func (x *PatriciaNode) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_snapshot_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatriciaNode.ProtoReflect.Descriptor instead.
func (*PatriciaNode) Descriptor() ([]byte, []int) {
	return file_p2p_proto_snapshot_proto_rawDescGZIP(), []int{0}
}

func (m *PatriciaNode) GetNode() isPatriciaNode_Node {
	if m != nil {
		return m.Node
	}
	return nil
}

func (x *PatriciaNode) GetEdge() *PatriciaNode_Edge {
	if x, ok := x.GetNode().(*PatriciaNode_Edge_); ok {
		return x.Edge
	}
	return nil
}

func (x *PatriciaNode) GetBinary() *PatriciaNode_Binary {
	if x, ok := x.GetNode().(*PatriciaNode_Binary_); ok {
		return x.Binary
	}
	return nil
}

type isPatriciaNode_Node interface {
	isPatriciaNode_Node()
}

type PatriciaNode_Edge_ struct {
	Edge *PatriciaNode_Edge `protobuf:"bytes,1,opt,name=edge,proto3,oneof"`
}

type PatriciaNode_Binary_ struct {
	Binary *PatriciaNode_Binary `protobuf:"bytes,2,opt,name=binary,proto3,oneof"`
}

func (*PatriciaNode_Edge_) isPatriciaNode_Node() {}

func (*PatriciaNode_Binary_) isPatriciaNode_Node() {}

// non leaf nodes required to build the trie given the range (leaves)
type PatriciaRangeProof struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nodes []*PatriciaNode `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
}

func (x *PatriciaRangeProof) Reset() {
	*x = PatriciaRangeProof{}
	if protoimpl.UnsafeEnabled {
		mi := &file_p2p_proto_snapshot_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PatriciaRangeProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatriciaRangeProof) ProtoMessage() {}

func (x *PatriciaRangeProof) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_snapshot_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatriciaRangeProof.ProtoReflect.Descriptor instead.
func (*PatriciaRangeProof) Descriptor() ([]byte, []int) {
	return file_p2p_proto_snapshot_proto_rawDescGZIP(), []int{1}
}

func (x *PatriciaRangeProof) GetNodes() []*PatriciaNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

// leafs of the contract state tree
type ContractState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address *Address `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"` // the key
	Class   *Hash    `protobuf:"bytes,2,opt,name=class,proto3" json:"class,omitempty"`
	Storage *Hash    `protobuf:"bytes,3,opt,name=storage,proto3" json:"storage,omitempty"` // patricia
	Nonce   uint64   `protobuf:"varint,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
}

func (x *ContractState) Reset() {
	*x = ContractState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_p2p_proto_snapshot_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContractState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractState) ProtoMessage() {}

func (x *ContractState) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_snapshot_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractState.ProtoReflect.Descriptor instead.
func (*ContractState) Descriptor() ([]byte, []int) {
	return file_p2p_proto_snapshot_proto_rawDescGZIP(), []int{2}
}

func (x *ContractState) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *ContractState) GetClass() *Hash {
	if x != nil {
		return x.Class
	}
	return nil
}

func (x *ContractState) GetStorage() *Hash {
	if x != nil {
		return x.Storage
	}
	return nil
}

func (x *ContractState) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

// request a range from the contract state tree that matches the given root (block)
// starts at 'start' and ends no more than 'end'.
// the result is  (ContractRange+, PatriciaRangeProof)*
type ContractRangeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Domain         uint32   `protobuf:"varint,1,opt,name=domain,proto3" json:"domain,omitempty"` // volition
	StateRoot      *Hash    `protobuf:"bytes,2,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	Start          *Address `protobuf:"bytes,3,opt,name=start,proto3" json:"start,omitempty"`
	End            *Address `protobuf:"bytes,4,opt,name=end,proto3" json:"end,omitempty"`
	ChunksPerProof uint32   `protobuf:"varint,5,opt,name=chunks_per_proof,json=chunksPerProof,proto3" json:"chunks_per_proof,omitempty"` // how many ContractRange items to send before sending a proof
}

func (x *ContractRangeRequest) Reset() {
	*x = ContractRangeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_p2p_proto_snapshot_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContractRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractRangeRequest) ProtoMessage() {}

func (x *ContractRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_snapshot_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractRangeRequest.ProtoReflect.Descriptor instead.
func (*ContractRangeRequest) Descriptor() ([]byte, []int) {
	return file_p2p_proto_snapshot_proto_rawDescGZIP(), []int{3}
}

func (x *ContractRangeRequest) GetDomain() uint32 {
	if x != nil {
		return x.Domain
	}
	return 0
}

func (x *ContractRangeRequest) GetStateRoot() *Hash {
	if x != nil {
		return x.StateRoot
	}
	return nil
}

func (x *ContractRangeRequest) GetStart() *Address {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *ContractRangeRequest) GetEnd() *Address {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *ContractRangeRequest) GetChunksPerProof() uint32 {
	if x != nil {
		return x.ChunksPerProof
	}
	return 0
}

// stream of leaves in the contracts tree
type ContractRange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State []*ContractState `protobuf:"bytes,1,rep,name=state,proto3" json:"state,omitempty"`
}

func (x *ContractRange) Reset() {
	*x = ContractRange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_p2p_proto_snapshot_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContractRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractRange) ProtoMessage() {}

func (x *ContractRange) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_snapshot_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractRange.ProtoReflect.Descriptor instead.
func (*ContractRange) Descriptor() ([]byte, []int) {
	return file_p2p_proto_snapshot_proto_rawDescGZIP(), []int{4}
}

func (x *ContractRange) GetState() []*ContractState {
	if x != nil {
		return x.State
	}
	return nil
}

type ContractRangeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Root          *Hash `protobuf:"bytes,1,opt,name=root,proto3,oneof" json:"root,omitempty"`                                        // may not appear if Fin is sent to end the whole response
	ContractsRoot *Hash `protobuf:"bytes,2,opt,name=contracts_root,json=contractsRoot,proto3,oneof" json:"contracts_root,omitempty"` // may not appear if Fin is sent to end the whole response
	ClassesRoot   *Hash `protobuf:"bytes,3,opt,name=classes_root,json=classesRoot,proto3,oneof" json:"classes_root,omitempty"`       // may not appear if Fin is sent to end the whole response
	// Types that are assignable to Responses:
	//
	//	*ContractRangeResponse_Range
	//	*ContractRangeResponse_Fin
	Responses isContractRangeResponse_Responses `protobuf_oneof:"responses"`
}

func (x *ContractRangeResponse) Reset() {
	*x = ContractRangeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_p2p_proto_snapshot_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContractRangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractRangeResponse) ProtoMessage() {}

func (x *ContractRangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_snapshot_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractRangeResponse.ProtoReflect.Descriptor instead.
func (*ContractRangeResponse) Descriptor() ([]byte, []int) {
	return file_p2p_proto_snapshot_proto_rawDescGZIP(), []int{5}
}

func (x *ContractRangeResponse) GetRoot() *Hash {
	if x != nil {
		return x.Root
	}
	return nil
}

func (x *ContractRangeResponse) GetContractsRoot() *Hash {
	if x != nil {
		return x.ContractsRoot
	}
	return nil
}

func (x *ContractRangeResponse) GetClassesRoot() *Hash {
	if x != nil {
		return x.ClassesRoot
	}
	return nil
}

func (m *ContractRangeResponse) GetResponses() isContractRangeResponse_Responses {
	if m != nil {
		return m.Responses
	}
	return nil
}

func (x *ContractRangeResponse) GetRange() *ContractRange {
	if x, ok := x.GetResponses().(*ContractRangeResponse_Range); ok {
		return x.Range
	}
	return nil
}

func (x *ContractRangeResponse) GetFin() *Fin {
	if x, ok := x.GetResponses().(*ContractRangeResponse_Fin); ok {
		return x.Fin
	}
	return nil
}

type isContractRangeResponse_Responses interface {
	isContractRangeResponse_Responses()
}

type ContractRangeResponse_Range struct {
	Range *ContractRange `protobuf:"bytes,4,opt,name=range,proto3,oneof"`
}

type ContractRangeResponse_Fin struct {
	Fin *Fin `protobuf:"bytes,5,opt,name=fin,proto3,oneof"`
}

func (*ContractRangeResponse_Range) isContractRangeResponse_Responses() {}

func (*ContractRangeResponse_Fin) isContractRangeResponse_Responses() {}

// duplicate of GetContractRange. Can introduce a 'type' instead.
// result is (Classes+, PatriciaRangeProof)*
type ClassRangeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Root           *Hash  `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	Start          *Hash  `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	End            *Hash  `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
	ChunksPerProof uint32 `protobuf:"varint,4,opt,name=chunks_per_proof,json=chunksPerProof,proto3" json:"chunks_per_proof,omitempty"`
}

func (x *ClassRangeRequest) Reset() {
	*x = ClassRangeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_p2p_proto_snapshot_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClassRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassRangeRequest) ProtoMessage() {}

func (x *ClassRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_snapshot_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassRangeRequest.ProtoReflect.Descriptor instead.
func (*ClassRangeRequest) Descriptor() ([]byte, []int) {
	return file_p2p_proto_snapshot_proto_rawDescGZIP(), []int{6}
}

func (x *ClassRangeRequest) GetRoot() *Hash {
	if x != nil {
		return x.Root
	}
	return nil
}

func (x *ClassRangeRequest) GetStart() *Hash {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *ClassRangeRequest) GetEnd() *Hash {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *ClassRangeRequest) GetChunksPerProof() uint32 {
	if x != nil {
		return x.ChunksPerProof
	}
	return 0
}

type ClassRangeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Root          *Hash `protobuf:"bytes,1,opt,name=root,proto3,oneof" json:"root,omitempty"`                                        // may not appear if Fin is sent to end the whole response
	ContractsRoot *Hash `protobuf:"bytes,2,opt,name=contracts_root,json=contractsRoot,proto3,oneof" json:"contracts_root,omitempty"` // may not appear if Fin is sent to end the whole response
	ClassesRoot   *Hash `protobuf:"bytes,3,opt,name=classes_root,json=classesRoot,proto3,oneof" json:"classes_root,omitempty"`       // may not appear if Fin is sent to end the whole response
	// Types that are assignable to Responses:
	//
	//	*ClassRangeResponse_Classes
	//	*ClassRangeResponse_Fin
	Responses isClassRangeResponse_Responses `protobuf_oneof:"responses"`
}

func (x *ClassRangeResponse) Reset() {
	*x = ClassRangeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_p2p_proto_snapshot_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClassRangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassRangeResponse) ProtoMessage() {}

func (x *ClassRangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_snapshot_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassRangeResponse.ProtoReflect.Descriptor instead.
func (*ClassRangeResponse) Descriptor() ([]byte, []int) {
	return file_p2p_proto_snapshot_proto_rawDescGZIP(), []int{7}
}

func (x *ClassRangeResponse) GetRoot() *Hash {
	if x != nil {
		return x.Root
	}
	return nil
}

func (x *ClassRangeResponse) GetContractsRoot() *Hash {
	if x != nil {
		return x.ContractsRoot
	}
	return nil
}

func (x *ClassRangeResponse) GetClassesRoot() *Hash {
	if x != nil {
		return x.ClassesRoot
	}
	return nil
}

func (m *ClassRangeResponse) GetResponses() isClassRangeResponse_Responses {
	if m != nil {
		return m.Responses
	}
	return nil
}

func (x *ClassRangeResponse) GetClasses() *Classes {
	if x, ok := x.GetResponses().(*ClassRangeResponse_Classes); ok {
		return x.Classes
	}
	return nil
}

func (x *ClassRangeResponse) GetFin() *Fin {
	if x, ok := x.GetResponses().(*ClassRangeResponse_Fin); ok {
		return x.Fin
	}
	return nil
}

type isClassRangeResponse_Responses interface {
	isClassRangeResponse_Responses()
}

type ClassRangeResponse_Classes struct {
	Classes *Classes `protobuf:"bytes,4,opt,name=classes,proto3,oneof"`
}

type ClassRangeResponse_Fin struct {
	Fin *Fin `protobuf:"bytes,5,opt,name=fin,proto3,oneof"`
}

func (*ClassRangeResponse_Classes) isClassRangeResponse_Responses() {}

func (*ClassRangeResponse_Fin) isClassRangeResponse_Responses() {}

// A position in some contract's state tree is identified by the state tree's root and the key in it
type StorageLeafQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContractStorageRoot *Hash    `protobuf:"bytes,1,opt,name=contract_storage_root,json=contractStorageRoot,proto3" json:"contract_storage_root,omitempty"`
	Key                 *Felt252 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *StorageLeafQuery) Reset() {
	*x = StorageLeafQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_p2p_proto_snapshot_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StorageLeafQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageLeafQuery) ProtoMessage() {}

func (x *StorageLeafQuery) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_snapshot_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageLeafQuery.ProtoReflect.Descriptor instead.
func (*StorageLeafQuery) Descriptor() ([]byte, []int) {
	return file_p2p_proto_snapshot_proto_rawDescGZIP(), []int{8}
}

func (x *StorageLeafQuery) GetContractStorageRoot() *Hash {
	if x != nil {
		return x.ContractStorageRoot
	}
	return nil
}

func (x *StorageLeafQuery) GetKey() *Felt252 {
	if x != nil {
		return x.Key
	}
	return nil
}

type StorageRangeQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Start *StorageLeafQuery `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End   *StorageLeafQuery `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
}

func (x *StorageRangeQuery) Reset() {
	*x = StorageRangeQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_p2p_proto_snapshot_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StorageRangeQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageRangeQuery) ProtoMessage() {}

func (x *StorageRangeQuery) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_snapshot_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageRangeQuery.ProtoReflect.Descriptor instead.
func (*StorageRangeQuery) Descriptor() ([]byte, []int) {
	return file_p2p_proto_snapshot_proto_rawDescGZIP(), []int{9}
}

func (x *StorageRangeQuery) GetStart() *StorageLeafQuery {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *StorageRangeQuery) GetEnd() *StorageLeafQuery {
	if x != nil {
		return x.End
	}
	return nil
}

// result is (ContractStorageRange+, PatriciaRangeProof)*
type ContractStorageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Domain    uint32               `protobuf:"varint,1,opt,name=domain,proto3" json:"domain,omitempty"` // volition
	StateRoot *Hash                `protobuf:"bytes,2,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	Query     []*StorageRangeQuery `protobuf:"bytes,3,rep,name=query,proto3" json:"query,omitempty"`
}

func (x *ContractStorageRequest) Reset() {
	*x = ContractStorageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_p2p_proto_snapshot_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContractStorageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractStorageRequest) ProtoMessage() {}

func (x *ContractStorageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_snapshot_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractStorageRequest.ProtoReflect.Descriptor instead.
func (*ContractStorageRequest) Descriptor() ([]byte, []int) {
	return file_p2p_proto_snapshot_proto_rawDescGZIP(), []int{10}
}

func (x *ContractStorageRequest) GetDomain() uint32 {
	if x != nil {
		return x.Domain
	}
	return 0
}

func (x *ContractStorageRequest) GetStateRoot() *Hash {
	if x != nil {
		return x.StateRoot
	}
	return nil
}

func (x *ContractStorageRequest) GetQuery() []*StorageRangeQuery {
	if x != nil {
		return x.Query
	}
	return nil
}

type ContractStorage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KeyValue []*ContractStoredValue `protobuf:"bytes,2,rep,name=keyValue,proto3" json:"keyValue,omitempty"`
}

func (x *ContractStorage) Reset() {
	*x = ContractStorage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_p2p_proto_snapshot_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContractStorage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractStorage) ProtoMessage() {}

func (x *ContractStorage) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_snapshot_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractStorage.ProtoReflect.Descriptor instead.
func (*ContractStorage) Descriptor() ([]byte, []int) {
	return file_p2p_proto_snapshot_proto_rawDescGZIP(), []int{11}
}

func (x *ContractStorage) GetKeyValue() []*ContractStoredValue {
	if x != nil {
		return x.KeyValue
	}
	return nil
}

type ContractStorageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StateRoot *Hash `protobuf:"bytes,1,opt,name=state_root,json=stateRoot,proto3,oneof" json:"state_root,omitempty"` // may not appear if Fin is sent to end the whole response
	// Types that are assignable to Responses:
	//
	//	*ContractStorageResponse_Storage
	//	*ContractStorageResponse_Fin
	Responses isContractStorageResponse_Responses `protobuf_oneof:"responses"`
}

func (x *ContractStorageResponse) Reset() {
	*x = ContractStorageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_p2p_proto_snapshot_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContractStorageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractStorageResponse) ProtoMessage() {}

func (x *ContractStorageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_snapshot_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractStorageResponse.ProtoReflect.Descriptor instead.
func (*ContractStorageResponse) Descriptor() ([]byte, []int) {
	return file_p2p_proto_snapshot_proto_rawDescGZIP(), []int{12}
}

func (x *ContractStorageResponse) GetStateRoot() *Hash {
	if x != nil {
		return x.StateRoot
	}
	return nil
}

func (m *ContractStorageResponse) GetResponses() isContractStorageResponse_Responses {
	if m != nil {
		return m.Responses
	}
	return nil
}

func (x *ContractStorageResponse) GetStorage() *ContractStorage {
	if x, ok := x.GetResponses().(*ContractStorageResponse_Storage); ok {
		return x.Storage
	}
	return nil
}

func (x *ContractStorageResponse) GetFin() *Fin {
	if x, ok := x.GetResponses().(*ContractStorageResponse_Fin); ok {
		return x.Fin
	}
	return nil
}

type isContractStorageResponse_Responses interface {
	isContractStorageResponse_Responses()
}

type ContractStorageResponse_Storage struct {
	Storage *ContractStorage `protobuf:"bytes,2,opt,name=storage,proto3,oneof"`
}

type ContractStorageResponse_Fin struct {
	Fin *Fin `protobuf:"bytes,3,opt,name=fin,proto3,oneof"`
}

func (*ContractStorageResponse_Storage) isContractStorageResponse_Responses() {}

func (*ContractStorageResponse_Fin) isContractStorageResponse_Responses() {}

type PatriciaNode_Edge struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Length uint32   `protobuf:"varint,1,opt,name=length,proto3" json:"length,omitempty"`
	Path   *Felt252 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"` // as bits of left/right
	Value  *Felt252 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *PatriciaNode_Edge) Reset() {
	*x = PatriciaNode_Edge{}
	if protoimpl.UnsafeEnabled {
		mi := &file_p2p_proto_snapshot_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PatriciaNode_Edge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatriciaNode_Edge) ProtoMessage() {}

func (x *PatriciaNode_Edge) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_snapshot_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatriciaNode_Edge.ProtoReflect.Descriptor instead.
func (*PatriciaNode_Edge) Descriptor() ([]byte, []int) {
	return file_p2p_proto_snapshot_proto_rawDescGZIP(), []int{0, 0}
}

func (x *PatriciaNode_Edge) GetLength() uint32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *PatriciaNode_Edge) GetPath() *Felt252 {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *PatriciaNode_Edge) GetValue() *Felt252 {
	if x != nil {
		return x.Value
	}
	return nil
}

type PatriciaNode_Binary struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Left  *Felt252 `protobuf:"bytes,1,opt,name=left,proto3" json:"left,omitempty"`
	Right *Felt252 `protobuf:"bytes,2,opt,name=right,proto3" json:"right,omitempty"`
}

func (x *PatriciaNode_Binary) Reset() {
	*x = PatriciaNode_Binary{}
	if protoimpl.UnsafeEnabled {
		mi := &file_p2p_proto_snapshot_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PatriciaNode_Binary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatriciaNode_Binary) ProtoMessage() {}

func (x *PatriciaNode_Binary) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_snapshot_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatriciaNode_Binary.ProtoReflect.Descriptor instead.
func (*PatriciaNode_Binary) Descriptor() ([]byte, []int) {
	return file_p2p_proto_snapshot_proto_rawDescGZIP(), []int{0, 1}
}

func (x *PatriciaNode_Binary) GetLeft() *Felt252 {
	if x != nil {
		return x.Left
	}
	return nil
}

func (x *PatriciaNode_Binary) GetRight() *Felt252 {
	if x != nil {
		return x.Right
	}
	return nil
}

var File_p2p_proto_snapshot_proto protoreflect.FileDescriptor

var file_p2p_proto_snapshot_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x32, 0x70, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x6e, 0x61, 0x70,
	0x73, 0x68, 0x6f, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x16, 0x70, 0x32, 0x70, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x15, 0x70, 0x32, 0x70, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x96, 0x02, 0x0a, 0x0c, 0x50, 0x61,
	0x74, 0x72, 0x69, 0x63, 0x69, 0x61, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x28, 0x0a, 0x04, 0x65, 0x64,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x50, 0x61, 0x74, 0x72, 0x69,
	0x63, 0x69, 0x61, 0x4e, 0x6f, 0x64, 0x65, 0x2e, 0x45, 0x64, 0x67, 0x65, 0x48, 0x00, 0x52, 0x04,
	0x65, 0x64, 0x67, 0x65, 0x12, 0x2e, 0x0a, 0x06, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x50, 0x61, 0x74, 0x72, 0x69, 0x63, 0x69, 0x61, 0x4e,
	0x6f, 0x64, 0x65, 0x2e, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x48, 0x00, 0x52, 0x06, 0x62, 0x69,
	0x6e, 0x61, 0x72, 0x79, 0x1a, 0x5c, 0x0a, 0x04, 0x45, 0x64, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x6c, 0x65,
	0x6e, 0x67, 0x74, 0x68, 0x12, 0x1c, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x08, 0x2e, 0x46, 0x65, 0x6c, 0x74, 0x32, 0x35, 0x32, 0x52, 0x04, 0x70, 0x61,
	0x74, 0x68, 0x12, 0x1e, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x08, 0x2e, 0x46, 0x65, 0x6c, 0x74, 0x32, 0x35, 0x32, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x1a, 0x46, 0x0a, 0x06, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x12, 0x1c, 0x0a, 0x04,
	0x6c, 0x65, 0x66, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x46, 0x65, 0x6c,
	0x74, 0x32, 0x35, 0x32, 0x52, 0x04, 0x6c, 0x65, 0x66, 0x74, 0x12, 0x1e, 0x0a, 0x05, 0x72, 0x69,
	0x67, 0x68, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x46, 0x65, 0x6c, 0x74,
	0x32, 0x35, 0x32, 0x52, 0x05, 0x72, 0x69, 0x67, 0x68, 0x74, 0x42, 0x06, 0x0a, 0x04, 0x6e, 0x6f,
	0x64, 0x65, 0x22, 0x39, 0x0a, 0x12, 0x50, 0x61, 0x74, 0x72, 0x69, 0x63, 0x69, 0x61, 0x52, 0x61,
	0x6e, 0x67, 0x65, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x12, 0x23, 0x0a, 0x05, 0x6e, 0x6f, 0x64, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x50, 0x61, 0x74, 0x72, 0x69, 0x63,
	0x69, 0x61, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x22, 0x87, 0x01,
	0x0a, 0x0d, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12,
	0x22, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x08, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x12, 0x1b, 0x0a, 0x05, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x05, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x52, 0x05, 0x63, 0x6c, 0x61, 0x73, 0x73,
	0x12, 0x1f, 0x0a, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x05, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x52, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x22, 0xba, 0x01, 0x0a, 0x14, 0x43, 0x6f, 0x6e, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x24, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x5f, 0x72, 0x6f, 0x6f, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x48,
	0x61, 0x73, 0x68, 0x52, 0x09, 0x73, 0x74, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x74, 0x12, 0x1e,
	0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x1a,
	0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x03, 0x65, 0x6e, 0x64, 0x12, 0x28, 0x0a, 0x10, 0x63, 0x68,
	0x75, 0x6e, 0x6b, 0x73, 0x5f, 0x70, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x73, 0x50, 0x65, 0x72, 0x50,
	0x72, 0x6f, 0x6f, 0x66, 0x22, 0x35, 0x0a, 0x0d, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74,
	0x52, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x24, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x95, 0x02, 0x0a, 0x15,
	0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x04, 0x72, 0x6f, 0x6f, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x48, 0x01, 0x52, 0x04, 0x72, 0x6f,
	0x6f, 0x74, 0x88, 0x01, 0x01, 0x12, 0x31, 0x0a, 0x0e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x73, 0x5f, 0x72, 0x6f, 0x6f, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e,
	0x48, 0x61, 0x73, 0x68, 0x48, 0x02, 0x52, 0x0d, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74,
	0x73, 0x52, 0x6f, 0x6f, 0x74, 0x88, 0x01, 0x01, 0x12, 0x2d, 0x0a, 0x0c, 0x63, 0x6c, 0x61, 0x73,
	0x73, 0x65, 0x73, 0x5f, 0x72, 0x6f, 0x6f, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05,
	0x2e, 0x48, 0x61, 0x73, 0x68, 0x48, 0x03, 0x52, 0x0b, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x65, 0x73,
	0x52, 0x6f, 0x6f, 0x74, 0x88, 0x01, 0x01, 0x12, 0x26, 0x0a, 0x05, 0x72, 0x61, 0x6e, 0x67, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x48, 0x00, 0x52, 0x05, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x12,
	0x18, 0x0a, 0x03, 0x66, 0x69, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x04, 0x2e, 0x46,
	0x69, 0x6e, 0x48, 0x00, 0x52, 0x03, 0x66, 0x69, 0x6e, 0x42, 0x0b, 0x0a, 0x09, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x72, 0x6f, 0x6f, 0x74, 0x42,
	0x11, 0x0a, 0x0f, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73, 0x5f, 0x72, 0x6f,
	0x6f, 0x74, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x65, 0x73, 0x5f, 0x72,
	0x6f, 0x6f, 0x74, 0x22, 0x8e, 0x01, 0x0a, 0x11, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x52, 0x61, 0x6e,
	0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x04, 0x72, 0x6f, 0x6f,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x52, 0x04,
	0x72, 0x6f, 0x6f, 0x74, 0x12, 0x1b, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x12, 0x17, 0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05,
	0x2e, 0x48, 0x61, 0x73, 0x68, 0x52, 0x03, 0x65, 0x6e, 0x64, 0x12, 0x28, 0x0a, 0x10, 0x63, 0x68,
	0x75, 0x6e, 0x6b, 0x73, 0x5f, 0x70, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x73, 0x50, 0x65, 0x72, 0x50,
	0x72, 0x6f, 0x6f, 0x66, 0x22, 0x90, 0x02, 0x0a, 0x12, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x52, 0x61,
	0x6e, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x04, 0x72,
	0x6f, 0x6f, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x48, 0x61, 0x73, 0x68,
	0x48, 0x01, 0x52, 0x04, 0x72, 0x6f, 0x6f, 0x74, 0x88, 0x01, 0x01, 0x12, 0x31, 0x0a, 0x0e, 0x63,
	0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73, 0x5f, 0x72, 0x6f, 0x6f, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x48, 0x02, 0x52, 0x0d, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73, 0x52, 0x6f, 0x6f, 0x74, 0x88, 0x01, 0x01, 0x12, 0x2d,
	0x0a, 0x0c, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x65, 0x73, 0x5f, 0x72, 0x6f, 0x6f, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x48, 0x03, 0x52, 0x0b, 0x63,
	0x6c, 0x61, 0x73, 0x73, 0x65, 0x73, 0x52, 0x6f, 0x6f, 0x74, 0x88, 0x01, 0x01, 0x12, 0x24, 0x0a,
	0x07, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08,
	0x2e, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x65, 0x73, 0x48, 0x00, 0x52, 0x07, 0x63, 0x6c, 0x61, 0x73,
	0x73, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x03, 0x66, 0x69, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x04, 0x2e, 0x46, 0x69, 0x6e, 0x48, 0x00, 0x52, 0x03, 0x66, 0x69, 0x6e, 0x42, 0x0b, 0x0a,
	0x09, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x72,
	0x6f, 0x6f, 0x74, 0x42, 0x11, 0x0a, 0x0f, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74,
	0x73, 0x5f, 0x72, 0x6f, 0x6f, 0x74, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x63, 0x6c, 0x61, 0x73, 0x73,
	0x65, 0x73, 0x5f, 0x72, 0x6f, 0x6f, 0x74, 0x22, 0x69, 0x0a, 0x10, 0x53, 0x74, 0x6f, 0x72, 0x61,
	0x67, 0x65, 0x4c, 0x65, 0x61, 0x66, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x39, 0x0a, 0x15, 0x63,
	0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f,
	0x72, 0x6f, 0x6f, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x48, 0x61, 0x73,
	0x68, 0x52, 0x13, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x53, 0x74, 0x6f, 0x72, 0x61,
	0x67, 0x65, 0x52, 0x6f, 0x6f, 0x74, 0x12, 0x1a, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x46, 0x65, 0x6c, 0x74, 0x32, 0x35, 0x32, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x22, 0x61, 0x0a, 0x11, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x52, 0x61, 0x6e,
	0x67, 0x65, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x27, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65,
	0x4c, 0x65, 0x61, 0x66, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x12, 0x23, 0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x4c, 0x65, 0x61, 0x66, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x52, 0x03, 0x65, 0x6e, 0x64, 0x22, 0x80, 0x01, 0x0a, 0x16, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61,
	0x63, 0x74, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x24, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x5f, 0x72, 0x6f, 0x6f, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x48,
	0x61, 0x73, 0x68, 0x52, 0x09, 0x73, 0x74, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x74, 0x12, 0x28,
	0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x22, 0x43, 0x0a, 0x0f, 0x43, 0x6f, 0x6e, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x12, 0x30, 0x0a, 0x08, 0x6b,
	0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x64, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x52, 0x08, 0x6b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0xa8, 0x01,
	0x0a, 0x17, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x0a, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x5f, 0x72, 0x6f, 0x6f, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e,
	0x48, 0x61, 0x73, 0x68, 0x48, 0x01, 0x52, 0x09, 0x73, 0x74, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f,
	0x74, 0x88, 0x01, 0x01, 0x12, 0x2c, 0x0a, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74,
	0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x61,
	0x67, 0x65, 0x12, 0x18, 0x0a, 0x03, 0x66, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x04, 0x2e, 0x46, 0x69, 0x6e, 0x48, 0x00, 0x52, 0x03, 0x66, 0x69, 0x6e, 0x42, 0x0b, 0x0a, 0x09,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x5f, 0x72, 0x6f, 0x6f, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_p2p_proto_snapshot_proto_rawDescOnce sync.Once
	file_p2p_proto_snapshot_proto_rawDescData = file_p2p_proto_snapshot_proto_rawDesc
)

func file_p2p_proto_snapshot_proto_rawDescGZIP() []byte {
	file_p2p_proto_snapshot_proto_rawDescOnce.Do(func() {
		file_p2p_proto_snapshot_proto_rawDescData = protoimpl.X.CompressGZIP(file_p2p_proto_snapshot_proto_rawDescData)
	})
	return file_p2p_proto_snapshot_proto_rawDescData
}

var (
	file_p2p_proto_snapshot_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
	file_p2p_proto_snapshot_proto_goTypes  = []interface{}{
		(*PatriciaNode)(nil),            // 0: PatriciaNode
		(*PatriciaRangeProof)(nil),      // 1: PatriciaRangeProof
		(*ContractState)(nil),           // 2: ContractState
		(*ContractRangeRequest)(nil),    // 3: ContractRangeRequest
		(*ContractRange)(nil),           // 4: ContractRange
		(*ContractRangeResponse)(nil),   // 5: ContractRangeResponse
		(*ClassRangeRequest)(nil),       // 6: ClassRangeRequest
		(*ClassRangeResponse)(nil),      // 7: ClassRangeResponse
		(*StorageLeafQuery)(nil),        // 8: StorageLeafQuery
		(*StorageRangeQuery)(nil),       // 9: StorageRangeQuery
		(*ContractStorageRequest)(nil),  // 10: ContractStorageRequest
		(*ContractStorage)(nil),         // 11: ContractStorage
		(*ContractStorageResponse)(nil), // 12: ContractStorageResponse
		(*PatriciaNode_Edge)(nil),       // 13: PatriciaNode.Edge
		(*PatriciaNode_Binary)(nil),     // 14: PatriciaNode.Binary
		(*Address)(nil),                 // 15: Address
		(*Hash)(nil),                    // 16: Hash
		(*Fin)(nil),                     // 17: Fin
		(*Classes)(nil),                 // 18: Classes
		(*Felt252)(nil),                 // 19: Felt252
		(*ContractStoredValue)(nil),     // 20: ContractStoredValue
	}
)

var file_p2p_proto_snapshot_proto_depIdxs = []int32{
	13, // 0: PatriciaNode.edge:type_name -> PatriciaNode.Edge
	14, // 1: PatriciaNode.binary:type_name -> PatriciaNode.Binary
	0,  // 2: PatriciaRangeProof.nodes:type_name -> PatriciaNode
	15, // 3: ContractState.address:type_name -> Address
	16, // 4: ContractState.class:type_name -> Hash
	16, // 5: ContractState.storage:type_name -> Hash
	16, // 6: ContractRangeRequest.state_root:type_name -> Hash
	15, // 7: ContractRangeRequest.start:type_name -> Address
	15, // 8: ContractRangeRequest.end:type_name -> Address
	2,  // 9: ContractRange.state:type_name -> ContractState
	16, // 10: ContractRangeResponse.root:type_name -> Hash
	16, // 11: ContractRangeResponse.contracts_root:type_name -> Hash
	16, // 12: ContractRangeResponse.classes_root:type_name -> Hash
	4,  // 13: ContractRangeResponse.range:type_name -> ContractRange
	17, // 14: ContractRangeResponse.fin:type_name -> Fin
	16, // 15: ClassRangeRequest.root:type_name -> Hash
	16, // 16: ClassRangeRequest.start:type_name -> Hash
	16, // 17: ClassRangeRequest.end:type_name -> Hash
	16, // 18: ClassRangeResponse.root:type_name -> Hash
	16, // 19: ClassRangeResponse.contracts_root:type_name -> Hash
	16, // 20: ClassRangeResponse.classes_root:type_name -> Hash
	18, // 21: ClassRangeResponse.classes:type_name -> Classes
	17, // 22: ClassRangeResponse.fin:type_name -> Fin
	16, // 23: StorageLeafQuery.contract_storage_root:type_name -> Hash
	19, // 24: StorageLeafQuery.key:type_name -> Felt252
	8,  // 25: StorageRangeQuery.start:type_name -> StorageLeafQuery
	8,  // 26: StorageRangeQuery.end:type_name -> StorageLeafQuery
	16, // 27: ContractStorageRequest.state_root:type_name -> Hash
	9,  // 28: ContractStorageRequest.query:type_name -> StorageRangeQuery
	20, // 29: ContractStorage.keyValue:type_name -> ContractStoredValue
	16, // 30: ContractStorageResponse.state_root:type_name -> Hash
	11, // 31: ContractStorageResponse.storage:type_name -> ContractStorage
	17, // 32: ContractStorageResponse.fin:type_name -> Fin
	19, // 33: PatriciaNode.Edge.path:type_name -> Felt252
	19, // 34: PatriciaNode.Edge.value:type_name -> Felt252
	19, // 35: PatriciaNode.Binary.left:type_name -> Felt252
	19, // 36: PatriciaNode.Binary.right:type_name -> Felt252
	37, // [37:37] is the sub-list for method output_type
	37, // [37:37] is the sub-list for method input_type
	37, // [37:37] is the sub-list for extension type_name
	37, // [37:37] is the sub-list for extension extendee
	0,  // [0:37] is the sub-list for field type_name
}

func init() { file_p2p_proto_snapshot_proto_init() }
func file_p2p_proto_snapshot_proto_init() {
	if File_p2p_proto_snapshot_proto != nil {
		return
	}
	file_p2p_proto_common_proto_init()
	file_p2p_proto_state_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_p2p_proto_snapshot_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PatriciaNode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_p2p_proto_snapshot_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PatriciaRangeProof); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_p2p_proto_snapshot_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContractState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_p2p_proto_snapshot_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContractRangeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_p2p_proto_snapshot_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContractRange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_p2p_proto_snapshot_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContractRangeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_p2p_proto_snapshot_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClassRangeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_p2p_proto_snapshot_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClassRangeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_p2p_proto_snapshot_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StorageLeafQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_p2p_proto_snapshot_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StorageRangeQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_p2p_proto_snapshot_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContractStorageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_p2p_proto_snapshot_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContractStorage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_p2p_proto_snapshot_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContractStorageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_p2p_proto_snapshot_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PatriciaNode_Edge); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_p2p_proto_snapshot_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PatriciaNode_Binary); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_p2p_proto_snapshot_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*PatriciaNode_Edge_)(nil),
		(*PatriciaNode_Binary_)(nil),
	}
	file_p2p_proto_snapshot_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*ContractRangeResponse_Range)(nil),
		(*ContractRangeResponse_Fin)(nil),
	}
	file_p2p_proto_snapshot_proto_msgTypes[7].OneofWrappers = []interface{}{
		(*ClassRangeResponse_Classes)(nil),
		(*ClassRangeResponse_Fin)(nil),
	}
	file_p2p_proto_snapshot_proto_msgTypes[12].OneofWrappers = []interface{}{
		(*ContractStorageResponse_Storage)(nil),
		(*ContractStorageResponse_Fin)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_p2p_proto_snapshot_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_p2p_proto_snapshot_proto_goTypes,
		DependencyIndexes: file_p2p_proto_snapshot_proto_depIdxs,
		MessageInfos:      file_p2p_proto_snapshot_proto_msgTypes,
	}.Build()
	File_p2p_proto_snapshot_proto = out.File
	file_p2p_proto_snapshot_proto_rawDesc = nil
	file_p2p_proto_snapshot_proto_goTypes = nil
	file_p2p_proto_snapshot_proto_depIdxs = nil
}
