// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: protobuf/compiled_class.proto

package junopb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Felt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Be32          []byte                 `protobuf:"bytes,1,opt,name=be32,proto3" json:"be32,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Felt) Reset() {
	*x = Felt{}
	mi := &file_protobuf_compiled_class_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Felt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Felt) ProtoMessage() {}

func (x *Felt) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_compiled_class_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Felt.ProtoReflect.Descriptor instead.
func (*Felt) Descriptor() ([]byte, []int) {
	return file_protobuf_compiled_class_proto_rawDescGZIP(), []int{0}
}

func (x *Felt) GetBe32() []byte {
	if x != nil {
		return x.Be32
	}
	return nil
}

type SierraEntryPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint64                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Selector      *Felt                  `protobuf:"bytes,2,opt,name=selector,proto3" json:"selector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SierraEntryPoint) Reset() {
	*x = SierraEntryPoint{}
	mi := &file_protobuf_compiled_class_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SierraEntryPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SierraEntryPoint) ProtoMessage() {}

func (x *SierraEntryPoint) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_compiled_class_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SierraEntryPoint.ProtoReflect.Descriptor instead.
func (*SierraEntryPoint) Descriptor() ([]byte, []int) {
	return file_protobuf_compiled_class_proto_rawDescGZIP(), []int{1}
}

func (x *SierraEntryPoint) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *SierraEntryPoint) GetSelector() *Felt {
	if x != nil {
		return x.Selector
	}
	return nil
}

type CompiledEntryPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Selector      *Felt                  `protobuf:"bytes,1,opt,name=selector,proto3" json:"selector,omitempty"`
	Offset        uint64                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Builtins      []string               `protobuf:"bytes,3,rep,name=builtins,proto3" json:"builtins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompiledEntryPoint) Reset() {
	*x = CompiledEntryPoint{}
	mi := &file_protobuf_compiled_class_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompiledEntryPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompiledEntryPoint) ProtoMessage() {}

func (x *CompiledEntryPoint) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_compiled_class_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompiledEntryPoint.ProtoReflect.Descriptor instead.
func (*CompiledEntryPoint) Descriptor() ([]byte, []int) {
	return file_protobuf_compiled_class_proto_rawDescGZIP(), []int{2}
}

func (x *CompiledEntryPoint) GetSelector() *Felt {
	if x != nil {
		return x.Selector
	}
	return nil
}

func (x *CompiledEntryPoint) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *CompiledEntryPoint) GetBuiltins() []string {
	if x != nil {
		return x.Builtins
	}
	return nil
}

type CasmClass struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Prime                  string                 `protobuf:"bytes,1,opt,name=prime,proto3" json:"prime,omitempty"`
	Bytecode               []*Felt                `protobuf:"bytes,2,rep,name=bytecode,proto3" json:"bytecode,omitempty"`
	HintsJson              []byte                 `protobuf:"bytes,3,opt,name=hints_json,json=hintsJson,proto3" json:"hints_json,omitempty"`
	PythonicHintsJson      []byte                 `protobuf:"bytes,4,opt,name=pythonic_hints_json,json=pythonicHintsJson,proto3" json:"pythonic_hints_json,omitempty"`
	CompilerVersion        string                 `protobuf:"bytes,5,opt,name=compiler_version,json=compilerVersion,proto3" json:"compiler_version,omitempty"`
	BytecodeSegmentLengths []byte                 `protobuf:"bytes,6,opt,name=bytecode_segment_lengths,json=bytecodeSegmentLengths,proto3" json:"bytecode_segment_lengths,omitempty"`
	External               []*CompiledEntryPoint  `protobuf:"bytes,10,rep,name=external,proto3" json:"external,omitempty"`
	L1Handler              []*CompiledEntryPoint  `protobuf:"bytes,11,rep,name=l1_handler,json=l1Handler,proto3" json:"l1_handler,omitempty"`
	Constructor            []*CompiledEntryPoint  `protobuf:"bytes,12,rep,name=constructor,proto3" json:"constructor,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CasmClass) Reset() {
	*x = CasmClass{}
	mi := &file_protobuf_compiled_class_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CasmClass) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CasmClass) ProtoMessage() {}

func (x *CasmClass) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_compiled_class_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CasmClass.ProtoReflect.Descriptor instead.
func (*CasmClass) Descriptor() ([]byte, []int) {
	return file_protobuf_compiled_class_proto_rawDescGZIP(), []int{3}
}

func (x *CasmClass) GetPrime() string {
	if x != nil {
		return x.Prime
	}
	return ""
}

func (x *CasmClass) GetBytecode() []*Felt {
	if x != nil {
		return x.Bytecode
	}
	return nil
}

func (x *CasmClass) GetHintsJson() []byte {
	if x != nil {
		return x.HintsJson
	}
	return nil
}

func (x *CasmClass) GetPythonicHintsJson() []byte {
	if x != nil {
		return x.PythonicHintsJson
	}
	return nil
}

func (x *CasmClass) GetCompilerVersion() string {
	if x != nil {
		return x.CompilerVersion
	}
	return ""
}

func (x *CasmClass) GetBytecodeSegmentLengths() []byte {
	if x != nil {
		return x.BytecodeSegmentLengths
	}
	return nil
}

func (x *CasmClass) GetExternal() []*CompiledEntryPoint {
	if x != nil {
		return x.External
	}
	return nil
}

func (x *CasmClass) GetL1Handler() []*CompiledEntryPoint {
	if x != nil {
		return x.L1Handler
	}
	return nil
}

func (x *CasmClass) GetConstructor() []*CompiledEntryPoint {
	if x != nil {
		return x.Constructor
	}
	return nil
}

type DeprecatedEntryPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Selector      *Felt                  `protobuf:"bytes,1,opt,name=selector,proto3" json:"selector,omitempty"`
	Offset        *Felt                  `protobuf:"bytes,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeprecatedEntryPoint) Reset() {
	*x = DeprecatedEntryPoint{}
	mi := &file_protobuf_compiled_class_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeprecatedEntryPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeprecatedEntryPoint) ProtoMessage() {}

func (x *DeprecatedEntryPoint) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_compiled_class_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeprecatedEntryPoint.ProtoReflect.Descriptor instead.
func (*DeprecatedEntryPoint) Descriptor() ([]byte, []int) {
	return file_protobuf_compiled_class_proto_rawDescGZIP(), []int{4}
}

func (x *DeprecatedEntryPoint) GetSelector() *Felt {
	if x != nil {
		return x.Selector
	}
	return nil
}

func (x *DeprecatedEntryPoint) GetOffset() *Felt {
	if x != nil {
		return x.Offset
	}
	return nil
}

type DeprecatedCairoClass struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	AbiJson       []byte                  `protobuf:"bytes,1,opt,name=abi_json,json=abiJson,proto3" json:"abi_json,omitempty"`
	Externals     []*DeprecatedEntryPoint `protobuf:"bytes,2,rep,name=externals,proto3" json:"externals,omitempty"`
	L1Handlers    []*DeprecatedEntryPoint `protobuf:"bytes,3,rep,name=l1_handlers,json=l1Handlers,proto3" json:"l1_handlers,omitempty"`
	Constructors  []*DeprecatedEntryPoint `protobuf:"bytes,4,rep,name=constructors,proto3" json:"constructors,omitempty"`
	ProgramB64    []byte                  `protobuf:"bytes,5,opt,name=program_b64,json=programB64,proto3" json:"program_b64,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeprecatedCairoClass) Reset() {
	*x = DeprecatedCairoClass{}
	mi := &file_protobuf_compiled_class_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeprecatedCairoClass) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeprecatedCairoClass) ProtoMessage() {}

func (x *DeprecatedCairoClass) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_compiled_class_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeprecatedCairoClass.ProtoReflect.Descriptor instead.
func (*DeprecatedCairoClass) Descriptor() ([]byte, []int) {
	return file_protobuf_compiled_class_proto_rawDescGZIP(), []int{5}
}

func (x *DeprecatedCairoClass) GetAbiJson() []byte {
	if x != nil {
		return x.AbiJson
	}
	return nil
}

func (x *DeprecatedCairoClass) GetExternals() []*DeprecatedEntryPoint {
	if x != nil {
		return x.Externals
	}
	return nil
}

func (x *DeprecatedCairoClass) GetL1Handlers() []*DeprecatedEntryPoint {
	if x != nil {
		return x.L1Handlers
	}
	return nil
}

func (x *DeprecatedCairoClass) GetConstructors() []*DeprecatedEntryPoint {
	if x != nil {
		return x.Constructors
	}
	return nil
}

func (x *DeprecatedCairoClass) GetProgramB64() []byte {
	if x != nil {
		return x.ProgramB64
	}
	return nil
}

type CompiledClass struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	CairoVersion        uint32                 `protobuf:"varint,1,opt,name=cairo_version,json=cairoVersion,proto3" json:"cairo_version,omitempty"`
	AbiLength           uint32                 `protobuf:"varint,2,opt,name=abi_length,json=abiLength,proto3" json:"abi_length,omitempty"`
	SierraProgramLength uint32                 `protobuf:"varint,3,opt,name=sierra_program_length,json=sierraProgramLength,proto3" json:"sierra_program_length,omitempty"`
	SierraVersion       string                 `protobuf:"bytes,4,opt,name=sierra_version,json=sierraVersion,proto3" json:"sierra_version,omitempty"`
	// Types that are valid to be assigned to Class:
	//
	//	*CompiledClass_Deprecated
	//	*CompiledClass_Casm
	Class         isCompiledClass_Class `protobuf_oneof:"class"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompiledClass) Reset() {
	*x = CompiledClass{}
	mi := &file_protobuf_compiled_class_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompiledClass) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompiledClass) ProtoMessage() {}

func (x *CompiledClass) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_compiled_class_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompiledClass.ProtoReflect.Descriptor instead.
func (*CompiledClass) Descriptor() ([]byte, []int) {
	return file_protobuf_compiled_class_proto_rawDescGZIP(), []int{6}
}

func (x *CompiledClass) GetCairoVersion() uint32 {
	if x != nil {
		return x.CairoVersion
	}
	return 0
}

func (x *CompiledClass) GetAbiLength() uint32 {
	if x != nil {
		return x.AbiLength
	}
	return 0
}

func (x *CompiledClass) GetSierraProgramLength() uint32 {
	if x != nil {
		return x.SierraProgramLength
	}
	return 0
}

func (x *CompiledClass) GetSierraVersion() string {
	if x != nil {
		return x.SierraVersion
	}
	return ""
}

func (x *CompiledClass) GetClass() isCompiledClass_Class {
	if x != nil {
		return x.Class
	}
	return nil
}

func (x *CompiledClass) GetDeprecated() *DeprecatedCairoClass {
	if x != nil {
		if x, ok := x.Class.(*CompiledClass_Deprecated); ok {
			return x.Deprecated
		}
	}
	return nil
}

func (x *CompiledClass) GetCasm() *CasmClass {
	if x != nil {
		if x, ok := x.Class.(*CompiledClass_Casm); ok {
			return x.Casm
		}
	}
	return nil
}

type isCompiledClass_Class interface {
	isCompiledClass_Class()
}

type CompiledClass_Deprecated struct {
	Deprecated *DeprecatedCairoClass `protobuf:"bytes,10,opt,name=deprecated,proto3,oneof"`
}

type CompiledClass_Casm struct {
	Casm *CasmClass `protobuf:"bytes,11,opt,name=casm,proto3,oneof"`
}

func (*CompiledClass_Deprecated) isCompiledClass_Class() {}

func (*CompiledClass_Casm) isCompiledClass_Class() {}

var File_protobuf_compiled_class_proto protoreflect.FileDescriptor

const file_protobuf_compiled_class_proto_rawDesc = "" +
	"\n" +
	"\x1dprotobuf/compiled_class.proto\x12\ajuno.vm\"\x1a\n" +
	"\x04Felt\x12\x12\n" +
	"\x04be32\x18\x01 \x01(\fR\x04be32\"S\n" +
	"\x10SierraEntryPoint\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x04R\x05index\x12)\n" +
	"\bselector\x18\x02 \x01(\v2\r.juno.vm.FeltR\bselector\"s\n" +
	"\x12CompiledEntryPoint\x12)\n" +
	"\bselector\x18\x01 \x01(\v2\r.juno.vm.FeltR\bselector\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset\x12\x1a\n" +
	"\bbuiltins\x18\x03 \x03(\tR\bbuiltins\"\xb4\x03\n" +
	"\tCasmClass\x12\x14\n" +
	"\x05prime\x18\x01 \x01(\tR\x05prime\x12)\n" +
	"\bbytecode\x18\x02 \x03(\v2\r.juno.vm.FeltR\bbytecode\x12\x1d\n" +
	"\n" +
	"hints_json\x18\x03 \x01(\fR\thintsJson\x12.\n" +
	"\x13pythonic_hints_json\x18\x04 \x01(\fR\x11pythonicHintsJson\x12)\n" +
	"\x10compiler_version\x18\x05 \x01(\tR\x0fcompilerVersion\x128\n" +
	"\x18bytecode_segment_lengths\x18\x06 \x01(\fR\x16bytecodeSegmentLengths\x127\n" +
	"\bexternal\x18\n" +
	" \x03(\v2\x1b.juno.vm.CompiledEntryPointR\bexternal\x12:\n" +
	"\n" +
	"l1_handler\x18\v \x03(\v2\x1b.juno.vm.CompiledEntryPointR\tl1Handler\x12=\n" +
	"\vconstructor\x18\f \x03(\v2\x1b.juno.vm.CompiledEntryPointR\vconstructor\"h\n" +
	"\x14DeprecatedEntryPoint\x12)\n" +
	"\bselector\x18\x01 \x01(\v2\r.juno.vm.FeltR\bselector\x12%\n" +
	"\x06offset\x18\x02 \x01(\v2\r.juno.vm.FeltR\x06offset\"\x92\x02\n" +
	"\x14DeprecatedCairoClass\x12\x19\n" +
	"\babi_json\x18\x01 \x01(\fR\aabiJson\x12;\n" +
	"\texternals\x18\x02 \x03(\v2\x1d.juno.vm.DeprecatedEntryPointR\texternals\x12>\n" +
	"\vl1_handlers\x18\x03 \x03(\v2\x1d.juno.vm.DeprecatedEntryPointR\n" +
	"l1Handlers\x12A\n" +
	"\fconstructors\x18\x04 \x03(\v2\x1d.juno.vm.DeprecatedEntryPointR\fconstructors\x12\x1f\n" +
	"\vprogram_b64\x18\x05 \x01(\fR\n" +
	"programB64\"\xa2\x02\n" +
	"\rCompiledClass\x12#\n" +
	"\rcairo_version\x18\x01 \x01(\rR\fcairoVersion\x12\x1d\n" +
	"\n" +
	"abi_length\x18\x02 \x01(\rR\tabiLength\x122\n" +
	"\x15sierra_program_length\x18\x03 \x01(\rR\x13sierraProgramLength\x12%\n" +
	"\x0esierra_version\x18\x04 \x01(\tR\rsierraVersion\x12?\n" +
	"\n" +
	"deprecated\x18\n" +
	" \x01(\v2\x1d.juno.vm.DeprecatedCairoClassH\x00R\n" +
	"deprecated\x12(\n" +
	"\x04casm\x18\v \x01(\v2\x12.juno.vm.CasmClassH\x00R\x04casmB\a\n" +
	"\x05classB,Z*github.com/NethermindEth/juno/vm/pb;junopbb\x06proto3"

var (
	file_protobuf_compiled_class_proto_rawDescOnce sync.Once
	file_protobuf_compiled_class_proto_rawDescData []byte
)

func file_protobuf_compiled_class_proto_rawDescGZIP() []byte {
	file_protobuf_compiled_class_proto_rawDescOnce.Do(func() {
		file_protobuf_compiled_class_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_compiled_class_proto_rawDesc), len(file_protobuf_compiled_class_proto_rawDesc)))
	})
	return file_protobuf_compiled_class_proto_rawDescData
}

var file_protobuf_compiled_class_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_protobuf_compiled_class_proto_goTypes = []any{
	(*Felt)(nil),                 // 0: juno.vm.Felt
	(*SierraEntryPoint)(nil),     // 1: juno.vm.SierraEntryPoint
	(*CompiledEntryPoint)(nil),   // 2: juno.vm.CompiledEntryPoint
	(*CasmClass)(nil),            // 3: juno.vm.CasmClass
	(*DeprecatedEntryPoint)(nil), // 4: juno.vm.DeprecatedEntryPoint
	(*DeprecatedCairoClass)(nil), // 5: juno.vm.DeprecatedCairoClass
	(*CompiledClass)(nil),        // 6: juno.vm.CompiledClass
}
var file_protobuf_compiled_class_proto_depIdxs = []int32{
	0,  // 0: juno.vm.SierraEntryPoint.selector:type_name -> juno.vm.Felt
	0,  // 1: juno.vm.CompiledEntryPoint.selector:type_name -> juno.vm.Felt
	0,  // 2: juno.vm.CasmClass.bytecode:type_name -> juno.vm.Felt
	2,  // 3: juno.vm.CasmClass.external:type_name -> juno.vm.CompiledEntryPoint
	2,  // 4: juno.vm.CasmClass.l1_handler:type_name -> juno.vm.CompiledEntryPoint
	2,  // 5: juno.vm.CasmClass.constructor:type_name -> juno.vm.CompiledEntryPoint
	0,  // 6: juno.vm.DeprecatedEntryPoint.selector:type_name -> juno.vm.Felt
	0,  // 7: juno.vm.DeprecatedEntryPoint.offset:type_name -> juno.vm.Felt
	4,  // 8: juno.vm.DeprecatedCairoClass.externals:type_name -> juno.vm.DeprecatedEntryPoint
	4,  // 9: juno.vm.DeprecatedCairoClass.l1_handlers:type_name -> juno.vm.DeprecatedEntryPoint
	4,  // 10: juno.vm.DeprecatedCairoClass.constructors:type_name -> juno.vm.DeprecatedEntryPoint
	5,  // 11: juno.vm.CompiledClass.deprecated:type_name -> juno.vm.DeprecatedCairoClass
	3,  // 12: juno.vm.CompiledClass.casm:type_name -> juno.vm.CasmClass
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_protobuf_compiled_class_proto_init() }
func file_protobuf_compiled_class_proto_init() {
	if File_protobuf_compiled_class_proto != nil {
		return
	}
	file_protobuf_compiled_class_proto_msgTypes[6].OneofWrappers = []any{
		(*CompiledClass_Deprecated)(nil),
		(*CompiledClass_Casm)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_compiled_class_proto_rawDesc), len(file_protobuf_compiled_class_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_compiled_class_proto_goTypes,
		DependencyIndexes: file_protobuf_compiled_class_proto_depIdxs,
		MessageInfos:      file_protobuf_compiled_class_proto_msgTypes,
	}.Build()
	File_protobuf_compiled_class_proto = out.File
	file_protobuf_compiled_class_proto_goTypes = nil
	file_protobuf_compiled_class_proto_depIdxs = nil
}
