// Code generated by "enumer -type=innerBucket -transform=title -output=buckets_enumer.go"; DO NOT EDIT.

package db

import (
	"fmt"
	"strings"
)

const _innerBucketName = "StateTriePeerContractClassHashContractStorageClassContractNonceChainHeightBlockHeaderNumbersByHashBlockHeadersByNumberTransactionBlockNumbersAndIndicesByHashTransactionsByBlockNumberAndIndexReceiptsByBlockNumberAndIndexStateUpdatesByBlockNumberClassesTrieContractStorageHistoryContractNonceHistoryContractClassHashHistoryContractDeploymentHeightL1HeightDeprecatedSchemaVersionUnusedBlockCommitmentsTemporaryDeprecatedSchemaIntermediateStateL1HandlerTxnHashByMsgHashMempoolHeadMempoolTailMempoolLengthMempoolNodeClassTrieContractTrieContractContractTrieStorageContractStateHashToTrieRootsStateIDPersistedStateIDTrieJournalAggregatedBloomFiltersRunningEventFilterClassCasmHashMetadataBlockTransactionsSchemaMetadataSchemaIntermediateState"

var _innerBucketIndex = [...]uint16{0, 9, 13, 30, 45, 50, 63, 74, 98, 118, 157, 190, 219, 244, 255, 277, 297, 321, 345, 353, 376, 382, 398, 407, 440, 465, 476, 487, 500, 511, 520, 540, 559, 567, 587, 594, 610, 621, 643, 661, 682, 699, 713, 736}

const _innerBucketLowerName = "statetriepeercontractclasshashcontractstorageclasscontractnoncechainheightblockheadernumbersbyhashblockheadersbynumbertransactionblocknumbersandindicesbyhashtransactionsbyblocknumberandindexreceiptsbyblocknumberandindexstateupdatesbyblocknumberclassestriecontractstoragehistorycontractnoncehistorycontractclasshashhistorycontractdeploymentheightl1heightdeprecatedschemaversionunusedblockcommitmentstemporarydeprecatedschemaintermediatestatel1handlertxnhashbymsghashmempoolheadmempooltailmempoollengthmempoolnodeclasstriecontracttriecontractcontracttriestoragecontractstatehashtotrierootsstateidpersistedstateidtriejournalaggregatedbloomfiltersrunningeventfilterclasscasmhashmetadatablocktransactionsschemametadataschemaintermediatestate"

func (i innerBucket) String() string {
	if i >= innerBucket(len(_innerBucketIndex)-1) {
		return fmt.Sprintf("innerBucket(%d)", i)
	}
	return _innerBucketName[_innerBucketIndex[i]:_innerBucketIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _innerBucketNoOp() {
	var x [1]struct{}
	_ = x[stateTrie-(0)]
	_ = x[peer-(1)]
	_ = x[contractClassHash-(2)]
	_ = x[contractStorage-(3)]
	_ = x[class-(4)]
	_ = x[contractNonce-(5)]
	_ = x[chainHeight-(6)]
	_ = x[blockHeaderNumbersByHash-(7)]
	_ = x[blockHeadersByNumber-(8)]
	_ = x[transactionBlockNumbersAndIndicesByHash-(9)]
	_ = x[transactionsByBlockNumberAndIndex-(10)]
	_ = x[receiptsByBlockNumberAndIndex-(11)]
	_ = x[stateUpdatesByBlockNumber-(12)]
	_ = x[classesTrie-(13)]
	_ = x[contractStorageHistory-(14)]
	_ = x[contractNonceHistory-(15)]
	_ = x[contractClassHashHistory-(16)]
	_ = x[contractDeploymentHeight-(17)]
	_ = x[l1Height-(18)]
	_ = x[deprecatedSchemaVersion-(19)]
	_ = x[unused-(20)]
	_ = x[blockCommitments-(21)]
	_ = x[temporary-(22)]
	_ = x[deprecatedSchemaIntermediateState-(23)]
	_ = x[l1HandlerTxnHashByMsgHash-(24)]
	_ = x[mempoolHead-(25)]
	_ = x[mempoolTail-(26)]
	_ = x[mempoolLength-(27)]
	_ = x[mempoolNode-(28)]
	_ = x[classTrie-(29)]
	_ = x[contractTrieContract-(30)]
	_ = x[contractTrieStorage-(31)]
	_ = x[contract-(32)]
	_ = x[stateHashToTrieRoots-(33)]
	_ = x[stateID-(34)]
	_ = x[persistedStateID-(35)]
	_ = x[trieJournal-(36)]
	_ = x[aggregatedBloomFilters-(37)]
	_ = x[runningEventFilter-(38)]
	_ = x[classCasmHashMetadata-(39)]
	_ = x[blockTransactions-(40)]
	_ = x[schemaMetadata-(41)]
	_ = x[schemaIntermediateState-(42)]
}

var _innerBucketValues = []innerBucket{stateTrie, peer, contractClassHash, contractStorage, class, contractNonce, chainHeight, blockHeaderNumbersByHash, blockHeadersByNumber, transactionBlockNumbersAndIndicesByHash, transactionsByBlockNumberAndIndex, receiptsByBlockNumberAndIndex, stateUpdatesByBlockNumber, classesTrie, contractStorageHistory, contractNonceHistory, contractClassHashHistory, contractDeploymentHeight, l1Height, deprecatedSchemaVersion, unused, blockCommitments, temporary, deprecatedSchemaIntermediateState, l1HandlerTxnHashByMsgHash, mempoolHead, mempoolTail, mempoolLength, mempoolNode, classTrie, contractTrieContract, contractTrieStorage, contract, stateHashToTrieRoots, stateID, persistedStateID, trieJournal, aggregatedBloomFilters, runningEventFilter, classCasmHashMetadata, blockTransactions, schemaMetadata, schemaIntermediateState}

var _innerBucketNameToValueMap = map[string]innerBucket{
	_innerBucketName[0:9]:          stateTrie,
	_innerBucketLowerName[0:9]:     stateTrie,
	_innerBucketName[9:13]:         peer,
	_innerBucketLowerName[9:13]:    peer,
	_innerBucketName[13:30]:        contractClassHash,
	_innerBucketLowerName[13:30]:   contractClassHash,
	_innerBucketName[30:45]:        contractStorage,
	_innerBucketLowerName[30:45]:   contractStorage,
	_innerBucketName[45:50]:        class,
	_innerBucketLowerName[45:50]:   class,
	_innerBucketName[50:63]:        contractNonce,
	_innerBucketLowerName[50:63]:   contractNonce,
	_innerBucketName[63:74]:        chainHeight,
	_innerBucketLowerName[63:74]:   chainHeight,
	_innerBucketName[74:98]:        blockHeaderNumbersByHash,
	_innerBucketLowerName[74:98]:   blockHeaderNumbersByHash,
	_innerBucketName[98:118]:       blockHeadersByNumber,
	_innerBucketLowerName[98:118]:  blockHeadersByNumber,
	_innerBucketName[118:157]:      transactionBlockNumbersAndIndicesByHash,
	_innerBucketLowerName[118:157]: transactionBlockNumbersAndIndicesByHash,
	_innerBucketName[157:190]:      transactionsByBlockNumberAndIndex,
	_innerBucketLowerName[157:190]: transactionsByBlockNumberAndIndex,
	_innerBucketName[190:219]:      receiptsByBlockNumberAndIndex,
	_innerBucketLowerName[190:219]: receiptsByBlockNumberAndIndex,
	_innerBucketName[219:244]:      stateUpdatesByBlockNumber,
	_innerBucketLowerName[219:244]: stateUpdatesByBlockNumber,
	_innerBucketName[244:255]:      classesTrie,
	_innerBucketLowerName[244:255]: classesTrie,
	_innerBucketName[255:277]:      contractStorageHistory,
	_innerBucketLowerName[255:277]: contractStorageHistory,
	_innerBucketName[277:297]:      contractNonceHistory,
	_innerBucketLowerName[277:297]: contractNonceHistory,
	_innerBucketName[297:321]:      contractClassHashHistory,
	_innerBucketLowerName[297:321]: contractClassHashHistory,
	_innerBucketName[321:345]:      contractDeploymentHeight,
	_innerBucketLowerName[321:345]: contractDeploymentHeight,
	_innerBucketName[345:353]:      l1Height,
	_innerBucketLowerName[345:353]: l1Height,
	_innerBucketName[353:376]:      deprecatedSchemaVersion,
	_innerBucketLowerName[353:376]: deprecatedSchemaVersion,
	_innerBucketName[376:382]:      unused,
	_innerBucketLowerName[376:382]: unused,
	_innerBucketName[382:398]:      blockCommitments,
	_innerBucketLowerName[382:398]: blockCommitments,
	_innerBucketName[398:407]:      temporary,
	_innerBucketLowerName[398:407]: temporary,
	_innerBucketName[407:440]:      deprecatedSchemaIntermediateState,
	_innerBucketLowerName[407:440]: deprecatedSchemaIntermediateState,
	_innerBucketName[440:465]:      l1HandlerTxnHashByMsgHash,
	_innerBucketLowerName[440:465]: l1HandlerTxnHashByMsgHash,
	_innerBucketName[465:476]:      mempoolHead,
	_innerBucketLowerName[465:476]: mempoolHead,
	_innerBucketName[476:487]:      mempoolTail,
	_innerBucketLowerName[476:487]: mempoolTail,
	_innerBucketName[487:500]:      mempoolLength,
	_innerBucketLowerName[487:500]: mempoolLength,
	_innerBucketName[500:511]:      mempoolNode,
	_innerBucketLowerName[500:511]: mempoolNode,
	_innerBucketName[511:520]:      classTrie,
	_innerBucketLowerName[511:520]: classTrie,
	_innerBucketName[520:540]:      contractTrieContract,
	_innerBucketLowerName[520:540]: contractTrieContract,
	_innerBucketName[540:559]:      contractTrieStorage,
	_innerBucketLowerName[540:559]: contractTrieStorage,
	_innerBucketName[559:567]:      contract,
	_innerBucketLowerName[559:567]: contract,
	_innerBucketName[567:587]:      stateHashToTrieRoots,
	_innerBucketLowerName[567:587]: stateHashToTrieRoots,
	_innerBucketName[587:594]:      stateID,
	_innerBucketLowerName[587:594]: stateID,
	_innerBucketName[594:610]:      persistedStateID,
	_innerBucketLowerName[594:610]: persistedStateID,
	_innerBucketName[610:621]:      trieJournal,
	_innerBucketLowerName[610:621]: trieJournal,
	_innerBucketName[621:643]:      aggregatedBloomFilters,
	_innerBucketLowerName[621:643]: aggregatedBloomFilters,
	_innerBucketName[643:661]:      runningEventFilter,
	_innerBucketLowerName[643:661]: runningEventFilter,
	_innerBucketName[661:682]:      classCasmHashMetadata,
	_innerBucketLowerName[661:682]: classCasmHashMetadata,
	_innerBucketName[682:699]:      blockTransactions,
	_innerBucketLowerName[682:699]: blockTransactions,
	_innerBucketName[699:713]:      schemaMetadata,
	_innerBucketLowerName[699:713]: schemaMetadata,
	_innerBucketName[713:736]:      schemaIntermediateState,
	_innerBucketLowerName[713:736]: schemaIntermediateState,
}

var _innerBucketNames = []string{
	_innerBucketName[0:9],
	_innerBucketName[9:13],
	_innerBucketName[13:30],
	_innerBucketName[30:45],
	_innerBucketName[45:50],
	_innerBucketName[50:63],
	_innerBucketName[63:74],
	_innerBucketName[74:98],
	_innerBucketName[98:118],
	_innerBucketName[118:157],
	_innerBucketName[157:190],
	_innerBucketName[190:219],
	_innerBucketName[219:244],
	_innerBucketName[244:255],
	_innerBucketName[255:277],
	_innerBucketName[277:297],
	_innerBucketName[297:321],
	_innerBucketName[321:345],
	_innerBucketName[345:353],
	_innerBucketName[353:376],
	_innerBucketName[376:382],
	_innerBucketName[382:398],
	_innerBucketName[398:407],
	_innerBucketName[407:440],
	_innerBucketName[440:465],
	_innerBucketName[465:476],
	_innerBucketName[476:487],
	_innerBucketName[487:500],
	_innerBucketName[500:511],
	_innerBucketName[511:520],
	_innerBucketName[520:540],
	_innerBucketName[540:559],
	_innerBucketName[559:567],
	_innerBucketName[567:587],
	_innerBucketName[587:594],
	_innerBucketName[594:610],
	_innerBucketName[610:621],
	_innerBucketName[621:643],
	_innerBucketName[643:661],
	_innerBucketName[661:682],
	_innerBucketName[682:699],
	_innerBucketName[699:713],
	_innerBucketName[713:736],
}

// innerBucketString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func innerBucketString(s string) (innerBucket, error) {
	if val, ok := _innerBucketNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _innerBucketNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to innerBucket values", s)
}

// innerBucketValues returns all values of the enum
func innerBucketValues() []innerBucket {
	return _innerBucketValues
}

// innerBucketStrings returns a slice of all String values of the enum
func innerBucketStrings() []string {
	strs := make([]string, len(_innerBucketNames))
	copy(strs, _innerBucketNames)
	return strs
}

// IsAinnerBucket returns "true" if the value is listed in the enum definition. "false" otherwise
func (i innerBucket) IsAinnerBucket() bool {
	for _, v := range _innerBucketValues {
		if i == v {
			return true
		}
	}
	return false
}
