name: Benchmark Sync

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" # Every Sunday at midnight UTC

permissions:
  contents: read
  id-token: write

env:
  DOCKER_REGISTRY: nethermind.jfrog.io
  IMAGE_REPO: nubia-oci-local-dev/juno
  BENCHMARK_TAG: nubia-oci-local-dev/juno-benchmark:latest

jobs:
  sync-benchmark:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Extract Git version
        id: extract_version
        run: echo "version=$(git describe --tags)" >> $GITHUB_OUTPUT

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@37fe631027851001ddb9b187196cc803df7f5f0e # v4.3.0
        id: buildx

      - name: Install JFrog CLI
        id: jfrog
        uses: jfrog/setup-jfrog-cli@deda456d982fc5e9a7a020b63eb0d2968aedd33e # v5.1.0
        env:
          JF_URL: https://${{ env.DOCKER_REGISTRY }}
        with:
          oidc-provider-name: github-nethermindeth

      - name: Login to Registry with OIDC
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ steps.jfrog.outputs.oidc-user }}
          password: ${{ steps.jfrog.outputs.oidc-token }}

      - name: Create benchmark tag
        run: docker buildx imagetools create -t ${{ env.DOCKER_REGISTRY }}/${{ env.BENCHMARK_TAG }} ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_REPO }}:${{ steps.extract_version.outputs.version }}
