name: CI/CD
on:
  push:
    branches: [mario/local-artifactory]
    tags: ['v*']
  workflow_dispatch:
permissions:
  id-token: write
  contents: write
jobs:
  prepare_dummy_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Define docker image tag
        id: image_tag
        run: |
          echo "DOCKER_IMAGE_TAG=nethermind.jfrog.io/angkor-docker-local-dev/juno:v0.0.0-test" >> $GITHUB_ENV
          echo "IMAGE_TAG=${DOCKER_IMAGE_TAG} >> $GITHUB_OUTPUT"
      - name: Login to Artifactory Docker registry
        run: |
          docker login nethermind.jfrog.io -u antoni.tomaszuk@nethermind.io -p ${{ secrets.ARTIFACTORY_ANGKOR_CONTRIBUTOR }}
        
      - name: Build dummy Docker image
        run: |
          echo -e "FROM busybox\nCMD echo 'This is a dummy image'" > Dockerfile
          docker build -t ${{ env.DOCKER_IMAGE_TAG }} .
          docker save -o /tmp/juno_image.tar ${{ env.DOCKER_IMAGE_TAG }}
      - name: Upload Docker image to dev artifactory
        run: |
          docker push ${{ env.DOCKER_IMAGE_TAG }}
