name: Docker Build and Deploy to Dev

on:
  push:
    branches: [main,wojciechos/local_artifactory]
    tags: ['v*']
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  docker_build_and_publish:
    runs-on: ubuntu-latest
    outputs:
      IMAGE_TAG: ${{ steps.image_tag.outputs.IMAGE_TAG }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Define_docker_image_tag
        id: image_tag
        run: |
          echo "DOCKER_IMAGE_TAG=$(git describe --tags)" >> $GITHUB_ENV
          echo "IMAGE_TAG=$(git describe --tags)" >> "$GITHUB_OUTPUT"
      
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: 'linux/amd64'
          push: false
          tags: juno:${{ env.DOCKER_IMAGE_TAG }}
          outputs: type=docker,dest=/tmp/juno_image.tar

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ secrets.JFROG_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.ARTIFACTORY_ANGKOR_CONTRIBUTOR }}

      - name: Push to Artifactory Dev
        run: |
          set -e
          jf rt docker-push ${env.DOCKER_IMAGE_TAG} angkor-docker-local-dev --url=${env.JF_URL} --build-name=juno --build-number=${github.run_number} --insecure-tls
          jf rt build-publish juno ${{ github.run_number }} --url=${{ secrets.JFROG_URL }} --insecure-tls
        env:
          JFROG_CLI_LOG_LEVEL: DEBUG
    
  deploy_to_dev:
    needs: [docker_build_and_publish]
    runs-on: ubuntu-latest
    environment: 
      name: Development
    steps:
      - name: Verify Deployment Version (Dev)
        run: bash .github/workflow-scripts/verify_deployment.sh ${{ secrets.DEV_SEPOLIA_URL }} ${{ needs.docker_build_and_publish.outputs.IMAGE_TAG }}        
        
  dev-starknet-rs-tests:
    needs: [deploy_to_dev]
    uses: ./.github/workflows/starknet-rs-tests.yml
    secrets:
      STARKNET_RPC: ${{ secrets.DEV_SEPOLIA_URL }}/v0_6
      
  dev-starknet-js-tests:
    needs: [deploy_to_dev]
    uses: ./.github/workflows/starknet-js-tests.yml
    secrets:
      TEST_RPC_URL: ${{ secrets.DEV_SEPOLIA_URL }}/v0_7
      TEST_ACCOUNT_ADDRESS: ${{ secrets.TEST_ACCOUNT_ADDRESS }}
      TEST_ACCOUNT_PRIVATE_KEY: ${{ secrets.TEST_ACCOUNT_PRIVATE_KEY }}