name: Dispatch Render Juno-Dev

on:
    workflow_dispatch:
      inputs:
        tag:
          description: Image tag 
          required: true
    push:
      branches:
        - juno-staging-gitaction
env: 
    EVENT_NAME: juno-staging
    GOERLI: apps/juno-staging/overlays/staging-goerli-1/config.yaml
    GOERLI2: apps/juno-staging/overlays/staging-goerli-2/config.yaml
    TESTNET: apps/juno-staging/overlays/staging-integration/config.yaml
    MAINNET: apps/juno-staging/overlays/staging-mainnet/config.yaml

permissions:
    id-token: write
    contents: write

jobs:
    deploy:
        environment: staging
        runs-on: ubuntu-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v3
        
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        
        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Build, tag and push image
          env:
            IMAGE_TAG: ${{ github.event.inputs.tag }}
          id: build-image
          uses: docker/build-push-action@v4
          with:
            context: .
            push: true
            platforms: 'linux/amd64'
            tags: nethermind/juno:${{env.IMAGE_TAG}}
        
        - name: Repository Dispatch
          env:
            IMAGE_TAG: ${{ github.event.inputs.tag }}
          uses: peter-evans/repository-dispatch@v2
          with: 
            token: ${{ secrets.ACCESS_TOKEN }}
            repository: NethermindEth/argo
            event-type: ${{ env.EVENT_NAME }}
            client-payload: '{"name": "${{ env.EVENT_NAME }}", "goerli_config": "${{ env.GOERLI }}", "goerli2_config": "${{ env.GOERLI2 }}", "testnet_config": "${{ env.TESTNET }}", "mainnet_config": "${{ env.MAINNET }}", "tag": "${{ env.IMAGE_TAG }}"}'


