name: Dispatch Render Juno-Dev

on:
  push:
    branches:
      - main
    
env: 
    EVENT_NAME: juno-dev
    GOERLI: apps/juno-dev/overlays/dev-goerli-1/config.yaml
    GOERLI2: apps/juno-dev/overlays/dev-goerli-2/config.yaml
    TESTNET: apps/juno-dev/overlays/dev-integration/config.yaml
    MAINNET: apps/juno-dev/overlays/dev-mainnet/config.yaml

permissions:
    id-token: write
    contents: write

jobs:
    deploy:
        environment: development
        runs-on: ubuntu-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            fetch-depth: 0
        
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        
        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Build, tag and push image
          env:
            IMAGE_TAG: ${{ }}
          uses: docker/build-push-action@v4
          with:
            context: .
            push: true
            platforms: 'linux/amd64'
            tags: nethermindeth/juno:${{env.IMAGE_TAG}}
        
        
        - name: Repository Dispatch
          env:
            IMAGE_TAG: 
          run: |
            curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.ACCESS_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/NethermindEth/argo/dispatches \
            -d '{"event_type": "${{ env.EVENT_NAME }}", "client-payload":{"name": "${{ env.EVENT_NAME }}", "goerli_config": "${{ env.GOERLI }}", "goerli2_config": "${{ env.GOERLI2 }}", "testnet_config": "${{ env.TESTNET }}", "mainnet_config": "${{ env.MAINNET }}", "tag": "${{ env.IMAGE_TAG }}"}}'
            
