name: CI/CD
on:
  push:
    branches: [main,wojciechos/local_artifactory]
    tags: ['v*']
  workflow_dispatch:
permissions:
  id-token: write
  contents: write
jobs:
  prepare_dummy_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Define docker image tag
        id: image_tag
        run: |
          echo "DOCKER_IMAGE_TAG=angkor-docker-virtual-dev:v0.0.0-juno" >> $GITHUB_ENV
          echo "IMAGE_TAG=${DOCKER_IMAGE_TAG} >> $GITHUB_OUTPUT"
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        with:
          version: 2.59.0
        env:
          JF_URL: ${{ vars.JFROG_URL }}
          ARTIFACTORY_URL: ${{vars.ARTIFACTORY_URL}}
          JF_ACCESS_TOKEN: ${{ secrets.ARTIFACTORY_ANGKOR_CONTRIBUTOR }}
      - name: Login to Artifactory Docker registry
        run: |
          jfrog docker login
        
      - name: Build dummy Docker image
        run: |
          echo -e "FROM busybox\nCMD echo 'This is a dummy image'" > Dockerfile
          docker build -t ${{ env.DOCKER_IMAGE_TAG }} .
          docker save -o /tmp/juno_image.tar juno:${{ env.DOCKER_IMAGE_TAG }}
      - name: Upload Docker image to dev artifactory
        run: |
          jfrog docker push nethermind.jfrog.io/${{ env.DOCKER_IMAGE_TAG }}