name: CI/CD

on:
  push:
    branches: [wojciechos/local_artifactory]
    tags: ['v*']
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:

  docker_build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Define docker image tag
        id: image_tag
        run: |
          echo "DOCKER_IMAGE_TAG=https://nethermind.jfrog.io/angkor-docker-local-dev/juno:$(git describe --tags)" >> $GITHUB_ENV
          echo "IMAGE_TAG=$(git describe --tags)" >> "$GITHUB_OUTPUT"

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Artifactory Docker registry
        run: |
          docker login https://nethermind.jfrog.io -u antoni.tomaszuk@nethermind.io -p ${{ secrets.ARTIFACTORY_ANGKOR_CONTRIBUTOR }}
      
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: 'linux/amd64'
          push: true
          tags: ${{ env.DOCKER_IMAGE_TAG }}

  validate_dev:
    needs: [docker_build_and_publish]
    runs-on: ubuntu-latest
    environment: 
      name: Development
    steps:
      - name: Verify Deployment Version (Dev)
        run: bash .github/workflow-scripts/verify_deployment.sh ${{ secrets.DEV_SEPOLIA_URL }} ${{ needs.docker_build_and_publish.outputs.IMAGE_TAG }}        
        
  dev-starknet-rs-tests:
    needs: [validate_dev]
    uses: ./.github/workflows/starknet-rs-tests.yml
    secrets:
      STARKNET_RPC: ${{ secrets.DEV_SEPOLIA_URL }}/v0_6
      
  dev-starknet-js-tests:
    needs: [validate_dev]
    uses: ./.github/workflows/starknet-js-tests.yml
    secrets:
      TEST_RPC_URL: ${{ secrets.DEV_SEPOLIA_URL }}/v0_7
      TEST_ACCOUNT_ADDRESS: ${{ secrets.TEST_ACCOUNT_ADDRESS }}
      TEST_ACCOUNT_PRIVATE_KEY: ${{ secrets.TEST_ACCOUNT_PRIVATE_KEY }}
  
  promote_to_staging:
    needs: [docker_build_and_publish, validate_dev]
    runs-on: ubuntu-latest
    environment: 
      name: Staging
    steps:         
    - name: Setup JFrog CLI
      uses: jfrog/setup-jfrog-cli@v4
      env:
        JF_URL: ${{ vars.JFROG_URL}}
        JF_ACCESS_TOKEN: ${{ secrets.ARTIFACTORY_ANGKOR_CONTRIBUTOR }}

    - name: Copy image to staging artifactory
      run: |
        jfrog rt cp ${{ env.DOCKER_IMAGE_TAG }} "nethermind.jfrog.io/angkor-docker-local-staging/juno:${{ needs.docker_build_and_publish.outputs.IMAGE_TAG}}"
    
    - name: Verify Deployment Version (Staging)
      run: bash .github/workflow-scripts/verify_deployment.sh ${{ secrets.STAGING_SEPOLIA_URL }} ${{ needs.docker_build_and_publish.outputs.IMAGE_TAG }}

  staging-starknet-rs-tests:
    needs: [promote_to_staging]
    uses: ./.github/workflows/starknet-rs-tests.yml
    secrets:
      STARKNET_RPC: ${{ secrets.STAGING_SEPOLIA_URL }}/v0_6

  staging-starknet-js-tests:
    needs: [promote_to_staging]
    uses: ./.github/workflows/starknet-js-tests.yml
    secrets:
      TEST_RPC_URL: ${{ secrets.STAGING_SEPOLIA_URL }}/v0_7
      TEST_ACCOUNT_ADDRESS: ${{ secrets.TEST_ACCOUNT_ADDRESS }}
      TEST_ACCOUNT_PRIVATE_KEY: ${{ secrets.TEST_ACCOUNT_PRIVATE_KEY }}
  
  promote_to_prod:
    needs: [docker_build_and_publish, promote_to_staging]
    runs-on: ubuntu-latest
    environment: 
      name: Prod
    steps:         
    - name: Setup JFrog CLI
      uses: jfrog/setup-jfrog-cli@v4
      env:
        JF_URL: ${{ vars.JFROG_URL}}
        JF_ACCESS_TOKEN: ${{ secrets.ARTIFACTORY_ANGKOR_CONTRIBUTOR }}

    - name: Copy image to staging artifactory
      run: |
        jfrog rt cp "angkor-docker-local-staging/juno:${{ env.DOCKER_IMAGE_TAG }}" "angkor-docker-local-prod/juno:${{ env.DOCKER_IMAGE_TAG }}"
    
    - name: Verify Deployment Version (Staging)
      run: bash .github/workflow-scripts/verify_deployment.sh ${{ secrets.STAGING_SEPOLIA_URL }} ${{ needs.docker_build_and_publish.outputs.IMAGE_TAG }}