name: Promote to Staging and Test

on:
  workflow_dispatch:
    inputs:
      docker_image_tag:
        description: 'Docker image tag from Dev to promote'
        required: true
        type: string
      rpc_version:
        description: 'RPC version for tests (e.g., v0_7)'
        required: true
        default: 'v0_7'
        type: string

permissions:
  contents: read

concurrency:
  group: shared_staging_environment
  cancel-in-progress: false

env:
  DOCKER_REGISTRY: nethermind.jfrog.io
  REPO_DEV: nubia-oci-local-dev
  REPO_STAGING: nubia-oci-local-staging

jobs:
  promote_to_staging:
    runs-on: ubuntu-latest
    environment:
      name: Staging
    steps:
      - uses: actions/checkout@v4
      - uses: oras-project/setup-oras@v1

      - name: Login to registry
        run: |
          oras login ${{ env.DOCKER_REGISTRY }} \
            -u ${{ secrets.ARTIFACTORY_NUBIA_USERNAME }} \
            -p ${{ secrets.ARTIFACTORY_NUBIA_TOKEN_DEVELOPER }}

      - name: Check image exists in Dev
        run: |
          oras manifest fetch \
          ${{ env.DOCKER_REGISTRY }}/${{ env.REPO_DEV }}/juno:${{ inputs.docker_image_tag }} || \
          (echo "❌ Image not found in Dev!" && exit 1)

      - name: Promote image to Staging
        run: |
          oras cp -r \
          ${{ env.DOCKER_REGISTRY }}/${{ env.REPO_DEV }}/juno:${{ inputs.docker_image_tag }} \
          ${{ env.DOCKER_REGISTRY }}/${{ env.REPO_STAGING }}/juno:latest, ${{ inputs.docker_image_tag }}

      - name: Verify Deployment Version (Staging)
        run: |
          bash .github/workflow-scripts/verify_deployment.sh \
            ${{ secrets.STAGING_SEPOLIA_URL }} \
            ${{ inputs.docker_image_tag }}

  starknet-rs-tests:
    needs: [promote_to_staging]
    uses: ./.github/workflows/starknet-rs-tests.yml
    secrets:
      STARKNET_RPC: ${{ secrets.STAGING_SEPOLIA_URL }}/${{ inputs.rpc_version }}

  starknet-js-tests:
    needs: [promote_to_staging]
    uses: ./.github/workflows/starknet-js-tests.yml
    secrets:
      TEST_RPC_URL: ${{ secrets.STAGING_SEPOLIA_URL }}/${{ inputs.rpc_version }}
      TEST_ACCOUNT_ADDRESS: ${{ secrets.TEST_ACCOUNT_ADDRESS }}
      TEST_ACCOUNT_PRIVATE_KEY: ${{ secrets.TEST_ACCOUNT_PRIVATE_KEY }}

  starknet-go-tests:
    needs: [promote_to_staging]
    uses: ./.github/workflows/starknet-go-tests.yml
    secrets:
      TEST_RPC_URL: ${{ secrets.STAGING_SEPOLIA_URL }}/${{ inputs.rpc_version }}