name: deploy to Production

on:
    workflow_call:
        inputs:
            IMAGE_TAG: 
                required: true
                type: string
            EVENT_NAME: 
                    required: true
                    type: string
            GOERLI: 
                    required: true
                    type: string
            INTEGRATION: 
                    required: true
                    type: string
            MAINNET: 
                    required: true
                    type: string
    
jobs:
    deployments:
      permissions:
        id-token: write
        contents: write
      runs-on: ubuntu-latest
      environment: 
        name: Production
      steps:
          - name: Repository Dispatch Production
            env:
              EVENT_NAME: ${{ inputs.EVENT_NAME }}
              IMAGE_TAG: ${{ inputs.IMAGE_TAG }}
              GOERLI: ${{ inputs.GOERLI }}
              INTEGRATION: ${{ inputs.INTEGRATION }}
              MAINNET: ${{ inputs.MAINNET }}
            run: |
              curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: token ${{ secrets.ACCESS_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/NethermindEth/argo/dispatches \
              -d '{"event_type": "${{ env.EVENT_NAME }}", "client_payload":{"name": "${{ env.EVENT_NAME }}", "goerli_config": "${{ env.GOERLI }}", "integration_config": "${{ env.INTEGRATION }}", "mainnet_config": "${{ env.MAINNET }}", "tag": "${{ env.IMAGE_TAG }}"}}'
    

   