name: Dev Environment Pipeline

on:
  workflow_call:
    outputs:
      docker_image_tag:
        description: "The Docker image tag that was deployed"
        value: ${{ jobs.build.outputs.DOCKER_IMAGE_TAG }}
    inputs:
      rpc_version:
        required: false
        type: string
        default: "v0_7"
    secrets:
      ARTIFACTORY_NUBIA_USERNAME:
        required: true
      ARTIFACTORY_NUBIA_TOKEN_DEVELOPER:
        required: true
      DEV_SEPOLIA_URL:
        required: true
      TEST_ACCOUNT_ADDRESS:
        required: true
      TEST_ACCOUNT_PRIVATE_KEY:
        required: true

permissions:
  contents: read  

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DOCKER_REGISTRY: nethermind.jfrog.io
  REPO_DEV: nubia-oci-local-dev

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      DOCKER_IMAGE_TAG: ${{ steps.set_tag.outputs.DOCKER_IMAGE_TAG }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Define image tag
        id: set_tag
        run: |
          export DOCKER_IMAGE_TAG=$(git describe --tags)
          echo "DOCKER_IMAGE_TAG=$DOCKER_IMAGE_TAG" >> $GITHUB_ENV
          echo "DOCKER_IMAGE_TAG=$DOCKER_IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2

      - name: Login to registry
        run: |
          docker login ${{ env.DOCKER_REGISTRY }} -u ${{ secrets.ARTIFACTORY_NUBIA_USERNAME }} -p ${{ secrets.ARTIFACTORY_NUBIA_TOKEN_DEVELOPER }}

      - name: Build Docker Image
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4
        with:
          context: .
          platforms: "linux/amd64"
          push: true
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ env.REPO_DEV }}/juno:${{ env.DOCKER_IMAGE_TAG }}

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    concurrency:
      group: shared_dev_environment
      cancel-in-progress: false
    environment:
      name: Development
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2
        id: buildx

      - name: Login to registry
        run: |
          docker login ${{ env.DOCKER_REGISTRY }} -u ${{ secrets.ARTIFACTORY_NUBIA_USERNAME }} -p ${{ secrets.ARTIFACTORY_NUBIA_TOKEN_DEVELOPER }}

      - name: Pull image and push it as latest
        run: |
          OLD_TAG=${{ env.DOCKER_REGISTRY }}/${{ env.REPO_DEV }}/juno:${{ needs.build.outputs.DOCKER_IMAGE_TAG }}
          NEW_TAG=${{ env.DOCKER_REGISTRY }}/${{ env.REPO_DEV }}/juno:latest
          docker buildx imagetools create -t $NEW_TAG $OLD_TAG
            
      - name: Verify Deployment Version (Dev)
        run: |
          bash .github/workflow-scripts/verify_deployment.sh ${{ secrets.DEV_SEPOLIA_URL }} ${{ needs.build.outputs.DOCKER_IMAGE_TAG }}

  starknet-rs:
    concurrency:
      group: shared_dev_environment
      cancel-in-progress: false 
    needs: [deploy]
    uses: ./.github/workflows/starknet-rs-tests.yml
    secrets:
      STARKNET_RPC: ${{ secrets.DEV_SEPOLIA_URL }}/${{ inputs.rpc_version }}

  starknet-js:
    concurrency:
      group: shared_dev_environment
      cancel-in-progress: false 
    needs: [deploy]
    uses: ./.github/workflows/starknet-js-tests.yml
    secrets:
      TEST_RPC_URL: ${{ secrets.DEV_SEPOLIA_URL }}/${{ inputs.rpc_version }}
      TEST_ACCOUNT_ADDRESS: ${{ secrets.TEST_ACCOUNT_ADDRESS }}
      TEST_ACCOUNT_PRIVATE_KEY: ${{ secrets.TEST_ACCOUNT_PRIVATE_KEY }}

  starknet-go:
    concurrency:
      group: shared_dev_environment
      cancel-in-progress: false 
    needs: [deploy]
    uses: ./.github/workflows/starknet-go-tests.yml
    secrets:
      TEST_RPC_URL: ${{ secrets.DEV_SEPOLIA_URL }}/${{ inputs.rpc_version }}
