name: Dev Deploy and Test

on:
  workflow_call:
    inputs:
      docker_image_tag:
        required: true
        type: string
        description: "The Docker image tag to deploy"
      rpc_version:
        required: false
        type: string
        default: "v0_7"
    secrets:
      ARTIFACTORY_NUBIA_USERNAME:
        required: true
      ARTIFACTORY_NUBIA_TOKEN_DEVELOPER:
        required: true
      DEV_SEPOLIA_URL:
        required: true
      TEST_ACCOUNT_ADDRESS:
        required: true
      TEST_ACCOUNT_PRIVATE_KEY:
        required: true

concurrency:
    group: shared_dev_environment
    cancel-in-progress: false 
    
permissions:
  contents: read  

env:
  DOCKER_REGISTRY: nethermind.jfrog.io
  REPO_DEV: nubia-oci-local-dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: Development
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2
        id: buildx

      - name: Login to registry
        run: |
          docker login ${{ env.DOCKER_REGISTRY }} -u ${{ secrets.ARTIFACTORY_NUBIA_USERNAME }} -p ${{ secrets.ARTIFACTORY_NUBIA_TOKEN_DEVELOPER }}

      - name: Pull image and push it as latest
        run: |
          OLD_TAG=${{ env.DOCKER_REGISTRY }}/${{ env.REPO_DEV }}/juno:${{ inputs.docker_image_tag }}
          NEW_TAG=${{ env.DOCKER_REGISTRY }}/${{ env.REPO_DEV }}/juno:latest
          docker buildx imagetools create -t $NEW_TAG $OLD_TAG
            
      - name: Verify Deployment Version (Dev)
        run: |
          bash .github/workflow-scripts/verify_deployment.sh ${{ secrets.DEV_SEPOLIA_URL }} ${{ inputs.docker_image_tag }}

  starknet-rs:
    needs: [deploy]
    uses: ./.github/workflows/starknet-rs-tests.yml
    secrets:
      STARKNET_RPC: ${{ secrets.DEV_SEPOLIA_URL }}/${{ inputs.rpc_version }}

  starknet-js:
    needs: [deploy]
    uses: ./.github/workflows/starknet-js-tests.yml
    secrets:
      TEST_RPC_URL: ${{ secrets.DEV_SEPOLIA_URL }}/${{ inputs.rpc_version }}
      TEST_ACCOUNT_ADDRESS: ${{ secrets.TEST_ACCOUNT_ADDRESS }}
      TEST_ACCOUNT_PRIVATE_KEY: ${{ secrets.TEST_ACCOUNT_PRIVATE_KEY }}

  starknet-go:
    needs: [deploy]
    uses: ./.github/workflows/starknet-go-tests.yml
    secrets:
      TEST_RPC_URL: ${{ secrets.DEV_SEPOLIA_URL }}/${{ inputs.rpc_version }} 