name: Dev Environment Pipeline

on:
  workflow_call:
    outputs:
      docker_image_tag:
        description: "The Docker image tag that was deployed"
        value: ${{ jobs.build.outputs.DOCKER_IMAGE_TAG }}
    secrets:
      ARTIFACTORY_NUBIA_USERNAME:
        required: true
      ARTIFACTORY_NUBIA_TOKEN_DEVELOPER:
        required: true
      DEV_SEPOLIA_URL:
        required: true
      TEST_ACCOUNT_ADDRESS:
        required: true
      TEST_ACCOUNT_PRIVATE_KEY:
        required: true

env:
  DOCKER_REGISTRY: nethermind.jfrog.io
  REPO_DEV: nubia-oci-local-dev

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      DOCKER_IMAGE_TAG: ${{ steps.set_tag.outputs.DOCKER_IMAGE_TAG }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Define image tag
        id: set_tag
        run: |
          export DOCKER_IMAGE_TAG=$(git describe --tags)
          echo "DOCKER_IMAGE_TAG=$DOCKER_IMAGE_TAG" >> $GITHUB_ENV
          echo "DOCKER_IMAGE_TAG=$DOCKER_IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: "linux/amd64"
          push: false
          outputs: type=docker,dest=/tmp/juno-image.tar

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: juno-image
          path: /tmp/juno-image.tar
          retention-days: 1

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    concurrency:
      group: shared_dev_environment
      cancel-in-progress: false
    environment:
      name: Development
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: juno-image
          path: /tmp

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        id: buildx

      - name: Login to registry
        run: |
          docker login ${{ env.DOCKER_REGISTRY }} -u ${{ secrets.ARTIFACTORY_NUBIA_USERNAME }} -p ${{ secrets.ARTIFACTORY_NUBIA_TOKEN_DEVELOPER }}
          echo "Testing login:" && docker push ${{ env.DOCKER_REGISTRY }}/${{ env.REPO_DEV }}/juno:latest --dry-run || echo "Login failed"

      - name: Load and Push
        run: |
          docker load --input /tmp/juno-image.tar
          echo "Loaded image ID: $(docker images -q | head -n 1)"
          docker tag $(docker images -q | head -n 1) ${{ env.DOCKER_REGISTRY }}/${{ env.REPO_DEV }}/juno:${{ needs.build.outputs.DOCKER_IMAGE_TAG }}
          docker tag $(docker images -q | head -n 1) ${{ env.DOCKER_REGISTRY }}/${{ env.REPO_DEV }}/juno:latest
          docker push ${{ env.DOCKER_REGISTRY }}/${{ env.REPO_DEV }}/juno:latest
          docker push ${{ env.DOCKER_REGISTRY }}/${{ env.REPO_DEV }}/juno:${{ needs.build.outputs.DOCKER_IMAGE_TAG }}
            
      - name: Verify Deployment Version (Dev)
        run: |
          bash .github/workflow-scripts/verify_deployment.sh ${{ secrets.DEV_SEPOLIA_URL }} ${{ needs.build.outputs.DOCKER_IMAGE_TAG }}

  starknet-rs:
    needs: [deploy]
    uses: ./.github/workflows/starknet-rs-tests.yml
    secrets:
      STARKNET_RPC: ${{ secrets.DEV_SEPOLIA_URL }}/v0_7

  starknet-js:
    needs: [deploy]
    uses: ./.github/workflows/starknet-js-tests.yml
    secrets:
      TEST_RPC_URL: ${{ secrets.DEV_SEPOLIA_URL }}/v0_7
      TEST_ACCOUNT_ADDRESS: ${{ secrets.TEST_ACCOUNT_ADDRESS }}
      TEST_ACCOUNT_PRIVATE_KEY: ${{ secrets.TEST_ACCOUNT_PRIVATE_KEY }}

  starknet-go:
    needs: [deploy]
    uses: ./.github/workflows/starknet-go-tests.yml
    secrets:
      TEST_RPC_URL: ${{ secrets.DEV_SEPOLIA_URL }}/v0_7 