name: Dispatch Render Juno-Dev

on:
    workflow_dispatch
env: 
    EVENT_NAME: juno-dev
    VALUES1_FILE: apps/juno-node/overlays/dev-goerli-1/config.yaml
    VALUES2_FILE: apps/juno-node/overlays/dev-goerli-2/config.yaml
    VALUES3_FILE: apps/juno-node/overlays/dev-integration/config.yaml
    VALUES4_FILE: apps/juno-node/overlays/dev-mainnet/config.yaml

permissions:
    id-token: write
    contents: write

jobs:
    deploy:
        environment: development
        runs-on: ubuntu-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v3
        
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        
        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}

        - name: Build, tag and push image
          env:
            IMAGE_TAG: ${{ github.sha }}
          id: build-image
          uses: docker/build-push-action@v4
          with:
            context: .
            push: true
            tags: nethermind/juno:$IMAGE_TAG
        
        - name: Repository Dispatch
          env:
            IMAGE_TAG: ${{ github.sha }}
            EVENT_NAME: ${{ env.EVENT_NAME }}
            VALUES1_FILE: ${{ env.VALUES_FILE }}
            VALUES2_FILE: ${{ env.VALUES_FILE }}
            VALUES3_FILE: ${{ env.VALUES_FILE }}
            VALUES4_FILE: ${{ env.VALUES_FILE }}
            ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

          run: |
            curl -H "Authorization: token ${{ secrets.ACCESS_TOKEN }}" \
            --request POST \
            --data '{"event_type": "'"$EVENT_NAME"'", "client_payload": {"name": "'"$EVENT_NAME"'", "file1_path": "'"$VALUES1_FILE"'", "file2_path": "'"$VALUES2_FILE"'", "file3_path": "'"$VALUES3_FILE"'", "file4_path": "'"$VALUES4_FILE"'", "tag": "'"$IMAGE_TAG"'"}}' \
            https://api.github.com/repos/NethermindEth/argo/dispatches