name: Dispatch Render Juno-Dev

on:
    # workflow_dispatch
    push:
      branches:
        - juno-dev-gitaction
env: 
    EVENT_NAME: juno-dev
    VALUES1_FILE: apps/juno-node/overlays/dev-goerli-1/config.yaml
    VALUES2_FILE: apps/juno-node/overlays/dev-goerli-2/config.yaml
    VALUES3_FILE: apps/juno-node/overlays/dev-integration/config.yaml
    VALUES4_FILE: apps/juno-node/overlays/dev-mainnet/config.yaml

permissions:
    id-token: write
    contents: write

jobs:
    deploy:
        environment: development
        runs-on: ubuntu-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v3
        
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        
        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Build, tag and push image
          env:
            IMAGE_TAG: ${{ github.sha }}
          id: build-image
          uses: docker/build-push-action@v4
          with:
            context: .
            push: true
            platforms: 'linux/amd64'
            tags: nethermind/juno:${{env.IMAGE_TAG}}
        
        - name: Repository Dispatch
          env:
            IMAGE_TAG: ${{ github.sha }}
            EVENT_NAME: ${{ env.EVENT_NAME }}
            VALUES1_FILE: ${{ env.VALUES1_FILE }}
            VALUES2_FILE: ${{ env.VALUES2_FILE }}
            VALUES3_FILE: ${{ env.VALUES3_FILE }}
            VALUES4_FILE: ${{ env.VALUES4_FILE }}
            ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

          run: |
            curl -v -L \
            -X POST \
            -H "Authorization: Bearer $ACCESS_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/NethermindEth/argo/dispatches \
            --data '{"event_type": "${{ env.EVENT_NAME }}", "client_payload": {"name": "${{ env.EVENT_NAME }}", "file1_path": "${{ env.VALUES1_FILE }}", "file2_path": "${{ env.VALUES2_FILE }}", "file3_path": "${{ env.VALUES3_FILE }}", "file4_path": "${{ env.VALUES4_FILE }}", "tag": "${{ env.IMAGE_TAG }}"}}'
