name: 'Docker Image CI'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-dockers:
    if: github.repository_owner == 'NethermindEth'
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository
        uses: actions/checkout@v2
      - name: Settings
        id: settings
        run: |
          echo ::set-output name=docker_username::${{ secrets.DOCKER_USERNAME }}
          echo ::set-output name=docker_image::nethermindeth/juno
          echo ::set-output name=dockerfile::Dockerfile
          echo ::set-output name=TAG::$(date +%s)
      - name: Setting up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Logging to Docker Hub
        if: success()
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login --username "${{ steps.settings.outputs.docker_username }}" --password-stdin
      - name: Building image
        run: |
          docker buildx build --platform=linux/amd64,linux/arm64 -t "${{ steps.settings.outputs.docker_image }}:latest" -t "${{ steps.settings.outputs.docker_image }}:${{ steps.settings.outputs.TAG }}" -f ${{ steps.settings.outputs.dockerfile }} .
      - name: Pushing image to Docker Hub
        run : |
          docker push "${{ steps.settings.outputs.docker_image }}:latest"
          docker push "${{ steps.settings.outputs.docker_image }}:${{ steps.settings.outputs.TAG }}"
      - name: Clearing
        if: always()
        run: |
          rm -f ${HOME}/.docker/config.json
