name: Docker Build and Publish AMD

on:
  workflow_call:

jobs:
  build_and_push_amd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push AMD image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: 'linux/amd64'
          push: true
          tags: nethermindeth/juno:${{ github.ref }}

      - name: Set Output
        id: set_output
        run: echo "AMD_IMAGE_TAG=${{ github.ref }}" >> $GITHUB_ENV

    outputs:
      AMD_IMAGE_TAG: ${{ steps.set_output.outputs.AMD_IMAGE_TAG }}
