name: Docs Staging Test

on: 
  pull_request:
    branches: "staging"

jobs:
  build:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Test Build
        env:
          TARGET_URL: "https://nethermindeth.github.io"
          BASE_URL: "/juno/"
        run: |
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
          npm run build
