name: Juno Test
on:
  push:
    branches:
      - main
      - develop
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run Tests
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, ubuntu-arm64-4-core]
    runs-on: ${{ matrix.os }}
    env:
      VM_DEBUG: true
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Set up go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.0.0
        with:
          go-version-file: go.mod
      - uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable
        with:
          toolchain: "1.88.0"

      - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2.8.1
        with:
          key: rust-toolchain-${{ matrix.os }}
          workspaces: |
            vm/rust
            starknet/compiler/rust

      - name: Install deps
        run: make install-deps

      - name: Install Jemalloc (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get update -qq && sudo apt-get install -y libjemalloc-dev libjemalloc2 libbz2-dev

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: brew install jemalloc

      - name: Tests (Coverage)
        if: matrix.os == 'ubuntu-latest'
        run: make test-cover

      - name: Tests (No Coverage)
        if: matrix.os != 'ubuntu-latest'
        run: make test

      #    Tests with race condition detector are flaky; we're disabling them for now
      #      - name: Tests (Race Detection)
      #        if: matrix.os == 'ubuntu-latest'
      #        run: make test-race

      - name: Upload coverage to Codecov
        if: matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          files: coverage/coverage.old.out,coverage/coverage.new.out
