name: publish docker

on:
  release:
    types: [published]

jobs:
  retag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Retag and push Docker images
      run: |
        VERSION_TAG=${{ github.event.release.tag_name }}
        DRAFT_IMAGE="nethermindeth/juno:${VERSION_TAG}-draft"
        OFFICIAL_IMAGE="nethermind/juno:${VERSION_TAG}"
        LATEST_IMAGE="nethermind/juno:latest"
        
        # Retag and push official version image
        docker buildx imagetools create -t ${OFFICIAL_IMAGE} ${DRAFT_IMAGE}
        docker buildx imagetools push ${OFFICIAL_IMAGE}
        
        # Retag and push latest image
        docker buildx imagetools create -t ${LATEST_IMAGE} ${DRAFT_IMAGE}
        docker buildx imagetools push ${LATEST_IMAGE}