name: p2p-sync-test

on:
  workflow_call:
    inputs:
      JUNO_VERSION:
        required: true
        type: string
          
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Kurtosis CLI
        run: |
          echo "deb [trusted=yes] https://apt.fury.io/kurtosis-tech/ /" | sudo tee /etc/apt/sources.list.d/kurtosis.list
          sudo apt update
          sudo apt install kurtosis-cli
      - name: Run p2p sync tests
        run: |
          kurtosis run github.com/nethermindeth/juno-sync-test '{"juno_version":"${{ inputs.JUNO_VERSION }}"}'
