name: Pre-merge e2e checks

env:
  DOCKER_REGISTRY: nethermind.jfrog.io
  REPO_DEV: nubia-oci-local-dev

on:
  merge_group:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  dev:
    uses: ./.github/workflows/dev-environment-pipeline.yml
    secrets:
      ARTIFACTORY_NUBIA_USERNAME: ${{ secrets.ARTIFACTORY_NUBIA_USERNAME }}
      ARTIFACTORY_NUBIA_TOKEN_DEVELOPER: ${{ secrets.ARTIFACTORY_NUBIA_TOKEN_DEVELOPER }}
      DEV_SEPOLIA_URL: ${{ secrets.DEV_SEPOLIA_URL }}
      TEST_ACCOUNT_ADDRESS: ${{ secrets.TEST_ACCOUNT_ADDRESS }}
      TEST_ACCOUNT_PRIVATE_KEY: ${{ secrets.TEST_ACCOUNT_PRIVATE_KEY }}