name: Dispatch Render for Juno Prod

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Enter image tag to be deployed'
        required: true

env:
  EVENT_NAME: juno-prod
  IMAGE_TAG: ${{github.event.inputs.tag}}
  GOERLI: apps/juno-prod/overlays/prod-goerli-1/config.yaml
  GOERLI2: apps/juno-prod/overlays/prod-goerli-2/config.yaml
  TESTNET: apps/juno-prod/overlays/prod-integration/config.yaml
  MAINNET: apps/juno-prod/overlays/prod-mainnet/config.yaml

permissions:
  id-token: write
  contents: write

jobs:
  deploy:
      environment: production
      runs-on: ubuntu-latest

      steps:
      - name: Checkout
        uses: actions/checkout@v3
        
  
      - name: Repository Dispatch
        env:
          IMAGE_TAG: ${{ github.event.inputs.tag }}
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token ${{ secrets.ACCESS_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/NethermindEth/argo/dispatches \
          -d '{"event_type": "${{ env.EVENT_NAME }}", "client-payload":{"name": "${{ env.EVENT_NAME }}", "goerli_config": "${{ env.GOERLI }}", "goerli2_config": "${{ env.GOERLI2 }}", "testnet_config": "${{ env.TESTNET }}", "mainnet_config": "${{ env.MAINNET }}", "tag": "${{ env.IMAGE_TAG }}"}}'
          
