name: rust-lint
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
    paths:
      - vm/rust/**
      - starknet/compiler/rust/**
      - rust-toolchain.toml
      - .github/workflows/rust-lint.yml
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  rust-lint:
    name: rust-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # master
        with:
          toolchain: "1.94.1"
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.8.1
        with:
          workspaces: |
            vm/rust
            starknet/compiler/rust
      - name: fmt vm/rust
        run: cargo fmt --check
        working-directory: vm/rust
      - name: fmt starknet/compiler/rust
        run: cargo fmt --check
        working-directory: starknet/compiler/rust
      - name: clippy vm/rust
        run: cargo clippy -- -D warnings
        working-directory: vm/rust
      - name: clippy starknet/compiler/rust
        run: cargo clippy -- -D warnings
        working-directory: starknet/compiler/rust
