name: starknet-rust tests
permissions:
  contents: read

on:
  workflow_call:
    inputs:
      ref:
        type: string
        default: "0.19.0-rc.2"
        description: "starknet-rust version/tag to test"
    secrets:
      STARKNET_RPC:
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v6.0.2
        with:
          repository: software-mansion/starknet-rust
          ref: ${{ inputs.ref }}

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Run jsonrpc providers tests
        env:
          RUST_BACKTRACE: full
          TEST_NODE_URL: ${{ secrets.STARKNET_RPC }}
        run: |
          cd starknet-rust-providers

          # Sepolia is at 0.14.2, while tests expect 0.14.1
          cargo test jsonrpc -- --skip jsonrpc_starknet_version --skip jsonrpc_spec_version

      - name: Run jsonrpc account tests
        env:
          RUST_BACKTRACE: full
          TEST_NODE_URL: ${{ secrets.STARKNET_RPC }}
        run: |
          cd starknet-rust-accounts
          cargo test jsonrpc -- --skip can_estimate_declare_v3_fee_with_jsonrpc --skip can_declare_cairo1_contract_v3_with_jsonrpc
